import type {DecisionPriority,DecisionStatus,GovernedDecision} from "@/domain/decisions/types";import type {EvidenceSource} from "@/domain/evidence/types";import type {HealthStatus,QualificationStatus,Trend} from "@/domain/accounts/account-digital-twin";
export type RenewalWorkspaceMode="deterministic-baseline"|"real-provider"|"artifact-replay";export type IndicatorDirection="improving"|"stable"|"declining"|"unknown";
export interface RenewalEvidenceReference{id:string;title:string;summary:string;source:EvidenceSource|string;timestamp:string;confidence:number;factIds:string[];lineageIds:string[];conflictIds:string[];freshness:string;}
export interface RenewalExecutiveSummary{healthScore:number;healthStatus:HealthStatus;arr:number;renewalDate:string;riskTrend:Trend;renewalConfidence:number;revenueAtRisk:number;topRecommendation:string;aiConfidence:number;evaluationScore:number;humanStatus:DecisionStatus;}
export interface RenewalHealthDriver{id:string;rank:number;label:string;summary:string;trend:IndicatorDirection;confidence:number;businessImpact:string;evidenceIds:string[];}
export interface RenewalMEDDPICCSection{key:string;label:string;status:QualificationStatus;coverage:number;confidence:number;value:string;supportingEvidence:RenewalEvidenceReference[];missingInformation:string[];recommendedAction:string;}
export interface RenewalLeadingIndicator{id:string;label:string;currentValue:string;previousValue:string;direction:IndicatorDirection;confidence:number;evidenceIds:string[];explanation:string;}
export interface RenewalPlay{id:string;decisionId:string;title:string;priority:DecisionPriority;expectedImpact:string;estimatedRevenueProtected:number;requiredParticipants:string[];recommendedOwner:string;suggestedDeadline:string;supportingEvidence:RenewalEvidenceReference[];reasoningSummary:string;recommendedAction:string;aiConfidence:number;evaluationScore:number;humanStatus:DecisionStatus;governedDecision:GovernedDecision;}
export interface RenewalTimelineItem{id:string;kind:"event"|"signal"|"risk-change"|"meeting"|"stakeholder-change"|"milestone";title:string;summary:string;timestamp:string;upcoming:boolean;source:string;}
export interface RenewalNarrative{whatChanged:string[];biggestRisks:string[];biggestOpportunity:string[];whatToDoToday:string[];}
export interface RenewalWorkspaceViewModel{accountId:string;accountName:string;ownerName:string;asOf:string;mode:RenewalWorkspaceMode;modeLabel:string;artifactId?:string;regressionStatus:"clear"|"warning"|"blocked";executiveSummary:RenewalExecutiveSummary;healthDrivers:RenewalHealthDriver[];meddpicc:{coverage:number;decisionConfidence:number;missingEvidenceCount:number;sections:RenewalMEDDPICCSection[];};leadingIndicators:RenewalLeadingIndicator[];plays:RenewalPlay[];timeline:RenewalTimelineItem[];evidence:RenewalEvidenceReference[];narrative:RenewalNarrative;}
