import { NextResponse } from "next/server";
import { recordAudit } from "@/auth/audit.server";
import { identityRepository } from "@/auth/repository.server";
import { getAuthenticatedIdentity,getRawSessionUser } from "@/auth/session.server";
import { createOrganizationUser,parseUserAdministrationInput,updateOrganizationUser } from "@/auth/user-administration";
import { toPublicUser } from "@/auth/types";

async function admin(){const actor=await getRawSessionUser(),identity=await getAuthenticatedIdentity();return actor&&identity&&["ORG_OWNER","ORG_ADMIN"].includes(identity.membership.adminRole)?actor:null}
export async function GET(){const actor=await admin();if(!actor)return NextResponse.json({error:"Organization administrator access is required."},{status:403});const users=identityRepository.read().users.filter(user=>user.organizationId===actor.organizationId).map(toPublicUser);return NextResponse.json({users})}
export async function POST(request:Request){const actor=await admin();if(!actor)return NextResponse.json({error:"Organization administrator access is required."},{status:403});let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid request."},{status:400})}const input=parseUserAdministrationInput(body,true);if(!input)return NextResponse.json({error:"Enter valid user details and a password of at least 8 characters."},{status:400});const result=createOrganizationUser(identityRepository,actor,input);if(!result.ok)return NextResponse.json({error:result.error},{status:400});recordAudit(actor,{event:"organization.user.created",resourceType:"user",resourceId:result.user.id,after:{...toPublicUser(result.user)}});return NextResponse.json({user:toPublicUser(result.user)},{status:201})}
export async function PATCH(request:Request){const actor=await admin();if(!actor)return NextResponse.json({error:"Organization administrator access is required."},{status:403});let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid request."},{status:400})}if(!body||typeof body!=="object"||typeof (body as {id?:unknown}).id!=="string")return NextResponse.json({error:"A user ID is required."},{status:400});const id=(body as {id:string}).id,input=parseUserAdministrationInput(body,false);if(!input)return NextResponse.json({error:"Enter valid user details. New passwords must be at least 8 characters."},{status:400});const before=identityRepository.findUserById(id);const result=updateOrganizationUser(identityRepository,actor,id,input);if(!result.ok)return NextResponse.json({error:result.error},{status:400});recordAudit(actor,{event:"organization.user.updated",resourceType:"user",resourceId:id,before:before?{...toPublicUser(before)}:undefined,after:{...toPublicUser(result.user)}});return NextResponse.json({user:toPublicUser(result.user)})}
