import type {LLMProvider,LLMRequest,LLMResponse,LLMRetryPolicy,ModelDefinition,ModelRegistry} from "@/domain/llm-provider/types";
import type {PromptPackage} from "@/domain/prompts/types";
export type DeploymentEnvironment="development"|"test"|"staging"|"production";
export type CredentialSource="environment"|"development-secret"|"secret-manager"|"workload-identity"|"none";
export type CredentialType="api-key"|"oauth-token"|"managed-identity"|"service-account"|"none";
export interface ProviderCredentialReference{referenceId:string;providerId:string;credentialType:CredentialType;source:CredentialSource;locator:string;environment:DeploymentEnvironment;required:boolean;allowLocalFallback:boolean;metadata:Record<string,string|number|boolean>;}
export interface ResolvedProviderCredential{providerId:string;credentialType:CredentialType;source:CredentialSource;resolved:boolean;expiresAt?:string;metadata:Record<string,string|number|boolean>;toJSON():Record<string,unknown>;}
export interface CredentialResolutionResult{credential?:ResolvedProviderCredential;errors:ProviderError[];warnings:string[];resolvedAt:string;}
export interface CredentialResolver{source:CredentialSource;resolve(reference:ProviderCredentialReference,environment:DeploymentEnvironment):Promise<CredentialResolutionResult>;}
export interface CredentialResolverRegistry{resolvers:ReadonlyMap<CredentialSource,CredentialResolver>;}
export type ProviderStatus="active"|"experimental"|"deprecated"|"unavailable"|"disabled";
export interface ProviderCapabilities{providerId:string;modelId:string;supportsStructuredOutput:boolean;supportsJsonObject:boolean;supportsJsonSchema:boolean;supportsStreaming:boolean;supportsCancellation:boolean;supportsToolCalling:boolean;supportsSystemMessages:boolean;supportsDeveloperMessages:boolean;supportsUsageReporting:boolean;supportsRequestTimeout:boolean;supportsSeed:boolean;maximumContextTokens:number;maximumOutputTokens:number;supportedInputModalities:readonly ("text"|"image"|"audio"|"file")[];supportedOutputModalities:readonly ("text"|"structured-json")[];supportedSchemaVersions:readonly string[];capabilityVersion:string;status:ProviderStatus;limitations:readonly string[];}
export interface ProviderRequestRequirements{requireStructuredOutput:boolean;requireJsonSchema:boolean;requireCancellation:boolean;requireUsageReporting:boolean;requireSystemMessages:boolean;requireDeveloperMessages:boolean;requireStreaming:boolean;requiredContextTokens:number;requiredOutputTokens:number;requiredSchemaVersion:string;allowedModalities:readonly string[];prohibitedCapabilities:readonly string[];policyVersion:string;}
export interface CapabilityNegotiationResult{compatible:boolean;providerId:string;modelId:string;requirements:ProviderRequestRequirements;capabilities?:ProviderCapabilities;missingCapabilities:string[];warnings:string[];fallbackAllowed:boolean;fallbackCandidates:string[];explanation:string;negotiatedAt:string;}
export interface ProviderExecutionPolicy{requireCredential:boolean;requireCapabilityNegotiation:boolean;requireCancellationSupport:boolean;allowRetries:boolean;allowRecording:boolean;allowReplay:boolean;allowRealProvider:boolean;failClosed:boolean;maximumAttempts:number;timeoutMs:number;policyVersion:string;}
export interface ProviderDeploymentConfig{environment:DeploymentEnvironment;realProviderCallsAllowed:boolean;enabledProviders:string[];enabledModels:string[];defaultProviderId:string;defaultModelId:string;credentialReferences:ProviderCredentialReference[];requestTimeoutMs:number;retryPolicy:LLMRetryPolicy;cancellationRequired:boolean;recordingPolicy:"allowed"|"prohibited";replayPolicy:"allowed"|"prohibited";diagnosticsPolicy:"minimal"|"development";modelAllowlist:string[];providerAllowlist:string[];maximumInputTokens:number;maximumOutputTokens:number;structuredOutputRequired:boolean;failClosed:boolean;fallbackAllowed:boolean;configurationVersion:string;}
export interface ProviderConfigValidationResult{valid:boolean;errors:ProviderError[];warnings:string[];environment:DeploymentEnvironment;configurationVersion:string;validatedAt:string;}
export interface ProviderExecutionContext{environment:DeploymentEnvironment;providerId:string;modelId:string;credentialReferenceId?:string;capabilities:ProviderCapabilities;executionPolicy:ProviderExecutionPolicy;requestStartedAt:string;deadlineAt:string;traceId:string;configurationVersion:string;capabilityVersion:string;credentialResolutionMetadata:Record<string,string|number|boolean>;diagnosticsEnabled:boolean;}
export type ProviderErrorCategory="configuration"|"authentication"|"authorization"|"capability"|"cancellation"|"timeout"|"rate-limit"|"provider-unavailable"|"invalid-request"|"invalid-response"|"transient"|"unknown";
export interface ProviderError{code:string;category:ProviderErrorCategory;message:string;providerId?:string;modelId?:string;requestId?:string;retryable:boolean;cancelled:boolean;timeout:boolean;rateLimited:boolean;authenticationFailed:boolean;authorizationFailed:boolean;capabilityMismatch:boolean;configurationError:boolean;details:Record<string,string|number|boolean>;occurredAt:string;}
export interface ProviderSelectionResult{selectedProviderId?:string;selectedModelId?:string;credentialReference?:ProviderCredentialReference;capabilities?:ProviderCapabilities;warnings:string[];fallbackUsed:boolean;selectionReason:string;valid:boolean;errors:ProviderError[];}
export interface ProviderRegistry{providers:ReadonlyMap<string,LLMProvider>;capabilities:readonly ProviderCapabilities[];realProviderIds:readonly string[];}
export type ProviderReadinessEventType="provider-config-loaded"|"provider-config-validation-passed"|"provider-config-validation-failed"|"credential-resolution-started"|"credential-resolution-succeeded"|"credential-resolution-failed"|"capability-negotiation-started"|"capability-negotiation-succeeded"|"capability-negotiation-failed"|"provider-selected"|"provider-selection-failed"|"provider-request-started"|"provider-request-cancelled"|"provider-request-timed-out"|"provider-request-retried"|"provider-request-completed"|"provider-request-failed"|"conformance-suite-started"|"conformance-suite-completed"|"conformance-case-failed";
export interface ProviderReadinessAuditEvent{id:string;traceId:string;requestId?:string;providerId?:string;modelId?:string;environment:DeploymentEnvironment;eventType:ProviderReadinessEventType;timestamp:string;details:Record<string,string|number|boolean>;}
export interface ProviderConformanceCaseResult{caseId:string;passed:boolean;skipped:boolean;reason:string;durationMs:number;findings:string[];diagnostics:Record<string,string|number|boolean>;}
export interface ProviderConformanceReport{providerId:string;providerVersion:string;contractVersion:string;startedAt:string;completedAt:string;totalCases:number;passedCases:number;failedCases:number;skippedCases:number;requiredFailureCount:number;conformant:boolean;caseResults:ProviderConformanceCaseResult[];warnings:string[];metadata:Record<string,string|number|boolean>;}
export interface ReadinessExecutionInput{request:LLMRequest;promptPackage:PromptPackage;deploymentConfig:ProviderDeploymentConfig;providerRegistry:ProviderRegistry;modelRegistry:ModelRegistry;signal?:AbortSignal;}
export type ReadinessExecutionResult={response?:LLMResponse;errors:ProviderError[];selection:ProviderSelectionResult;negotiation?:CapabilityNegotiationResult;context?:ProviderExecutionContext;};
export type ReadinessModelDefinition=ModelDefinition&{capabilities:ProviderCapabilities;environmentsAllowed:DeploymentEnvironment[];displayName:string;defaultForTasks:string[];aliases:string[];configurationVersion:string;};
