import type {AgentTaskType,AgentType} from "@/domain/agents/types";
import type {CitationPolicy,PromptBuildPolicy,PromptContextSectionPolicy,PromptSelectionPolicy,UncertaintyInstructionPolicy} from "@/domain/prompts/types";
import {contextVersions} from "@/llm-context";
import {reasoningVersions} from "@/agent-reasoning/config";

export const promptVersions={registryVersion:"prompt-registry-v1",builderVersion:"prompt-builder-v1",fixtureVersion:"prompt-fixtures-v1",auditVersion:"prompt-audit-v1",citationPolicyVersion:"citation-policy-v1",uncertaintyPolicyVersion:"uncertainty-policy-v1",buildPolicyVersion:"prompt-build-policy-v1"} as const;
export const agentTaskCompatibility:Record<AgentType,AgentTaskType[]>={"renewal-agent":["assess-risk"],"expansion-agent":["identify-opportunity"],"relationship-agent":["review-relationship"],"forecast-agent":["review-forecast"],"executive-agent":["recommend-executive-action"],"meeting-preparation-agent":["prepare-meeting"]};
export const defaultCitationPolicy:CitationPolicy={materialClaimTypes:["financial-impact","date","stakeholder","relationship","product-usage","renewal","opportunity","forecast","meeting","risk","qualification"],minimumCitationsPerMaterialClaim:1,requireFactIds:true,requireEvidenceIds:true,requireLineageIdsForCriticalClaims:true,allowConflictIds:true,allowUncitedRecommendations:false,citationFormat:"DecisionClaim factIds/evidenceIds/conflictIds/lineageIds arrays",missingCitationBehavior:"omit-claim",invalidCitationBehavior:"fail-output",policyVersion:promptVersions.citationPolicyVersion};
export const defaultUncertaintyPolicy:UncertaintyInstructionPolicy={labelInferredClaims:true,labelDisputedClaims:true,labelStaleClaims:true,prohibitUnsupportedCertainty:true,requireConfidenceRationale:true,requireCaveatWhenMaterialConflictExists:true,requireDataGapAcknowledgement:true,policyVersion:promptVersions.uncertaintyPolicyVersion};
export const prohibitedBehaviors=["Invent stakeholders, financial values, dates, evidence IDs, fact IDs, or lineage IDs.","Use cross-account references.","Present disputed values as certain or ignore material conflicts.","Claim an email, meeting, CRM update, Outreach action, or other external action occurred.","Bypass human approval or override governance policy.","Return prose outside the required structured output.","Reveal hidden chain-of-thought; provide only the concise reasoningSummary field.","Include raw source payloads or unreconciled source records."];
const allSections=["account-summary","commercial","renewal","opportunities","stakeholders","relationships","product-usage","qualification","recent-changes","timeline","risks","expansion-signals","unresolved-questions","decisions","evidence","caveats","data-confidence","source-coverage","provenance"] as const;
const policy=(required:PromptContextSectionPolicy["requiredSections"],optional:PromptContextSectionPolicy["optionalSections"]):PromptContextSectionPolicy=>({requiredSections:required,optionalSections:optional,prohibitedSections:[],sectionOrder:allSections.filter(section=>required.includes(section)||optional.includes(section)),maximumItemsPerSection:{stakeholders:8,timeline:8,evidence:10,decisions:6,qualification:8,"product-usage":4,opportunities:5,"recent-changes":6,"unresolved-questions":8},includeEmptySections:false,includeOmissions:true,includeSourceCoverage:true,includeProvenanceIndex:true,includeConflictDetails:true,includeHistoricalDecisions:true});
const core:PromptContextSectionPolicy["requiredSections"]=["account-summary","commercial","evidence","caveats","data-confidence","provenance"];
export const contextSectionPolicies:Record<AgentType,PromptContextSectionPolicy>={
 "renewal-agent":policy([...core,"renewal"],["stakeholders","relationships","product-usage","qualification","recent-changes","timeline","risks","unresolved-questions","decisions","source-coverage"]),
 "expansion-agent":policy([...core,"opportunities","product-usage"],["stakeholders","relationships","qualification","recent-changes","timeline","risks","expansion-signals","unresolved-questions","decisions","source-coverage"]),
 "relationship-agent":policy([...core,"stakeholders","relationships"],["qualification","recent-changes","timeline","risks","unresolved-questions","decisions","source-coverage"]),
 "forecast-agent":policy([...core,"opportunities","qualification"],["stakeholders","relationships","recent-changes","timeline","risks","unresolved-questions","decisions","source-coverage"]),
 "executive-agent":policy(core,["renewal","opportunities","stakeholders","relationships","product-usage","qualification","recent-changes","timeline","risks","expansion-signals","unresolved-questions","decisions","source-coverage"]),
 "meeting-preparation-agent":policy([...core,"stakeholders","timeline","unresolved-questions"],["renewal","opportunities","relationships","qualification","recent-changes","risks","decisions","source-coverage"])
};
export const defaultPromptBuildPolicy:PromptBuildPolicy={maximumPromptTokens:20000,reservedOutputTokens:1200,includeSchema:true,includeExamples:false,includeContextMetadata:true,includeDiagnostics:false,includePromptChangelog:false,strictOutputOnly:true,allowExperimentalPrompts:false,fallbackBehavior:"fail",deterministicFormatting:true,policyVersion:promptVersions.buildPolicyVersion};
export const defaultPromptSelectionPolicy:PromptSelectionPolicy={allowFallback:false,allowDeprecatedExplicit:true,allowExperimental:false,supportedContextVersions:[contextVersions.contextVersion],supportedOutputSchemaVersions:[reasoningVersions.decisionCandidateSchemaVersion],supportedEvaluationPolicyVersions:[reasoningVersions.evaluationPolicyVersion]};
export const agentPromptDefaults:Record<AgentType,string>={"renewal-agent":"renewal-assess-risk","expansion-agent":"expansion-identify-opportunity","relationship-agent":"relationship-review","forecast-agent":"forecast-review","executive-agent":"executive-recommend-action","meeting-preparation-agent":"meeting-prepare"};
