import type {AccountDigitalTwin,AccountSnapshot,SnapshotChange} from "@/domain/accounts/account-digital-twin";import type {AgentEvaluationResult,CandidateEligibilityResult} from "@/domain/agent-evaluation/types";import type {AgentReasoningResult} from "@/domain/agent-reasoning/types";import type {AgentType,AgentTaskType} from "@/domain/agents/types";import type {DecisionCandidate,DecisionPriority,GovernedDecision} from "@/domain/decisions/types";import type {EvaluationArtifact} from "@/domain/evaluation-artifacts/types";import type {AgentContextBuildResult,AgentContextPackage} from "@/domain/llm-context/types";import type {ResolvedAccountContext} from "@/domain/reconciliation/types";import type {RenewalWorkspaceViewModel} from "@/domain/renewal-intelligence/types";import type {SourceRecord} from "@/domain/sources/types";import type {DecisionControlResult} from "@/decision-control";
export type SimulationExecutionMode="deterministic"|"replay"|"real-provider-development";export type SimulationSessionStatus="draft"|"ready"|"running"|"paused"|"completed"|"failed"|"reset";export type SimulationScenarioStatus="draft"|"active"|"deprecated"|"archived";export type SimulationSeverity="informational"|"low"|"medium"|"high"|"critical";export type SimulationDomain="commercial"|"renewal"|"stakeholder"|"relationship"|"product-usage"|"support"|"security"|"legal"|"procurement"|"opportunity"|"forecast"|"qualification"|"external-environment";
export const simulationEventTypes=["champion-left","champion-promoted","executive-engagement-declined","executive-meeting-completed","executive-meeting-cancelled","product-usage-declined","product-usage-increased","support-escalation-opened","support-escalation-resolved","security-review-stalled","security-review-approved","legal-review-stalled","legal-review-completed","procurement-delayed","procurement-completed","renewal-date-changed","contract-value-changed","competitor-entered","budget-freeze","strategic-initiative-announced","stakeholder-sentiment-improved","stakeholder-sentiment-declined","opportunity-stage-advanced","opportunity-stage-stalled","economic-buyer-confirmed","economic-buyer-missing","meddpicc-field-confirmed","meddpicc-field-became-stale","external-news-risk","external-news-opportunity"] as const;export type SimulationEventType=(typeof simulationEventTypes)[number];
export interface SimulationEvent{eventId:string;eventType:SimulationEventType;accountId:string;effectiveAt:string;observedAt:string;severity:SimulationSeverity;sourceType:string;title:string;description:string;affectedDomains:SimulationDomain[];expectedImpact:string;payload:{stakeholderId?:string;stakeholderName?:string;productId?:string;percentageChange?:number;status?:string;date?:string;amount?:number;meddpiccKey?:string;value?:string;participants?:string[];opportunityId?:string;headline?:string;};metadata:{synthetic:true;hypothesis?:string;scenarioId?:string;};}
export interface ExpectedSimulationBehavior{expectedHealthDirection:"increase"|"decrease"|"stable"|"any";expectedConfidenceDirection:"increase"|"decrease"|"stable"|"any";expectedPriorityDirection:"increase"|"decrease"|"stable"|"any";expectedDecisionTypes:string[];prohibitedDecisionTypes:string[];expectedIndicatorChanges:Record<string,"increase"|"decrease"|"change"|"stable">;expectedMeddpiccChanges:Record<string,string>;requiredRecommendations:string[];prohibitedRecommendations:string[];requiredCaveats:string[];expectedEvidenceSources:string[];maximumUnsupportedClaims:number;humanReviewRequired:boolean;}
export interface SimulationScenario{scenarioId:string;name:string;description:string;version:string;accountId:string;agentType:AgentType;taskType:AgentTaskType;baselineFixtureId:string;initialSimulatedTime:string;objective:string;expectedBehavior:ExpectedSimulationBehavior;availableEventTypes:SimulationEventType[];predefinedEvents:SimulationEvent[];successCriteria:string[];suggestedReviewQuestions:string[];tags:string[];status:SimulationScenarioStatus;metadata:{synthetic:true;weekScenario:boolean;};}
export interface SimulationClock{baselineTime:string;currentTime:string;timezone:string;elapsedDurationMs:number;stepCount:number;frozen:boolean;}
export interface SimulationAccountState{asOf:string;sourceRecords:SourceRecord[];resolvedAccountContext:ResolvedAccountContext;accountDigitalTwin:AccountDigitalTwin;agentContextPackage:AgentContextPackage;decisionCandidates:DecisionCandidate[];evaluations:AgentEvaluationResult[];governedDecisions:GovernedDecision[];renewalWorkspaceViewModel:RenewalWorkspaceViewModel;snapshot:AccountSnapshot;artifacts:EvaluationArtifact[];diagnostics:Record<string,string|number|boolean>;}
export interface IndicatorChange{indicatorId:string;label:string;previousValue:string;currentValue:string;direction:string;confidenceChange:number;evidenceAdded:string[];explanation:string;}
export interface MEDDPICCChange{key:string;previousStatus:string;currentStatus:string;confidenceDelta:number;evidenceAdded:string[];gapsAdded:string[];gapsResolved:string[];previousAction:string;currentAction:string;}
export interface RecommendationChange{previousDecisionId?:string;currentDecisionId?:string;changeType:"created"|"removed"|"escalated"|"de-escalated"|"revised"|"unchanged"|"blocked"|"review-required";previousPriority?:DecisionPriority;currentPriority?:DecisionPriority;previousRecommendation?:string;currentRecommendation?:string;businessImpactChange:number;confidenceChange:number;evidenceChange:string[];explanation:string;}
export interface SimulationStateComparison{healthChanges:{previousScore:number;currentScore:number;delta:number;previousStatus:string;currentStatus:string;changedDrivers:string[];explanation:string};renewalChanges:SnapshotChange[];leadingIndicatorChanges:IndicatorChange[];meddpiccChanges:MEDDPICCChange[];stakeholderChanges:string[];commercialChanges:string[];conflictChanges:string[];dataQualityChanges:string[];decisionChanges:string[];recommendationChanges:RecommendationChange[];evidenceChanges:string[];timelineChanges:string[];summary:string;materialChangeCount:number;}
export interface SimulationAssertionResult{assertionId:string;category:"health-direction"|"confidence-direction"|"priority-direction"|"decision-type"|"prohibited-decision"|"indicator-change"|"meddpicc-change"|"recommendation-content"|"caveat-presence"|"evidence-source"|"unsupported-claim"|"human-review";passed:boolean;severity:"info"|"warning"|"error";expected:string;actual:string;explanation:string;blocking:boolean;}
export interface SimulationReview{reviewId:string;sessionId:string;stepId:string;reviewer:string;reviewedAt:string;recommendationCorrectness:number;actionability:number;evidenceSufficiency:number;businessImpactAccuracy:number;confidenceAppropriateness:number;priorityAppropriateness:number;changeAppropriateness:number;wouldTakeAction:boolean;savedTimeEstimateMinutes:number;decision:"appropriate"|"mostly-appropriate"|"needs-improvement"|"inappropriate";flags:("overreacted"|"underreacted"|"unsupported-claim"|"missed-signal"|"wrong-priority"|"weak-action"|"missing-caveat"|"stale-evidence"|"duplicate-recommendation"|"other")[];comments:string;}
export interface SimulationQualityScorecard{recommendationCorrectness:number;actionability:number;evidenceSufficiency:number;businessImpactAccuracy:number;confidenceAppropriateness:number;priorityAppropriateness:number;changeAppropriateness:number;wouldTakeActionRate:number;averageTimeSaved:number;unsupportedClaimRate:number;missedSignalRate:number;overallScore:number;readinessStatus:"not-ready"|"needs-improvement"|"internally-ready"|"design-partner-ready";}
export interface SimulationDiagnostics{eventsProcessed:number;sourceRecordsCreated:number;factsChanged:number;conflictsCreated:number;conflictsResolved:number;twinSectionsUpdated:number;contextsRebuilt:number;providerCalls:number;replayCalls:number;evaluationsRun:number;decisionsCreated:number;decisionsChanged:number;assertionsPassed:number;assertionsFailed:number;buildDurationMs:number;warnings:string[];errors:string[];}
export interface SimulationStep{stepId:string;sessionId:string;sequence:number;startedAt:string;completedAt:string;simulatedTime:string;appliedEventIds:string[];addedSourceRecordIds:string[];changedFactIds:string[];affectedTwinSections:string[];beforeSnapshot:AccountSnapshot;afterSnapshot:AccountSnapshot;contextBuildResult:AgentContextBuildResult;reasoningResult?:AgentReasoningResult;evaluationResult?:AgentEvaluationResult;eligibilityResult?:CandidateEligibilityResult;governedDecisionResult?:DecisionControlResult;comparison:SimulationStateComparison;expectedBehaviorResult:SimulationAssertionResult[];state:SimulationAccountState;diagnostics:SimulationDiagnostics;analytics?:import("@/domain/simulation/analytics-types").SimulationStepAnalytics;status:"pending"|"running"|"completed"|"completed-with-warnings"|"failed";}
export interface SimulationSession{sessionId:string;scenarioId:string;scenarioVersion:string;accountId:string;accountName:string;agentType:AgentType;taskType:AgentTaskType;status:SimulationSessionStatus;createdAt:string;updatedAt:string;baselineTime:string;currentSimulatedTime:string;executionMode:SimulationExecutionMode;baselineState:SimulationAccountState;currentState:SimulationAccountState;queuedEvents:SimulationEvent[];appliedEvents:SimulationEvent[];simulationSteps:SimulationStep[];humanReviews:SimulationReview[];diagnostics:SimulationDiagnostics;analytics?:import("@/domain/simulation/analytics-types").SimulationAnalyticsAggregate;metadata:{simulatorVersion:string;synthetic:true;};}
export interface RevenueSimulationResult{session:SimulationSession;completed:boolean;errors:string[];}
