import type { AIConsoleSearchMatch, AIConsoleTraceFilter, AIExecutionStageKey, AIExecutionTrace } from "@/domain/ai-developer-console/types";
import { aiDeveloperConsoleConfig } from "../config";
import { getTraceStages } from "../traces/build-trace";
import { stableStringify } from "../redaction/redact";

export function filterAIExecutionTraces(traces:readonly AIExecutionTrace[],filter:AIConsoleTraceFilter):AIExecutionTrace[]{const query=filter.query?.toLowerCase();return traces.filter(trace=>(!filter.accountId||trace.accountId===filter.accountId)&&(!filter.scenarioId||trace.scenarioId===filter.scenarioId)&&(!filter.executionMode||trace.executionMode===filter.executionMode)&&(!filter.promptVersion||trace.metadata.promptVersion===filter.promptVersion)&&(!filter.provider||trace.metadata.provider===filter.provider)&&(!filter.model||trace.metadata.model===filter.model)&&(!filter.verdict||trace.metadata.evaluationVerdict===filter.verdict)&&(filter.eligible===undefined||trace.metadata.eligible===filter.eligible)&&(!filter.status||trace.status===filter.status)&&(!query||stableStringify(trace).toLowerCase().includes(query))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||a.traceId.localeCompare(b.traceId));}

export function searchAIExecutionTrace(trace:AIExecutionTrace,query:string):AIConsoleSearchMatch[]{const target=query.trim().toLowerCase();if(!target)return[];const matches:AIConsoleSearchMatch[]=[];const visit=(stage:AIExecutionStageKey,value:unknown,path:string)=>{if(matches.length>=aiDeveloperConsoleConfig.maximumSearchMatches)return;if(typeof value==="string"&&value.toLowerCase().includes(target))matches.push({stage,path,excerpt:value.length>180?`${value.slice(0,177)}…`:value});else if(Array.isArray(value))value.forEach((item,index)=>visit(stage,item,`${path}[${index}]`));else if(value&&typeof value==="object")Object.entries(value).forEach(([key,item])=>visit(stage,item,path?`${path}.${key}`:key));};for(const[key,value]of getTraceStages(trace))visit(key,value.output,"output");return matches;}

export function buildChronologicalTimeline(trace:AIExecutionTrace){const entries=getTraceStages(trace).flatMap(([key,value])=>[{id:`${key}-start`,stage:key,label:`${value.stageName} ${value.status==="unavailable"?"unavailable":"started"}`,timestamp:value.startedAt??trace.createdAt,status:value.status},...(value.completedAt?[{id:`${key}-complete`,stage:key,label:`${value.stageName} ${value.status}`,timestamp:value.completedAt,status:value.status}]:[])]);return entries.sort((a,b)=>a.timestamp.localeCompare(b.timestamp)||a.id.localeCompare(b.id));}
