import type {AgentEvaluationResult,EvaluationPolicy,EvaluationVerdict} from "@/domain/agent-evaluation/types";
import type {AgentReasoner,AgentReasoningRequest,AgentReasoningResult} from "@/domain/agent-reasoning/types";
import type {AgentTaskType,AgentType} from "@/domain/agents/types";
import type {AgentContextPackage,ContextSection} from "@/domain/llm-context/types";

export type PromptStatus="draft"|"active"|"deprecated"|"experimental"|"archived";
export type PromptRole="system"|"developer"|"user";
export type PromptPlaceholder="agentRole"|"taskObjective"|"taskConstraints"|"accountName"|"contextPackage"|"outputSchema"|"citationPolicy"|"uncertaintyPolicy"|"prohibitedBehaviors"|"currentTime"|"timeHorizon";
export interface PromptMetadata{author:string;owner:string;intendedUse:string;knownLimitations:string[];testCoverage:string[];releaseNotes:string;supersedesPromptId?:string;providerNotes?:string[];synthetic:boolean;traceabilityRequired:boolean;}
export interface PromptChangelogEntry{version:string;date:string;author:string;summary:string;changeType:"major"|"minor"|"patch";expectedBehaviorImpact:string;relatedEvaluationScenarioIds:string[];}
export interface PromptContextSectionPolicy{requiredSections:ContextSection[];optionalSections:ContextSection[];prohibitedSections:ContextSection[];sectionOrder:ContextSection[];maximumItemsPerSection:Partial<Record<ContextSection,number>>;includeEmptySections:boolean;includeOmissions:boolean;includeSourceCoverage:boolean;includeProvenanceIndex:boolean;includeConflictDetails:boolean;includeHistoricalDecisions:boolean;}
export interface CitationPolicy{materialClaimTypes:string[];minimumCitationsPerMaterialClaim:number;requireFactIds:boolean;requireEvidenceIds:boolean;requireLineageIdsForCriticalClaims:boolean;allowConflictIds:boolean;allowUncitedRecommendations:boolean;citationFormat:string;missingCitationBehavior:"omit-claim"|"fail-output";invalidCitationBehavior:"omit-claim"|"fail-output";policyVersion:string;}
export interface UncertaintyInstructionPolicy{labelInferredClaims:boolean;labelDisputedClaims:boolean;labelStaleClaims:boolean;prohibitUnsupportedCertainty:boolean;requireConfidenceRationale:boolean;requireCaveatWhenMaterialConflictExists:boolean;requireDataGapAcknowledgement:boolean;policyVersion:string;}
export interface PromptDefinition{promptId:string;name:string;description:string;agentType:AgentType;supportedTaskTypes:AgentTaskType[];version:string;status:PromptStatus;systemInstructionTemplate:string;taskInstructionTemplate:string;outputInstructionTemplate:string;evidenceInstructionTemplate:string;uncertaintyInstructionTemplate:string;prohibitedBehaviorTemplate:string;contextSectionPolicy:PromptContextSectionPolicy;citationPolicy:CitationPolicy;uncertaintyPolicy:UncertaintyInstructionPolicy;prohibitedBehaviors:string[];outputSchemaVersion:string;evaluationPolicyVersion:string;minimumContextVersion:string;tags:string[];createdAt:string;updatedAt:string;changelog:PromptChangelogEntry[];metadata:PromptMetadata;}
export interface PromptRegistry{version:string;definitions:readonly PromptDefinition[];defaults:Partial<Record<AgentType,string>>;}
export interface PromptSelectionPolicy{allowFallback:boolean;allowDeprecatedExplicit:boolean;allowExperimental:boolean;supportedContextVersions:string[];supportedOutputSchemaVersions:string[];supportedEvaluationPolicyVersions:string[];}
export type PromptErrorCode="missing-prompt"|"duplicate-prompt-id"|"duplicate-version"|"unsupported-agent"|"unsupported-task"|"deprecated-prompt"|"archived-prompt"|"experimental-blocked"|"incompatible-context-version"|"incompatible-output-schema"|"incompatible-evaluation-policy"|"unknown-placeholder"|"missing-placeholder"|"empty-template"|"missing-citation-policy"|"missing-uncertainty-policy"|"missing-prohibited-behavior"|"provider-specific-syntax"|"raw-source-instruction"|"prompt-over-budget"|"empty-context"|"rendering-failure"|"content-hash-mismatch"|"fixture-missing"|"baseline-missing";
export interface PromptIssue{code:PromptErrorCode;message:string;field?:string;recoverable:boolean;}
export interface PromptSelectionResult{definition?:PromptDefinition;errors:PromptIssue[];warnings:PromptIssue[];auditEvents:PromptAuditEvent[];selectionReason?:"explicit-version"|"active-match"|"agent-default"|"explicit-fallback";}
export interface PromptValidationResult{valid:boolean;errors:PromptIssue[];warnings:PromptIssue[];validatedAt:string;definitionId:string;definitionVersion:string;auditEvents:PromptAuditEvent[];}
export interface PromptBuildPolicy{maximumPromptTokens:number;reservedOutputTokens:number;includeSchema:boolean;includeExamples:boolean;includeContextMetadata:boolean;includeDiagnostics:boolean;includePromptChangelog:boolean;strictOutputOnly:boolean;allowExperimentalPrompts:boolean;fallbackBehavior:"fail"|"explicit-only";deterministicFormatting:boolean;policyVersion:string;}
export interface PromptMessage{role:PromptRole;content:string;name?:string;metadata:Record<string,string|number|boolean|undefined>;}
export interface PromptContextReference{section:ContextSection;itemIds:string[];factIds:string[];evidenceIds:string[];conflictIds:string[];lineageIds:string[];}
export interface PromptTokenEstimate{systemTokens:number;taskTokens:number;contextTokens:number;schemaTokens:number;safetyTokens:number;reservedOutputTokens:number;totalEstimatedTokens:number;withinLimit:boolean;estimationMethod:string;margin:number;}
export interface PromptBuildMetadata{builderVersion:string;registryVersion:string;promptDefinitionVersion:string;contextVersion:string;outputSchemaVersion:string;builtAt:string;requestId:string;traceId:string;deterministic:boolean;templateVariables:Record<string,string>;includedContextSections:ContextSection[];excludedContextSections:ContextSection[];contentHash:string;warnings:string[];}
export interface PromptPackage{promptPackageId:string;promptId:string;promptVersion:string;agentType:AgentType;taskType:AgentTaskType;requestId:string;traceId:string;contextId:string;contextVersion:string;outputSchemaVersion:string;evaluationPolicyVersion:string;messages:PromptMessage[];contextReferences:PromptContextReference[];schemaContract:string;citationPolicy:CitationPolicy;uncertaintyPolicy:UncertaintyInstructionPolicy;prohibitedBehaviors:string[];buildMetadata:PromptBuildMetadata;estimatedTokens:PromptTokenEstimate;warnings:PromptIssue[];omissions:string[];}
export interface PromptBuildResult{package?:PromptPackage;errors:PromptIssue[];warnings:PromptIssue[];tokenEstimate:PromptTokenEstimate;auditEvents:PromptAuditEvent[];}
export interface PromptDiffResult{baselinePromptId:string;baselineVersion:string;candidatePromptId:string;candidateVersion:string;changedSections:string[];addedInstructions:string[];removedInstructions:string[];changedPolicies:string[];schemaVersionChanged:boolean;evaluationPolicyChanged:boolean;riskLevel:"low"|"medium"|"high"|"critical";explanation:string;}
export type PromptAuditEventType="prompt-selected"|"prompt-selection-failed"|"prompt-validation-passed"|"prompt-validation-failed"|"prompt-build-started"|"prompt-build-completed"|"prompt-build-failed"|"prompt-over-budget"|"prompt-fixture-started"|"prompt-fixture-completed"|"prompt-regression-detected";
export interface PromptAuditEvent{id:string;traceId:string;requestId:string;contextId:string;promptId:string;promptVersion:string;promptPackageId?:string;eventType:PromptAuditEventType;timestamp:string;details:Record<string,string|number|boolean>;}
export interface PromptFixture{fixtureId:string;name:string;accountId:string;agentType:AgentType|string;taskType:AgentTaskType|string;contextFixtureId:string;promptId:string;promptVersion:string;reasonerFixtureId:string;expectedBuildOutcome:"pass"|"fail";expectedEvaluationOutcome?:EvaluationVerdict;tags:string[];version:string;buildPolicy?:Partial<PromptBuildPolicy>;contextVersionOverride?:string;outputSchemaVersionOverride?:string;}
export interface PromptRegressionResult{fixtureId:string;promptVersion:string;buildPassed:boolean;reasoningPassed:boolean;evaluationPassed:boolean;score:number;verdict:EvaluationVerdict|"not-run";eligibility:boolean;expectedOutcomeMatched:boolean;findings:string[];regressed:boolean;explanation:string;}
export interface PromptFixtureRunResult{fixture:PromptFixture;selection:PromptSelectionResult;build:PromptBuildResult;reasoning?:AgentReasoningResult;evaluation?:AgentEvaluationResult;regression:PromptRegressionResult;auditEvents:PromptAuditEvent[];}
export interface RunPromptFixtureDependencies{registry:PromptRegistry;reasoner:AgentReasoner;evaluatorPolicy:EvaluationPolicy;context:AgentContextPackage;request:AgentReasoningRequest;now:string;}
