import { buildAccountDigitalTwin,buildAccountSummary,daysUntilRenewal,filterTimeline,toDecisionAccountContext } from "@/account-digital-twin";import { normalizeAccount,normalizeActivity,normalizeOpportunity,normalizeProductUsage,normalizeStakeholder } from "@/account-digital-twin/normalization/normalize-sources";import { relationshipScore,roleHealth } from "@/account-digital-twin/relationships/derive-relationships";import { detectOpportunityStagnation } from "@/account-digital-twin/selectors/account-intelligence";import { buildTimeline } from "@/account-digital-twin/timeline/build-timeline";import { baseAccountDigitalTwins } from "@/data/synthetic/account-digital-twins";import { syntheticSourceBundles } from "@/data/synthetic/account-source-records";import { accountDigitalTwins } from "@/data/synthetic/final-account-digital-twins";import { decisionControlResult } from "@/features/morning-briefing/data";import { describe,expect,it } from "vitest";
const source=syntheticSourceBundles[0],twin=accountDigitalTwins[0];
describe("Account Digital Twin",()=>{
it("normalizes account source",()=>expect(normalizeAccount(source.account).identity.name).toBe("Coinbase"));
it("normalizes stakeholders",()=>expect(normalizeStakeholder(source.stakeholders[0]).roleInBuyingProcess).toBe("champion"));
it("normalizes opportunities",()=>expect(normalizeOpportunity(source.opportunities[0],75).qualificationCompleteness).toBe(75));
it("normalizes activities",()=>expect(normalizeActivity(source.activities[0]).type).toBe("call"));
it("normalizes usage",()=>expect(normalizeProductUsage(source.usage[0]).adoptionRate).toBe(.68));
it("calculates renewal days",()=>expect(daysUntilRenewal("2026-08-11T00:00:00.000Z","2026-08-01T00:00:00.000Z")).toBe(10));
it("calculates relationship strength",()=>expect(relationshipScore(twin.stakeholders)).toBeGreaterThan(0));
it("derives engagement trend",()=>expect(normalizeStakeholder(source.stakeholders[0]).engagementTrend).toBe("declining"));
it("derives champion health",()=>expect(roleHealth(twin.stakeholderMap.champion)).not.toBe("unknown"));
it("derives sponsor health",()=>expect(roleHealth(twin.stakeholderMap.executiveSponsor)).not.toBe("unknown"));
it("detects opportunity stagnation",()=>expect(detectOpportunityStagnation(accountDigitalTwins[4].opportunities,twin.asOf).length).toBeGreaterThan(0));
it("derives product trend",()=>expect(accountDigitalTwins[1].productUsage[0].usageTrend).toBe("improving"));
it("calculates MEDDPICC completeness",()=>expect(twin.meddpicc.completenessScore).toBeGreaterThan(0));
it("finds MEDDPICC critical gaps",()=>expect(accountDigitalTwins[4].meddpicc.criticalGaps.length).toBeGreaterThan(0));
it("calculates health deterministically",()=>expect(baseAccountDigitalTwins[0].health.overallScore).toBe(baseAccountDigitalTwins[0].health.overallScore));
it("explains health drivers",()=>expect(twin.health.drivers).toHaveLength(4));
it("calculates data quality",()=>expect(twin.dataQuality.overallScore).toBeGreaterThan(0));
it("orders timeline deterministically",()=>{const events=buildTimeline(twin.recentActivities,twin.activeDecisions);expect(events[0].occurredAt>=events.at(-1)!.occurredAt).toBe(true)});
it("filters timeline",()=>expect(filterTimeline(twin.fullTimeline,"decisions").every((e)=>e.category==="decisions")).toBe(true));
it("compares snapshots",()=>expect(twin.snapshotSummary.changes.length).toBeGreaterThan(0));
it("derives known risks",()=>expect(twin.knownRisks).toContain("Security review is stalled"));
it("derives expansion signals",()=>expect(accountDigitalTwins[1].expansionSignals.length).toBeGreaterThan(0));
it("derives unresolved questions",()=>expect(accountDigitalTwins[4].unresolvedQuestions.some((q)=>q.includes("economic buyer"))).toBe(true));
it("retains provenance",()=>expect(twin.provenance[0].ruleVersion).toBe("account-health-v1"));
it("builds a complete Twin",()=>expect(twin.accountId).toBe("acct-coinbase"));
it("builds a partial Twin",()=>{const partial=buildAccountDigitalTwin({account:source.account,now:twin.asOf});expect(partial.stakeholders).toEqual([]);expect(partial.dataQuality.missingFields.length).toBeGreaterThan(0)});
it("rejects invalid source input",()=>expect(()=>normalizeAccount({...source.account,Id:""})).toThrow());
it("adapts Twin to Decision context",()=>{const context=toDecisionAccountContext(twin);expect(context.annualContractValue).toBe(twin.commercialProfile.annualContractValue);expect(context.dataQualityScore).toBeDefined()});
it("preserves Decision Control behavior",()=>expect(decisionControlResult.acceptedDecisions).toHaveLength(8));
it("builds all five account Twins",()=>expect(accountDigitalTwins).toHaveLength(5));
it("includes governed account decisions",()=>expect(twin.activeDecisions.some((d)=>d.accountId===twin.accountId)).toBe(true));
it("creates all stakeholder map roles",()=>expect(twin.stakeholderMap.champion?.name).toBeDefined());
it("always creates eight MEDDPICC fields",()=>expect(twin.meddpicc.fields).toHaveLength(8));
it("builds a deterministic summary",()=>expect(buildAccountSummary(twin)).toContain("Top risk:"));
it("reports simulated source coverage",()=>expect(twin.sourceCoverage.every((s)=>!s.connected)).toBe(true));
it("keeps timeline tie ordering stable",()=>{const a=filterTimeline(twin.fullTimeline,"all").map((e)=>e.id);const b=filterTimeline(twin.fullTimeline,"all").map((e)=>e.id);expect(a).toEqual(b)});
it("health has interpretable component scores",()=>expect(twin.health.relationshipScore+twin.health.productUsageScore).toBeGreaterThan(0));
});
