import { describe, expect, it } from "vitest";
import { compareAIExecutionTraces, containsAIConsoleSecret, exportAIExecutionTrace, exportPromptPackage, filterAIExecutionTraces, getTraceStages, InMemoryAIExecutionTraceRepository, isAIConsoleEnabled, redactAIConsoleValue, replayAIExecutionTrace, screenRedactionPolicy, searchAIExecutionTrace } from "@/ai-developer-console";
import { createCoinbaseAIConsoleTraces } from "@/ai-developer-console/fixtures/coinbase-traces";

describe("AI Developer Console read model",()=>{
 const traces=createCoinbaseAIConsoleTraces();
 it("creates stable, complete stage ordering with explicit unavailable stages",()=>{expect(traces).toHaveLength(3);expect(getTraceStages(traces[0]!).map(([key])=>key)).toEqual(["source","reconciliation","digital-twin","context","prompt","provider","parsing","evaluation","eligibility","governance","economics","artifact","workspace"]);expect(traces[0]!.providerStage.status).toBe("unavailable");expect(traces[2]!.providerStage.status).toBe("completed");});
 it("inspects context and prompt without reconstructing them",()=>{const trace=traces[0]!;expect(trace.contextStage.output?.context?.accountId).toBe("acct-coinbase");expect(trace.promptStage.output?.promptPackage?.messages.map(item=>item.role)).toEqual(["system","developer","user"]);expect(trace.promptStage.contentHash).toMatch(/^fnv1a32-/);});
 it("redacts credentials, authorization, email, phone, and sensitive notes recursively",()=>{const value=redactAIConsoleValue({Authorization:"Bearer secret-token",apiKey:"sk-supersecret",email:"person@example.com",phone:"+1 (415) 555-1234",sensitiveNote:"do not expose"},screenRedactionPolicy);expect(JSON.stringify(value)).not.toContain("secret-token");expect(JSON.stringify(value)).not.toContain("sk-supersecret");expect(JSON.stringify(value)).toContain("[REDACTED EMAIL]");expect(JSON.stringify(value)).toContain("[REDACTED PHONE]");expect(containsAIConsoleSecret(value)).toBe(false);});
 it("filters and searches only safe traces",()=>{expect(filterAIExecutionTraces(traces,{executionMode:"replay"})).toHaveLength(1);expect(filterAIExecutionTraces(traces,{accountId:"acct-coinbase"})).toHaveLength(3);expect(searchAIExecutionTrace(traces[0]!,"evidence").length).toBeGreaterThan(0);});
 it("compares prompts and recommendations deterministically",()=>{const result=compareAIExecutionTraces(traces[0]!,traces[1]!);expect(result.compatible).toBe(true);expect(result.prompt.changed).toBe(false);expect(result.recommendation.classification).toBe("unchanged");});
 it("exports redacted trace and prompt with hashes",()=>{const traceExport=exportAIExecutionTrace(traces[2]!),prompt=traces[2]!.promptStage.output!.promptPackage!,promptJson=exportPromptPackage(prompt,"json"),promptMarkdown=exportPromptPackage(prompt,"markdown");expect(traceExport.contentHash).toMatch(/^fnv1a32-/);expect(traceExport.content).toContain("developmentOnly");expect(containsAIConsoleSecret(traceExport.content)).toBe(false);expect(promptJson.mimeType).toBe("application/json");expect(promptMarkdown.content).toContain("Development-only redacted prompt export");});
 it("replays approved artifact without incremental provider cost",()=>{const result=replayAIExecutionTrace(traces[1]!,"2026-08-02T16:00:00.000Z");expect(result.success).toBe(true);expect(result.incrementalApiCostUsd).toBe(0);});
 it("persists immutable safe snapshots by reference",async()=>{const repository=new InMemoryAIExecutionTraceRepository();await repository.save(traces[2]!);const stored=await repository.load(traces[2]!.traceId);expect(stored?.artifactStage.output).toBeUndefined();expect(stored?.artifactStage.inputReferences).toContain(traces[2]!.artifactStage.output?.artifact.artifactId);expect(containsAIConsoleSecret(stored)).toBe(false);});
 it("fails closed in production",()=>{expect(isAIConsoleEnabled("development")).toBe(true);expect(isAIConsoleEnabled("production")).toBe(false);});
});
