-- PostgreSQL reference migration for replacing the phase-1 repository adapter.
CREATE TYPE organization_status AS ENUM ('ACTIVE','INACTIVE'); CREATE TYPE user_status AS ENUM ('ACTIVE','INACTIVE'); CREATE TYPE revenue_role AS ENUM ('SDR','AE','RSM','PARTNER_SALES','VP_SALES','CRO');
CREATE TABLE organizations (id text PRIMARY KEY,name text NOT NULL,slug text NOT NULL UNIQUE,status organization_status NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE regions (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),name text NOT NULL,parent_region_id text REFERENCES regions(id));
CREATE TABLE teams (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),name text NOT NULL,manager_user_id text,parent_team_id text REFERENCES teams(id),type text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),email text NOT NULL,first_name text NOT NULL,last_name text NOT NULL,display_name text NOT NULL,role revenue_role NOT NULL,status user_status NOT NULL DEFAULT 'ACTIVE',manager_user_id text REFERENCES users(id),team_id text REFERENCES teams(id),region_id text REFERENCES regions(id),timezone text,avatar_url text,is_demo_user boolean NOT NULL DEFAULT false,is_admin boolean NOT NULL DEFAULT false,password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),last_login_at timestamptz,UNIQUE(organization_id,email));
ALTER TABLE teams ADD CONSTRAINT teams_manager_fk FOREIGN KEY(manager_user_id) REFERENCES users(id);
CREATE TABLE auth_sessions (id text PRIMARY KEY,token_hash text NOT NULL UNIQUE,user_id text NOT NULL REFERENCES users(id),organization_id text NOT NULL REFERENCES organizations(id),view_as_role revenue_role,created_at timestamptz NOT NULL,last_seen_at timestamptz NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE resource_assignments (organization_id text NOT NULL REFERENCES organizations(id),resource_type text NOT NULL,resource_id text NOT NULL,user_id text REFERENCES users(id),team_id text REFERENCES teams(id),partner_user_id text REFERENCES users(id),PRIMARY KEY(organization_id,resource_type,resource_id));
CREATE TABLE security_audit_events (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),actor_user_id text NOT NULL REFERENCES users(id),actor_role revenue_role NOT NULL,event text NOT NULL,resource_type text NOT NULL,resource_id text NOT NULL,timestamp timestamptz NOT NULL,payload jsonb,before_state jsonb,after_state jsonb);
CREATE INDEX users_manager_scope_idx ON users(organization_id,manager_user_id); CREATE INDEX assignments_scope_idx ON resource_assignments(organization_id,user_id,team_id,partner_user_id); CREATE INDEX sessions_expiry_idx ON auth_sessions(token_hash,expires_at); CREATE INDEX audit_resource_idx ON security_audit_events(organization_id,resource_type,resource_id,timestamp DESC);
-- Backfill existing account/opportunity organization_id and owner_user_id columns to org-cognivit-demo using the deterministic mappings in src/auth/seed.ts before making those columns NOT NULL.
