import type { FactType } from "@/domain/facts/types";
import type { EvidenceSource } from "@/domain/evidence/types";
export interface SourceAuthorityPolicy{factType:FactType;preferredSources:EvidenceSource[];fallbackSources:EvidenceSource[];minimumReliability:number;directObservationPreferred:boolean;humanOverrideAllowed:boolean;authorityWeights:Partial<Record<EvidenceSource,number>>;explanation:string;}
export interface FreshnessPolicy{factType:FactType;freshFor:number;agingAfter:number;staleAfter:number;expireAfter?:number;sourceOverrides?:Partial<Record<EvidenceSource,number>>;explanation:string;}
const day=86_400_000;
const authority=(factType:FactType,preferredSources:EvidenceSource[],fallbackSources:EvidenceSource[]=[]):SourceAuthorityPolicy=>({factType,preferredSources,fallbackSources,minimumReliability:.55,directObservationPreferred:true,humanOverrideAllowed:true,authorityWeights:Object.fromEntries([...preferredSources,...fallbackSources].map((s,i)=>[s,Math.max(.5,1-i*.12)])) as Partial<Record<EvidenceSource,number>>,explanation:`${preferredSources.join(", ")} are authoritative for ${factType}.`});
const defaultAuthority=authority("account-name",["salesforce"],["manual"]);
export const authorityPolicies:Partial<Record<FactType,SourceAuthorityPolicy>>={
 "account-name":defaultAuthority,"owner":authority("owner",["salesforce"],["manual"]),"annual-contract-value":authority("annual-contract-value",["contract-system"],["salesforce","manual"]),"total-contract-value":authority("total-contract-value",["contract-system"],["salesforce"]),"contract-start-date":authority("contract-start-date",["contract-system"]),"contract-end-date":authority("contract-end-date",["contract-system"]),"renewal-date":authority("renewal-date",["contract-system","manual"],["salesforce"]),"opportunity-stage":authority("opportunity-stage",["salesforce"],["manual"]),"opportunity-value":authority("opportunity-value",["salesforce"],["manual"]),"close-date":authority("close-date",["salesforce"]),"forecast-category":authority("forecast-category",["salesforce"]),"meeting-occurrence":authority("meeting-occurrence",["calendar","gong"],["email"]),"meeting-outcome":authority("meeting-outcome",["gong"],["manual","email"]),"stakeholder-title":authority("stakeholder-title",["salesforce","email"],["manual"]),"stakeholder-sentiment":authority("stakeholder-sentiment",["gong"],["manual","email"]),"product-adoption":authority("product-adoption",["product-usage"],["manual","salesforce"]),"product-usage-trend":authority("product-usage-trend",["product-usage"],["manual","salesforce"]),"support-severity":authority("support-severity",["support"],["manual","email"]),"strategic-initiative":authority("strategic-initiative",["manual","salesforce"],["external-news"]),"meddpicc-field":authority("meddpicc-field",["manual","gong"],["salesforce"])
};
const freshness=(factType:FactType,freshDays:number,staleDays:number,expireDays?:number):FreshnessPolicy=>({factType,freshFor:freshDays*day,agingAfter:freshDays*day,staleAfter:staleDays*day,expireAfter:expireDays?expireDays*day:undefined,explanation:`Fresh for ${freshDays} days; stale after ${staleDays} days.`});
export const freshnessPolicies:Partial<Record<FactType,FreshnessPolicy>>={"product-adoption":freshness("product-adoption",1,3,14),"product-usage-trend":freshness("product-usage-trend",1,3,14),"opportunity-stage":freshness("opportunity-stage",2,7,30),"opportunity-value":freshness("opportunity-value",2,7,30),"stakeholder-engagement":freshness("stakeholder-engagement",7,14,45),"stakeholder-sentiment":freshness("stakeholder-sentiment",14,30,90),"stakeholder-title":freshness("stakeholder-title",30,90,365),"meddpicc-field":freshness("meddpicc-field",14,30,90),"support-severity":freshness("support-severity",1,7,30),"external-news":freshness("strategic-initiative",7,14,30),"meeting-occurrence":freshness("meeting-occurrence",36500,36500),"annual-contract-value":freshness("annual-contract-value",365,730),"renewal-date":freshness("renewal-date",365,730)} as Partial<Record<FactType,FreshnessPolicy>>;
export const reconciliationPolicy={version:"reconciliation-v1",ruleVersion:"fact-rules-v1",sourceReliability:{salesforce:.92,gong:.86,email:.72,calendar:.94,"product-usage":.98,support:.95,"contract-system":.99,"external-news":.55,manual:.9,synthetic:.75} satisfies Record<EvidenceSource,number>,numericTolerance:{money:.03,percentage:.02},dateToleranceMs:day,stringNormalization:true,confidenceWeights:{authority:.22,reliability:.18,freshness:.16,directness:.12,corroboration:.12,consistency:.1,verification:.1},criticalConflictFactTypes:["annual-contract-value","renewal-date","opportunity-value"] as FactType[],humanOverrideDefaultDurationMs:90*day,incrementalDependencies:{"annual-contract-value":["commercial","renewal","health","data-quality"],"renewal-date":["commercial","renewal","health","timeline","data-quality"],"opportunity-value":["opportunities","commercial","health","data-quality"],"opportunity-stage":["opportunities","health"],"product-adoption":["product-usage","health","data-quality"],"product-usage-trend":["product-usage","health"],"stakeholder-title":["stakeholders","data-quality"],"stakeholder-sentiment":["stakeholders","health"],"stakeholder-engagement":["stakeholders","health","timeline"],"relationship-strength":["stakeholders","health"],champion:["stakeholders","meddpicc","health"],"executive-sponsor":["stakeholders","health"],"meeting-occurrence":["timeline","stakeholders","health"],"meeting-outcome":["timeline","stakeholders","health"],"support-severity":["renewal","health","timeline"],"security-review-status":["renewal","health","timeline"],"legal-review-status":["renewal","health","timeline"],"procurement-status":["renewal","health","timeline"],"strategic-initiative":["timeline"],"meddpicc-field":["meddpicc","health"]} as Partial<Record<FactType,string[]>>};
export function authorityPolicy(type:FactType){return authorityPolicies[type]??{...defaultAuthority,factType:type};}
export function freshnessPolicy(type:FactType){const policy=freshnessPolicies[type]??freshness(type,30,90,365);return type==="stakeholder-title"?{...policy,sourceOverrides:{...policy.sourceOverrides,email:120*day}}:policy;}
