"use client";
import { useMemo, useState } from "react";
import type { AIExecutionStageKey, AIExecutionTrace } from "@/domain/ai-developer-console/types";
import type { PromptPackage } from "@/domain/prompts/types";
import type { ContextPolicySimulationResult } from "@/domain/llm-context/explainability-types";
import { ContextQualityView } from "./context-quality/context-quality-view";
import { buildChronologicalTimeline, compareAIExecutionTraces, copyPromptText, exportAIExecutionTrace, exportPromptPackage, filterAIExecutionTraces, getTraceStages, replayAIExecutionTrace, searchAIExecutionTrace } from "@/ai-developer-console";

const label=(value:string)=>value.replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const download=(filename:string,mimeType:string,content:string)=>{const url=URL.createObjectURL(new Blob([content],{type:mimeType})),anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.click();URL.revokeObjectURL(url);};
const prettyJson=(value:unknown)=>JSON.stringify(value,null,2);

export function AIDeveloperConsole({initialTraces,policySimulation}:{initialTraces:AIExecutionTrace[];policySimulation?:ContextPolicySimulationResult}){
 const [selectedId,setSelectedId]=useState(initialTraces[0]?.traceId??"");const [stageKey,setStageKey]=useState<AIExecutionStageKey>("context");const [query,setQuery]=useState("");const [mode,setMode]=useState("all");const [compareId,setCompareId]=useState(initialTraces[1]?.traceId??"");const [notice,setNotice]=useState("Select a stage to inspect the retained, redacted pipeline snapshot.");
 const traces=useMemo(()=>filterAIExecutionTraces(initialTraces,{executionMode:mode==="all"?undefined:mode as AIExecutionTrace["executionMode"],query:query||undefined}),[initialTraces,mode,query]);const trace=initialTraces.find(item=>item.traceId===selectedId)??traces[0]??initialTraces[0];if(!trace)return <p>No traces are available.</p>;const stages=getTraceStages(trace),selected=stages.find(([key])=>key===stageKey)?.[1]??trace.contextStage,comparison=compareAIExecutionTraces(trace,initialTraces.find(item=>item.traceId===compareId)??trace),matches=searchAIExecutionTrace(trace,query),timeline=buildChronologicalTimeline(trace),prompt=trace.promptStage.output?.promptPackage;
 const copy=async()=>{if(!prompt)return setNotice("PromptPackage unavailable for this trace.");await navigator.clipboard.writeText(copyPromptText(prompt));setNotice("Redacted prompt copied.");};
 const replay=()=>{const result=replayAIExecutionTrace(trace,new Date().toISOString());setNotice(result.success?`Replay completed with $${result.incrementalApiCostUsd.toFixed(2)} incremental API cost.`:`Replay unavailable: ${result.errors.join(", ")}`);};
 return <article className="ai-console">
  <header className="accounts-header"><div><span className="eyebrow">DEVELOPMENT ONLY · REDACTED OBSERVER</span><h1>AI Developer Console</h1><p>Trace Coinbase renewal intelligence from evidence through governed decision.</p></div><span className={`trace-status status-${trace.status}`}>{label(trace.status)}</span></header>
  <div className="ai-console-toolbar" aria-label="Trace controls"><label>Execution mode<select value={mode} onChange={event=>setMode(event.target.value)}><option value="all">All modes</option><option value="deterministic">Deterministic</option><option value="replay">Replay</option><option value="real-provider-development">Real provider · approved recording</option></select></label><label>Search safe trace<input aria-label="Search safe trace" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Fact, evidence, claim, warning…"/></label><button onClick={copy}>Copy prompt</button><button onClick={()=>{const value=exportAIExecutionTrace(trace);download(value.filename,value.mimeType,value.content);setNotice("Redacted trace exported.");}}>Export trace</button><button onClick={replay}>Replay artifact</button></div>
  <p className="console-notice" role="status">{notice}</p>
  <div className="ai-console-layout">
   <aside className="console-rail"><h2>Traces</h2>{traces.map(item=><button className={item.traceId===trace.traceId?"selected":""} key={`${item.traceId}-${item.executionMode}`} onClick={()=>setSelectedId(item.traceId)}><strong>{label(item.executionMode)}</strong><small>{item.metadata.provider} · {item.metadata.model}</small><small>{item.metadata.evaluationVerdict??"No verdict"}</small></button>)}{matches.length>0&&<section><h3>Search matches</h3>{matches.slice(0,8).map((match,index)=><button key={`${match.path}-${index}`} onClick={()=>setStageKey(match.stage)}><small>{label(match.stage)} · {match.path}</small>{match.excerpt}</button>)}</section>}</aside>
   <main className="console-main"><section className="pipeline-timeline" aria-label="Pipeline timeline">{stages.map(([key,value])=><button key={key} className={`${stageKey===key?"selected":""} stage-${value.status}`} onClick={()=>setStageKey(key)} aria-label={`Inspect ${value.stageName}`}><span>{value.status==="completed"?"✓":value.status==="unavailable"?"—":value.status==="failed"?"!":"•"}</span><strong>{value.stageName}</strong><small>{value.durationMs??value.diagnostics.latencyMs??"—"}{typeof(value.durationMs??value.diagnostics.latencyMs)==="number"?" ms":""}</small></button>)}</section>
    <StageInspector trace={trace} stageKey={stageKey} stage={selected} onExportPrompt={(format)=>{if(!prompt)return;const value=exportPromptPackage(prompt,format);download(value.filename,value.mimeType,value.content);setNotice(`Redacted prompt ${format.toUpperCase()} exported.`);}} />
    {stageKey==="context"&&trace.contextStage.output&&<section className="console-card"><span className="eyebrow">CONTEXT QUALITY · POLICY TUNING</span><h2>Why context was selected</h2><ContextQualityView build={trace.contextStage.output.build}/>{policySimulation&&<PolicyComparisonView simulation={policySimulation}/>}</section>}
    <section className="console-card"><header><div><span className="eyebrow">DIFF MODE</span><h2>Prompt & recommendation comparison</h2></div><select aria-label="Comparison trace" value={compareId} onChange={event=>setCompareId(event.target.value)}>{initialTraces.map(item=><option key={`${item.traceId}-${item.executionMode}`} value={item.traceId}>{label(item.executionMode)} · {item.metadata.promptVersion}</option>)}</select></header>{comparison.compatible?<div className="console-summary-grid"><Metric label="Prompt changed" value={comparison.prompt.changed?"Yes":"No"}/><Metric label="Token delta" value={`${comparison.prompt.tokenDelta}`}/><Metric label="Recommendation" value={label(comparison.recommendation.classification)}/><Metric label="Quality delta" value={`${comparison.economics.qualityDelta??"Unavailable"}`}/><div className="console-wide"><h3>Structured changes</h3><ul>{[...comparison.prompt.changedSections.map(item=>`${label(item)} message changed`),...comparison.recommendation.claimChanges,...comparison.recommendation.evidenceChanges].map(item=><li key={item}>{item}</li>)}</ul></div></div>:<p className="error-text">{comparison.errors.join(" ")}</p>}</section>
    <section className="console-card"><span className="eyebrow">EXECUTION EVENTS</span><h2>Chronological timeline</h2><ol className="audit-timeline">{timeline.map(item=><li key={item.id}><time>{new Date(item.timestamp).toLocaleTimeString()}</time><strong>{item.label}</strong><span>{label(item.status)}</span></li>)}</ol></section>
   </main>
   <aside className="console-summary"><section className="console-card"><span className="eyebrow">RUN SUMMARY</span><h2>{trace.accountName}</h2><dl><dt>Trace</dt><dd>{trace.traceId}</dd><dt>Agent</dt><dd>{label(trace.agentType)}</dd><dt>Task</dt><dd>{label(trace.taskType)}</dd><dt>Prompt</dt><dd>{trace.metadata.promptVersion??"Unavailable"}</dd><dt>Provider</dt><dd>{trace.metadata.provider??"None"}</dd><dt>Model</dt><dd>{trace.metadata.model??"None"}</dd></dl></section><QualitySummary trace={trace}/><section className="console-card"><h2>Warnings & errors</h2><strong>{trace.warnings.length} warnings · {trace.errors.length} errors</strong>{trace.warnings.slice(0,5).map(item=><p key={item} className="warning-text">{item}</p>)}</section></aside>
  </div>
 </article>;
}

function Metric({label,value}:{label:string;value:string}){return <div className="console-metric"><small>{label}</small><strong>{value}</strong></div>}
function QualitySummary({trace}:{trace:AIExecutionTrace}){const evaluation=trace.evaluationStage.output?.evaluation,analytics=trace.economicsStage.output?.analytics;return <section className="console-card"><span className="eyebrow">COST · LATENCY · QUALITY</span><div className="console-summary-grid"><Metric label="Evaluation" value={evaluation?`${evaluation.overallScore}/100`:"Unavailable"}/><Metric label="Grounding" value={evaluation?`${evaluation.groundingSummary.coverageScore}%`:"Unavailable"}/><Metric label="Eligibility" value={trace.metadata.eligible===undefined?"Unavailable":trace.metadata.eligible?"Eligible":"Blocked"}/><Metric label="Tokens" value={`${analytics?.usage.totalTokens??trace.promptStage.output?.promptPackage?.estimatedTokens.totalEstimatedTokens??"Unavailable"}`}/><Metric label="Incremental cost" value={trace.executionMode==="deterministic"?"$0 · deterministic":trace.executionMode==="replay"?"$0 · replay":analytics?`$${analytics.cost.incrementalCostUsd.toFixed(4)}`:"Unavailable"}/><Metric label="Latency" value={analytics?`${analytics.latency.totalMs} ms`:"Unavailable"}/></div>{analytics?.cost.historicalOriginalCostUsd!==undefined&&<p>Historical original cost: ${analytics.cost.historicalOriginalCostUsd.toFixed(4)}. Current replay cost is $0.</p>}</section>}
function StageInspector({trace,stageKey,stage,onExportPrompt}:{trace:AIExecutionTrace;stageKey:AIExecutionStageKey;stage:{stageName:string;status:string;warnings:string[];errors:string[];versionMetadata:Record<string,string>;diagnostics:Record<string,string|number|boolean>;output?:unknown};onExportPrompt:(format:"json"|"markdown")=>void}){const prompt=trace.promptStage.output?.promptPackage,evaluation=trace.evaluationStage.output?.evaluation,governance=trace.governanceStage.output?.result;return <section className="console-card stage-inspector"><header><div><span className="eyebrow">{label(stageKey)} INSPECTOR</span><h2>{stage.stageName}</h2></div><span className={`trace-status stage-${stage.status}`}>{label(stage.status)}</span></header>{stage.status==="unavailable"?<div className="empty-state"><strong>Stage unavailable</strong><p>{String(stage.diagnostics.unavailableReason??"The source run did not produce or retain this stage.")}</p></div>:<>{stageKey==="context"&&trace.contextStage.output&&<ContextView trace={trace}/>} {stageKey==="prompt"&&prompt&&<PromptView prompt={prompt} onExport={onExportPrompt}/>} {stageKey==="provider"&&<ProviderView trace={trace}/>} {stageKey==="parsing"&&<SplitView leftTitle="Raw output" left={trace.parsingStage.output?.rawOutput} rightTitle="Parsed DecisionCandidate" right={trace.parsingStage.output?.candidate}/>} {stageKey==="evaluation"&&evaluation&&<EvaluationView trace={trace}/>} {stageKey==="governance"&&governance&&<SplitView leftTitle="DecisionCandidate" left={trace.governanceStage.output?.candidate} rightTitle="GovernedDecision" right={governance.acceptedDecisions[0]??governance.rejectedCandidates}/>} {!["context","prompt","provider","parsing","evaluation","governance"].includes(stageKey)&&<Code value={stage.output}/>}</>}<details><summary>Versions and diagnostics</summary><Code value={{versions:stage.versionMetadata,diagnostics:stage.diagnostics,warnings:stage.warnings,errors:stage.errors}}/></details></section>}
function ContextView({trace}:{trace:AIExecutionTrace}){const value=trace.contextStage.output!,context=value.context!;return <><div className="console-summary-grid"><Metric label="Context ID" value={context.contextId}/><Metric label="Version" value={context.contextVersion}/><Metric label="Selected claims" value={`${context.claims.length}`}/><Metric label="Evidence" value={`${context.supportingEvidence.length}`}/><Metric label="Omissions" value={`${context.omissions.length}`}/><Metric label="Confidence" value={`${context.dataConfidence.overall}%`}/></div><details open><summary>Account summary and selected facts</summary><p>{context.accountSummary}</p><Code value={context.claims}/></details><details><summary>Evidence, provenance, conflicts and caveats</summary><Code value={{supportingEvidence:context.supportingEvidence,provenanceIndex:context.provenanceIndex,conflictsAndCaveats:context.conflictsAndCaveats,sourceCoverage:context.sourceCoverage}}/></details><details><summary>Omitted items and reasons</summary><Code value={value.build.excludedItems}/></details></>}
function PromptView({prompt,onExport}:{prompt:PromptPackage;onExport:(format:"json"|"markdown")=>void}){const [view,setView]=useState<"rendered"|"plain"|"structured">("rendered");return <><div className="console-summary-grid"><Metric label="Prompt" value={`${prompt.promptId} v${prompt.promptVersion}`}/><Metric label="Schema" value={prompt.outputSchemaVersion}/><Metric label="Estimated tokens" value={`${prompt.estimatedTokens.totalEstimatedTokens}`}/><Metric label="Content hash" value={prompt.buildMetadata.contentHash}/></div><div className="inline-actions"><button onClick={()=>setView("rendered")}>Rendered</button><button onClick={()=>setView("plain")}>Plain text</button><button onClick={()=>setView("structured")}>Structured</button><button onClick={()=>onExport("markdown")}>Download Markdown</button><button onClick={()=>onExport("json")}>Download JSON</button></div>{view==="rendered"?prompt.messages.map((message,index)=><details open={index===0} key={`${message.role}-${index}`}><summary>{message.role.toUpperCase()}</summary><Code value={message.content}/></details>):view==="plain"?<Code value={prompt.messages.map(item=>`[${item.role.toUpperCase()}]\n${item.content}`).join("\n\n")}/>:<Code value={prompt}/>}<details><summary>Citation, uncertainty and prohibited behavior policies</summary><Code value={{citationPolicy:prompt.citationPolicy,uncertaintyPolicy:prompt.uncertaintyPolicy,prohibitedBehaviors:prompt.prohibitedBehaviors,schemaContract:prompt.schemaContract}}/></details></>}
function ProviderView({trace}:{trace:AIExecutionTrace}){const value=trace.providerStage.output;return <>{value?.request&&<><div className="redacted-banner">REDACTED · Provider-neutral request</div><Code value={value.request}/></>}{value?.response&&<><h3>Raw output → normalized response → parser input</h3><SplitView leftTitle="Raw provider output" left={value.rawOutputAvailable?value.response.rawOutput:"Unavailable by recording policy"} rightTitle="Normalized LLMResponse" right={value.response}/></>}{!value?.translatedRequest&&<p>Provider-translated SDK request unavailable by policy. No provider SDK object is exposed.</p>}</>}
function EvaluationView({trace}:{trace:AIExecutionTrace}){const value=trace.evaluationStage.output!.evaluation;return <><div className="console-summary-grid"><Metric label="Score" value={`${value.overallScore}/100`}/><Metric label="Verdict" value={label(value.verdict)}/><Metric label="Risk" value={label(value.riskLevel)}/><Metric label="Grounding" value={`${value.groundingSummary.coverageScore}%`}/><Metric label="Traceability" value={`${value.traceabilitySummary.coverageScore}%`}/><Metric label="Blocking findings" value={`${value.diagnostics.blockingFindingCount}`}/></div><div className="evaluation-bars">{value.categoryResults.map(item=><div key={item.category}><span>{label(item.category)}</span><progress max="100" value={item.score}/><strong>{item.score}</strong></div>)}</div><details open><summary>Findings and remediation</summary><Code value={value.findings}/></details><details><summary>Claim → fact → evidence traceability</summary><Code value={trace.parsingStage.output?.candidate?.claimReferences??value.traceabilitySummary}/></details></>}
function SplitView({leftTitle,left,rightTitle,right}:{leftTitle:string;left:unknown;rightTitle:string;right:unknown}){return <div className="console-split"><section><h3>{leftTitle}</h3><Code value={left}/></section><section><h3>{rightTitle}</h3><Code value={right}/></section></div>}
function Code({value}:{value:unknown}){return <pre tabIndex={0} className="console-code">{typeof value==="string"?value:prettyJson(value)}</pre>}
function PolicyComparisonView({simulation}:{simulation:ContextPolicySimulationResult}){return <section className="policy-comparison"><span className="eyebrow">CONTROLLED POLICY EXPERIMENT</span><h3>Baseline versus candidate policy</h3><div className="console-summary-grid"><Metric label="Selected added" value={`${simulation.selectedAdded.length}`}/><Metric label="Selected removed" value={`${simulation.selectedRemoved.length}`}/><Metric label="Token delta" value={`${simulation.tokenChange}`}/><Metric label="Mandatory coverage delta" value={`${simulation.mandatoryCoverageChange}%`}/><Metric label="Compression delta" value={`${simulation.compressionChange}`}/><Metric label="Quality" value={simulation.contextQualityChange}/></div><p>{simulation.recommendation}</p><details><summary>Selection and rank changes</summary><Code value={{selectedAdded:simulation.selectedAdded,selectedRemoved:simulation.selectedRemoved,rankChanges:simulation.rankChanges,warnings:simulation.warnings}}/></details><p><strong>Promotion:</strong> Manual only. Run deterministic and replay evaluation before adopting this experiment.</p></section>}
