import {fireEvent,render,screen} from "@testing-library/react";
import {describe,expect,it} from "vitest";
import {accountDigitalTwins} from "@/data/synthetic/final-account-digital-twins";
import {resolvedAccountContexts} from "@/data/synthetic/resolved-account-contexts";
import {agentTaskNow,createSyntheticAgentTask} from "@/data/synthetic/agent-tasks";
import {buildAgentContext} from "@/llm-context";
import {ContextQualityView} from "./context-quality-view";
const twin=accountDigitalTwins.find(item=>item.accountId==="acct-coinbase")!,build=buildAgentContext({agentType:"renewal-agent",task:createSyntheticAgentTask("acct-coinbase","renewal-agent"),accountTwin:twin,resolvedContext:resolvedAccountContexts["acct-coinbase"],governedDecisions:twin.activeDecisions,now:agentTaskNow});
describe("Context Quality view",()=>{it("renders funnel, ledger, score, stages, budget, compression and availability",()=>{render(<ContextQualityView build={build}/>);expect(screen.getByText("Selection ledger")).toBeInTheDocument();expect(screen.getByText("Token budget ledger")).toBeInTheDocument();expect(screen.getByText("Availability trace")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Selection disposition filter"),{target:{value:"excluded"}});const items=screen.getAllByRole("listitem");expect(items.length).toBeGreaterThan(0);fireEvent.click(items[0]!);expect(screen.getByText("Score breakdown")).toBeInTheDocument();expect(screen.getByText("Decision stages")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Availability concept"),{target:{value:"security review"}});expect(screen.getByText(/security review reached|security review produced|security review existed|security review was not available/i)).toBeInTheDocument();});it("supports historical build results without a ledger",()=>{render(<ContextQualityView build={{...build,selectionDecisions:undefined,contextQuality:undefined,tokenBudgetLedger:undefined}}/>);expect(screen.getByText("Selection ledger unavailable")).toBeInTheDocument();});});
