"use client";
import {useMemo,useState} from "react";import type {EvaluationScenario,EvaluationScenarioResult} from "@/domain/agent-evaluation/types";import type {AgentContextPackage} from "@/domain/llm-context/types";import {createEvaluationRunReport,defaultEvaluationPolicy,runEvaluationScenario} from "@/agent-evaluation";import {reasonerFixtures,reasoningFixtureIds} from "@/data/evaluation-fixtures/reasoner-fixtures";import {agentTaskNow} from "@/data/synthetic/agent-tasks";
const key=(accountId:string,agentType:string)=>`${accountId}|${agentType}`,pretty=(value:string)=>value.replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
export function ReasoningLab({contexts,scenarios}:{contexts:Record<string,AgentContextPackage>;scenarios:EvaluationScenario[]}){
 const[scenarioId,setScenarioId]=useState(scenarios[0]?.id??""),[fixtureId,setFixtureId]=useState(scenarios[0]?.reasonerFixtureId??"valid"),[runAllResults,setRunAllResults]=useState<EvaluationScenarioResult[]|null>(null),scenario=scenarios.find(item=>item.id===scenarioId)??scenarios[0],context=scenario?contexts[key(scenario.accountId,scenario.agentType)]:undefined,result=useMemo(()=>scenario&&context?runEvaluationScenario({scenario:{...scenario,reasonerFixtureId:fixtureId},context,reasoner:reasonerFixtures[fixtureId],policy:defaultEvaluationPolicy,now:agentTaskNow}):undefined,[context,fixtureId,scenario]),report=runAllResults?createEvaluationRunReport({results:runAllResults,startedAt:agentTaskNow,policyVersion:defaultEvaluationPolicy.version}):undefined;
 const runAll=()=>setRunAllResults(scenarios.map(item=>runEvaluationScenario({scenario:item,context:contexts[key(item.accountId,item.agentType)],reasoner:reasonerFixtures[item.reasonerFixtureId],policy:defaultEvaluationPolicy,now:agentTaskNow})));
 if(!scenario||!context)return <section className="twin-card inspector-error" role="alert"><h1>Reasoning Lab unavailable</h1><p>No context fixture is available.</p></section>;
 return <article className="context-inspector reasoning-lab">
  <header className="accounts-header"><div><span className="eyebrow">DEVELOPMENT TOOL · SIMULATED REASONERS ONLY</span><h1>Agent Reasoning Lab</h1><p>Exercise schema parsing, grounding, hallucination checks, eligibility, and deterministic regressions.</p></div><button className="primary-button" type="button" onClick={runAll}>Run all golden scenarios</button></header>
  <section className="twin-card inspector-controls" aria-label="Reasoning controls"><label>Scenario<select aria-label="Scenario" value={scenarioId} onChange={event=>{const next=scenarios.find(item=>item.id===event.target.value);setScenarioId(event.target.value);if(next)setFixtureId(next.reasonerFixtureId)}}>{scenarios.map(item=><option key={item.id} value={item.id}>{pretty(item.name)}</option>)}</select></label><label>Account<input aria-label="Account" readOnly value={context.accountName}/></label><label>Agent type<input aria-label="Agent type" readOnly value={pretty(context.agentType)}/></label><label>Reasoner fixture<select aria-label="Reasoner fixture" value={fixtureId} onChange={event=>setFixtureId(event.target.value)}>{reasoningFixtureIds.map(id=><option key={id} value={id}>{pretty(id)}</option>)}</select></label><label>Evaluation policy<input aria-label="Evaluation policy" readOnly value={defaultEvaluationPolicy.version}/></label></section>
  {result&&<><section className="reconciliation-metrics inspector-metrics" aria-label="Evaluation diagnostics"><span><strong>{result.evaluation?.overallScore??0}</strong> evaluation score</span><span><strong>{result.evaluation?.verdict??"unable-to-evaluate"}</strong> verdict</span><span><strong>{result.eligibility?.eligible?"Eligible":"Blocked"}</strong> governance</span><span><strong>{result.evaluation?.hallucinationFindings.length??0}</strong> hallucinations</span><span><strong>{result.evaluation?.traceabilitySummary.coverageScore??0}%</strong> traceability</span><span><strong>{result.reasoning.parseResult.success?"Passed":"Failed"}</strong> parse</span></section><div className="inspector-grid">
   <section className="twin-card twin-wide"><h2>AgentContextPackage summary</h2><p>{context.accountSummary}</p><p>{context.supportingEvidence.length} evidence references · {Object.keys(context.provenanceIndex).length} provenance entries · {context.conflictsAndCaveats.length} caveats</p></section>
   <section className="twin-card"><h2>Reasoning request</h2><pre>{JSON.stringify(result.reasoning.request,null,2)}</pre></section><section className="twin-card"><h2>Raw simulated output</h2><pre>{JSON.stringify(result.reasoning.response?.rawOutput??result.reasoning.errors,null,2)}</pre></section><section className="twin-card"><h2>Parsed DecisionCandidate</h2><pre>{JSON.stringify(result.reasoning.candidate??result.reasoning.parseResult.errors,null,2)}</pre></section>
   <section className="twin-card"><h2>Parse warnings</h2>{result.reasoning.parseResult.warnings.map(item=><p key={`${item.code}-${item.field}`}>{item.code}: {item.message}</p>)}{!result.reasoning.parseResult.warnings.length&&<p>No parse warnings.</p>}</section>
   <section className="twin-card twin-wide"><h2>Evaluation categories</h2><div className="evaluation-category-grid">{result.evaluation?.categoryResults.map(item=><article key={item.category}><strong>{pretty(item.category)}</strong><span>{item.score}/100</span><p>{item.explanation}</p></article>)??<p>Unable to evaluate malformed output.</p>}</div></section>
   <section className="twin-card"><h2>Grounding and hallucinations</h2>{result.evaluation?.findings.filter(item=>["claim-grounding","hallucination-resistance","financial-impact-grounding"].includes(item.category)).map(item=><p key={item.id}><strong>{item.severity}</strong> · {item.message}</p>)}{!result.evaluation?.hallucinationFindings.length&&<p>No observable hallucination detected.</p>}</section>
   <section className="twin-card"><h2>Traceability and caveats</h2><p>{result.evaluation?.traceabilitySummary.explanation??"Unavailable"}</p>{result.evaluation?.conflictAwarenessFindings.map(item=><p key={item.id}>{item.message}</p>)}{result.evaluation?.staleEvidenceFindings.map(item=><p key={item.id}>{item.message}</p>)}</section>
   <section className="twin-card"><h2>Scope and recommendation</h2>{[...(result.evaluation?.scopeFindings??[]),...(result.evaluation?.recommendationFindings??[])].map(item=><p key={item.id}>{item.code}: {item.message}</p>)}{!result.evaluation?.scopeFindings.length&&!result.evaluation?.recommendationFindings.length&&<p>Within agent scope and actionable.</p>}</section><section className="twin-card"><h2>Audit events</h2><ol>{[...result.reasoning.auditEvents,...(result.evaluation?.auditEvents??[])].map(item=><li key={item.id}>{item.eventType}</li>)}</ol></section>
  </div></>}
  {report&&<section className="twin-card twin-wide reasoning-report" aria-live="polite"><h2>Golden scenario run</h2><p>{report.scenarioCount} scenarios · {report.failedCount} failed · {report.unableToEvaluateCount} unable · {report.eligibilityRate}% eligible · average {report.averageScore}</p><p>{report.scenarioResults.filter(item=>item.passedExpectation).length}/{report.scenarioCount} matched their golden expectations.</p></section>}
 </article>;
}
