import type {AccountDigitalTwin,Stakeholder} from "@/domain/accounts/account-digital-twin";import type {ResolvedAccountContext} from "@/domain/reconciliation/types";import {resolvedValue} from "@/evidence-reconciliation";import {buildStakeholderMap} from "../relationships/derive-relationships";import {calculateMEDDPICC} from "../qualification/calculate-meddpicc";import {calculateAccountHealth} from "../health/calculate-health";
const stakeholderId=(path:string)=>path.split(".")[1];
export function applyResolvedAccountContext(twin:AccountDigitalTwin,context:ResolvedAccountContext):AccountDigitalTwin{
 const acv=resolvedValue<number>(context,"annual-contract-value"),renewalDate=resolvedValue<string>(context,"renewal-date"),allOpportunityValues=context.facts.filter(f=>f.factType==="opportunity-value"),opportunityValues=allOpportunityValues.filter(f=>f.resolutionMethod!=="unresolved"&&typeof f.value==="number"),openPipeline=opportunityValues.length?opportunityValues.reduce((sum,f)=>sum+Number(f.value),0):allOpportunityValues.length?0:twin.commercialProfile.openPipelineValue;
 const opportunities=twin.opportunities.map(opportunity=>{const value=resolvedValue<number>(context,"opportunity-value",`opportunities.${opportunity.id}.amount`),stage=resolvedValue<string>(context,"opportunity-stage",`opportunities.${opportunity.id}.stage`);return{...opportunity,amount:value??(allOpportunityValues.some(f=>f.fieldPath===`opportunities.${opportunity.id}.amount`)?0:opportunity.amount),stage:stage??opportunity.stage};});
 const productUsage=twin.productUsage.map(usage=>{const adoption=resolvedValue<number>(context,"product-adoption",`productUsage.${usage.productId}.adoptionRate`),trend=resolvedValue<string>(context,"product-usage-trend",`productUsage.${usage.productId}.usageTrend`);return{...usage,adoptionRate:adoption??usage.adoptionRate,usageTrend:trend==="improving"||trend==="stable"||trend==="declining"?trend:usage.usageTrend};});
 const stakeholders=twin.stakeholders.map(original=>{const id=original.id,title=resolvedValue<string>(context,"stakeholder-title",`stakeholders.${id}.title`),sentiment=resolvedValue<string>(context,"stakeholder-sentiment",`stakeholders.${id}.sentiment`),relationship=resolvedValue<string>(context,"relationship-strength",`stakeholders.${id}.relationshipStrength`),engagement=resolvedValue<string>(context,"stakeholder-engagement",`stakeholders.${id}.engagementTrend`),champion=resolvedValue<boolean>(context,"champion",`stakeholders.${id}.isChampion`);return{...original,title:title??original.title,sentiment:["positive","neutral","negative","unknown"].includes(sentiment??"")?sentiment as Stakeholder["sentiment"]:original.sentiment,relationshipStrength:["strong","healthy","weakening","at-risk","inactive","unknown"].includes(relationship??"")?relationship as Stakeholder["relationshipStrength"]:original.relationshipStrength,engagementTrend:["improving","stable","declining","unknown"].includes(engagement??"")?engagement as Stakeholder["engagementTrend"]:original.engagementTrend,isChampion:champion??original.isChampion,roleInBuyingProcess:champion===false&&original.roleInBuyingProcess==="champion"?"user":original.roleInBuyingProcess};});
 const championFacts=context.facts.filter(f=>f.factType==="champion"&&f.fieldPath.startsWith("stakeholders."));for(const fact of championFacts){const id=stakeholderId(fact.fieldPath),index=stakeholders.findIndex(item=>item.id===id);if(index>=0&&fact.value===true)stakeholders[index]={...stakeholders[index]!,isChampion:true,roleInBuyingProcess:"champion"};}
 const qualification=twin.meddpicc.fields.map(field=>{const value=resolvedValue<string>(context,"meddpicc-field",`meddpicc.${field.key}`);if(!value)return field;const stale=value.startsWith("stale:"),clean=value.replace(/^(confirmed|stale):/i,"");return{...field,status:stale?"stale" as const:"confirmed" as const,value:clean,confidence:stale?.45:.95,evidenceIds:[...new Set([...field.evidenceIds,...context.facts.filter(f=>f.fieldPath===`meddpicc.${field.key}`).map(f=>f.id)])],lastUpdatedAt:context.asOf,gaps:stale?[`Revalidate ${field.key}`]:[],recommendedNextStep:stale?`Revalidate ${field.key}`:`Maintain evidence for ${field.key}`};}),meddpicc=calculateMEDDPICC(qualification,context.asOf);
 const support=resolvedValue<string>(context,"support-severity"),security=resolvedValue<string>(context,"security-review-status"),legal=resolvedValue<string>(context,"legal-review-status"),procurement=resolvedValue<string>(context,"procurement-status"),stakeholderMap=buildStakeholderMap(stakeholders),renewal=twin.renewalProfile?{...twin.renewalProfile,annualContractValue:acv??twin.renewalProfile.annualContractValue,renewalDate:renewalDate??twin.renewalProfile.renewalDate,supportHealth:support==="resolved"||support==="low"?"healthy" as const:support==="critical"?"critical" as const:support?"at-risk" as const:twin.renewalProfile.supportHealth,securityReviewStatus:security??twin.renewalProfile.securityReviewStatus,legalReviewStatus:legal??twin.renewalProfile.legalReviewStatus,procurementStatus:procurement??twin.renewalProfile.procurementStatus}:null;
 const health=calculateAccountHealth({commercialScore:twin.commercialProfile.paymentStatus==="current"?85:55,stakeholders,usage:productUsage,supportScore:renewal?.supportHealth==="healthy"?85:renewal?.supportHealth==="watch"?60:45,renewal,opportunities,meddpicc,quality:context.dataQuality,previousScore:twin.health.overallScore,now:context.asOf});
 const provenance=context.facts.map(fact=>({fieldPath:fact.fieldPath,derivationType:"aggregated" as const,sourceIds:fact.lineage.sourceRecordIds,evidenceIds:fact.supportingFactIds,calculatedAt:context.asOf,ruleVersion:fact.lineage.ruleVersions.join(" + "),explanation:fact.explanation}));
 return{...twin,asOf:context.asOf,commercialProfile:{...twin.commercialProfile,annualContractValue:acv??twin.commercialProfile.annualContractValue,renewalDate:renewalDate??twin.commercialProfile.renewalDate,openPipelineValue:openPipeline},renewalProfile:renewal,opportunities,productUsage,stakeholders,stakeholderMap,meddpicc,health,dataQuality:context.dataQuality,sourceCoverage:context.sourceCoverage,provenance:[...twin.provenance,...provenance],reconciliation:context};
}
