import type { AgentTaskType, AgentType } from "@/domain/agents/types";
import type { ContextSection } from "./types";
import type { FreshnessStatus } from "@/domain/reconciliation/types";

export type ContextCandidateItemType="resolved-fact"|"stakeholder"|"opportunity"|"renewal-milestone"|"product-usage"|"meddpicc-field"|"timeline-event"|"recent-change"|"active-risk"|"expansion-signal"|"unresolved-question"|"governed-decision"|"supporting-evidence"|"conflict"|"caveat"|"source-coverage"|"data-quality";
export type ContextMandatoryStatus="required"|"conditionally-required"|"preferred"|"optional"|"prohibited";
export type ContextFinalDisposition="selected-full"|"selected-compressed"|"selected-as-caveat"|"excluded-low-relevance"|"excluded-agent-scope"|"excluded-task-scope"|"excluded-low-confidence"|"excluded-stale"|"excluded-unsupported"|"excluded-duplicate"|"excluded-section-limit"|"excluded-token-budget"|"excluded-redaction"|"excluded-conflict-policy"|"excluded-invalid"|"replaced-by-higher-ranked-item"|"unavailable-upstream";
export type ContextSelectionStage="candidate-generated"|"scope-evaluated"|"trust-evaluated"|"freshness-evaluated"|"mandatory-classified"|"relevance-scored"|"deduplicated"|"section-limited"|"token-budgeted"|"compressed"|"selected"|"excluded";
export interface ContextPolicyAdjustment{ruleId:string;value:number;explanation:string;}
export interface ContextRelevanceScore{agentRelevance:number;taskRelevance:number;businessImpact:number;urgency:number;recency:number;confidence:number;sourceAuthority:number;timeSensitivity:number;stakeholderInfluence:number;decisionPriority:number;conflictMateriality:number;methodologyRelevance:number;freshnessAdjustment:number;trustAdjustment:number;policyAdjustments:ContextPolicyAdjustment[];total:number;explanation:string;}
export interface ContextCandidate{candidateId:string;accountId:string;agentType:AgentType;taskType:AgentTaskType;section:ContextSection;itemType:ContextCandidateItemType;sourceItemId:string;fieldPath?:string;title:string;compactValue:string;fullValueReference:string;factIds:string[];evidenceIds:string[];conflictIds:string[];lineageIds:string[];sourceRecordIds:string[];businessImpactValue?:number;priority?:string;urgency?:string;confidence:number;freshnessStatus:FreshnessStatus;authorityScore:number;verificationStatus:"human-verified"|"resolved"|"inferred"|"disputed"|"unsupported";createdAt:string;observedAt?:string;estimatedTokens:number;duplicateKey?:string;metadata:Record<string,string|number|boolean>;}
export interface ContextSelectionStageDecision{stage:ContextSelectionStage;status:"passed"|"failed"|"applied"|"skipped";inputRank?:number;outputRank?:number;scoreBefore:number;scoreAfter:number;ruleIds:string[];explanation:string;timestamp:string;}
export interface ContextSelectionDecision{candidateId:string;selected:boolean;finalDisposition:ContextFinalDisposition;policyId:string;policyVersion:string;mandatoryStatus:ContextMandatoryStatus;matchedRules:string[];failedRules:string[];score:number;scoreBreakdown:ContextRelevanceScore;initialRank:number;finalRank?:number;section:ContextSection;sectionRank:number;threshold:number;estimatedTokens:number;tokensAllocated:number;compressionApplied:boolean;compressionRuleId?:string;duplicateOfCandidateId?:string;replacementCandidateId?:string;exclusionReason?:string;humanReadableExplanation:string;decisionStages:ContextSelectionStageDecision[];createdAt:string;diagnostics:Record<string,string|number|boolean>;}
export interface ContextCompressionDecision{candidateId:string;applied:boolean;ruleId:string;originalTokenEstimate:number;compressedTokenEstimate:number;preservedFields:string[];removedFields:string[];originalSummaryReference:string;compressedSummary:string;informationLossRisk:"none"|"low"|"medium"|"high";explanation:string;}
export interface ContextSectionTokenAllocation{section:ContextSection;requestedTokens:number;allocatedTokens:number;usedTokens:number;unusedTokens:number;selectedCount:number;excludedCount:number;compressedCount:number;}
export interface ContextTokenBudgetLedger{totalBudget:number;reservedPromptTokens:number;reservedOutputTokens:number;availableContextTokens:number;mandatoryTokensRequested:number;mandatoryTokensAllocated:number;preferredTokensRequested:number;preferredTokensAllocated:number;optionalTokensRequested:number;optionalTokensAllocated:number;sectionAllocations:ContextSectionTokenAllocation[];itemsRemoved:string[];itemsCompressed:string[];overBudget:boolean;hardLimitExceeded:boolean;explanation:string;}
export type ContextAvailabilityStatus="available-selected"|"available-compressed"|"available-excluded"|"unavailable-resolved-context"|"unavailable-digital-twin"|"candidate-generation-gap"|"blocked-by-trust"|"blocked-by-policy"|"blocked-by-budget";
export interface ContextAvailabilityTrace{requestedConcept:string;resolvedFactIds:string[];digitalTwinPaths:string[];candidateIds:string[];selectedCandidateIds:string[];status:ContextAvailabilityStatus;missingStage?:string;explanation:string;}
export interface ContextQualitySummary{candidateCount:number;selectedCount:number;compressedCount:number;excludedCount:number;mandatoryCandidateCount:number;mandatorySelectedCount:number;mandatoryCoverage:number;taskCriticalCandidateCount:number;taskCriticalSelectedCount:number;taskCriticalCoverage:number;highConfidenceCoverage:number;freshEvidenceCoverage:number;provenanceCoverage:number;caveatCoverage:number;duplicateRate:number;tokenUtilization:number;informationLossRisk:"none"|"low"|"medium"|"high";unresolvedSelectionWarnings:string[];overallStatus:"healthy"|"warning"|"critical"|"unable-to-assess";explanation:string;}
export interface ContextPolicyMetadata{policyId:string;policyVersion:string;registryVersion:string;selectionSchemaVersion:string;agentType:AgentType;taskType:AgentTaskType;}
export interface ContextPolicySimulationResult{simulationId:string;baselinePolicy:ContextPolicyMetadata;candidatePolicy:ContextPolicyMetadata;baselineBuild:import("./types").AgentContextBuildResult;candidateBuild:import("./types").AgentContextBuildResult;selectedAdded:string[];selectedRemoved:string[];rankChanges:{candidateId:string;baselineRank:number;candidateRank:number;delta:number}[];mandatoryCoverageChange:number;tokenChange:number;compressionChange:number;contextQualityChange:string;downstreamEvaluationComparison?:{baselineScore:number;candidateScore:number;scoreDelta:number;baselineEligible:boolean;candidateEligible:boolean};warnings:string[];recommendation:string;}
export interface ContextSelectionComparison{selectedAdded:string[];selectedRemoved:string[];rankChanges:{candidateId:string;baselineRank:number;candidateRank:number;delta:number}[];tokenChange:number;mandatoryCoverageChange:number;compressionChange:number;qualityStatusChanged:boolean;}
