import type { AIConsoleExport, AIExecutionTrace } from "@/domain/ai-developer-console/types";
import type { PromptPackage } from "@/domain/prompts/types";
import { contentHash } from "@/prompt-builder";
import { copyRedactionPolicy, exportRedactionPolicy } from "../config";
import { containsAIConsoleSecret, redactAIConsoleValue, stableStringify } from "../redaction/redact";

function bounded(content:string,limit:number){return content.length<=limit?{content,truncated:false}:{content:`${content.slice(0,limit)}\n\n[TRUNCATED BY AI CONSOLE EXPORT POLICY: ${content.length-limit} CHARACTERS OMITTED]`,truncated:true};}
function result(filename:string,mimeType:AIConsoleExport["mimeType"],content:string,truncated:boolean):AIConsoleExport{if(containsAIConsoleSecret(content))throw new Error("ai-console-export-redaction-failed");return{filename,mimeType,content,contentHash:contentHash(content),truncated,redactionPolicyVersion:exportRedactionPolicy.policyVersion};}
export function exportAIExecutionTrace(trace:AIExecutionTrace):AIConsoleExport{const safe=redactAIConsoleValue(trace,exportRedactionPolicy),limited=bounded(stableStringify({developmentOnly:true,exportVersion:"ai-console-export-v1",trace:safe}),exportRedactionPolicy.maximumExportedCharacters);return result(`${trace.traceId}.redacted.json`,"application/json",limited.content,limited.truncated);}
export function exportPromptPackage(prompt:PromptPackage,format:"json"|"markdown"):AIConsoleExport{const safe=redactAIConsoleValue(prompt,exportRedactionPolicy) as PromptPackage;if(format==="json"){const limited=bounded(stableStringify({developmentOnly:true,promptPackage:safe}),exportRedactionPolicy.maximumExportedCharacters);return result(`${prompt.promptId}-${prompt.promptVersion}.json`,"application/json",limited.content,limited.truncated);}const messages=safe.messages.map(message=>`## ${message.role.toUpperCase()}\n\n${message.content}`).join("\n\n"),content=`# ${safe.promptId} v${safe.promptVersion}\n\nDevelopment-only redacted prompt export.\n\nContent hash: ${safe.buildMetadata.contentHash}\n\n${messages}\n\n## Output schema\n\n\`\`\`json\n${safe.schemaContract}\n\`\`\``,limited=bounded(content,exportRedactionPolicy.maximumExportedCharacters);return result(`${prompt.promptId}-${prompt.promptVersion}.md`,"text/markdown",limited.content,limited.truncated);}
export function copyPromptText(prompt:PromptPackage):string{const safe=redactAIConsoleValue(prompt.messages,copyRedactionPolicy);return bounded(stableStringify(safe),copyRedactionPolicy.maximumDisplayedCharacters).content;}
