import Link from "next/link";
import { redirect } from "next/navigation";
import { requireIdentity } from "@/auth/guards.server";
import { query } from "@/db/client";
import { CadenceAgenda, PriorityCard, RevenueImpactBadge } from "@/components/revenue-operating";

export default async function RsmVpCadencePage() {
  const identity = await requireIdentity();
  if (identity.effectiveRole !== "RSM" && identity.effectiveRole !== "VP_SALES") redirect("/access-denied");
  const [health, risks, managers] = await Promise.all([
    query(`SELECT count(DISTINCT o.id)::int AS opportunities,COALESCE(sum(o.amount),0)::float8 AS pipeline,count(*) FILTER(WHERE f.aros_category IN('AT_RISK','HIGH_RISK'))::int AS risks FROM opportunities o LEFT JOIN forecast_assessments f ON(f.organization_id=o.organization_id AND f.opportunity_id=o.id) WHERE o.organization_id=$1`, [identity.organization.id]),
    query(`SELECT i.id,i.summary,i.priority_score,i.severity,a.name AS account_name,o.name AS opportunity_name,o.amount::float8 AS amount FROM manager_interventions i LEFT JOIN accounts a ON(a.organization_id=i.organization_id AND a.id=i.account_id) LEFT JOIN opportunities o ON(o.organization_id=i.organization_id AND o.id=i.opportunity_id) WHERE i.organization_id=$1 AND i.status NOT IN('RESOLVED','DISMISSED') ORDER BY i.priority_score DESC LIMIT 8`, [identity.organization.id]),
    query(`SELECT m.id,u.display_name,count(DISTINCT mi.id)::int AS interventions,count(DISTINCT c.id) FILTER(WHERE c.status IN('OPEN','IN_PROGRESS','BLOCKED','MISSED'))::int AS open_commitments FROM organization_memberships m JOIN users u ON(u.id=m.user_id) LEFT JOIN manager_interventions mi ON(mi.organization_id=m.organization_id AND mi.manager_membership_id=m.id) LEFT JOIN commitments c ON(c.organization_id=m.organization_id AND c.owner_membership_id=m.id) WHERE m.organization_id=$1 AND m.status='ACTIVE' GROUP BY m.id,u.display_name ORDER BY interventions DESC LIMIT 8`, [identity.organization.id]),
  ]);
  return <main className="rsm-today"><header className="rsm-hero"><div><span className="eyebrow">REGIONAL OPERATING CADENCE</span><h1>RSM–VP Operating Review</h1><p>Regional execution health, strategic risks, manager operating health, and resource decisions.</p></div><Link className="secondary-button" href="/forecast">Open forecast →</Link></header><CadenceAgenda title="Regional revenue health" purpose="Manage regional execution; this is not a forecast inspection meeting." sections={[{heading:"Regional revenue health",children:<div className="operating-list"><span><strong>{health.rows[0]?.opportunities ?? 0}</strong> active opportunities</span><span><strong>{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact"}).format(Number(health.rows[0]?.pipeline ?? 0))}</strong> pipeline</span><span><strong>{health.rows[0]?.risks ?? 0}</strong> forecast risks</span></div>},{heading:"Strategic accounts requiring attention",children:<div className="pattern-list">{risks.rows.map((item) => <PriorityCard key={item.id} item={{id:item.id,stage:"DECISION",title:item.opportunity_name ?? item.summary,summary:item.summary,accountName:item.account_name,revenueImpact:Number(item.amount ?? 0),status:item.severity}}><RevenueImpactBadge value={Number(item.amount ?? 0)} /></PriorityCard>)}</div>},{heading:"Manager operating health",children:<ul className="operating-list">{managers.rows.map((item) => <li key={item.id}><strong>{item.display_name}</strong> · {item.interventions} interventions · {item.open_commitments} open commitments</li>)}</ul>},{heading:"Resource needs and VP decisions",children:<p>Approve escalation, assign SE/Field CTO or executive sponsor support, request evidence, and create a dated leadership action.</p>}]}/></main>;
}
