import type {AgentTaskType,AgentType} from "@/domain/agents/types";
import type {PromptDefinition} from "@/domain/prompts/types";
import {allowedDecisionTypes,reasoningVersions,responsibleAgentNames} from "@/agent-reasoning/config";
import {contextVersions} from "@/llm-context";
import {agentTaskCompatibility,contextSectionPolicies,defaultCitationPolicy,defaultUncertaintyPolicy,prohibitedBehaviors} from "../config";

const system=`You are {{agentRole}}. Work only within the assigned task scope and supplied AgentContextPackage. Do not invent facts, treat omitted information as false, override governance, or claim external execution. Cite supplied IDs, distinguish resolved, observed, corroborated, inferred, disputed, stale, and unknown information, and return only the required {{outputSchema}} structured output.`;
const output=`Return only one DecisionCandidate matching {{outputSchema}}. Required structured contract:\n{{outputSchema}}`;
const evidence=`Apply this citation policy to every material claim:\n{{citationPolicy}}`;
const uncertainty=`Apply these uncertainty rules:\n{{uncertaintyPolicy}}`;
const prohibited=`The following behavior is prohibited:\n{{prohibitedBehaviors}}`;
const taskDetails:Record<AgentType,string>={
 "renewal-agent":"Assess renewal risk and blockers using supplied renewal date, ACV, usage, support, champion, sponsor, security, legal, and procurement facts. Estimate impact only from authoritative values. Recommend the smallest high-leverage human action.",
 "expansion-agent":"Identify supported expansion opportunity from adoption, unused capabilities, initiatives, stakeholder demand, opportunity value, use cases, and qualification gaps. Never invent budget. Separate observed demand from inferred potential.",
 "relationship-agent":"Review the stakeholder map, champion, economic buyer, executive sponsor, sentiment, engagement, role changes, and blockers. Recommend a specific human relationship action.",
 "forecast-agent":"Review stage, close date, forecast category, activity, next step, days in stage, qualification, and relationship strength. Flag unsupported or stale forecast certainty.",
 "executive-agent":"Recommend executive action only when verified impact, strategic tier, blockers, executive relationships, escalation needs, and approval requirements justify it.",
 "meeting-preparation-agent":"Prepare a concise briefing using supplied participants, roles, open decisions, recent changes, commitments, risks, agenda questions, and talk track. Never claim the meeting occurred."
};
const createdAt="2026-08-02T00:00:00.000Z";
 function definition(agentType:AgentType):PromptDefinition{const task=agentTaskCompatibility[agentType][0],promptId={"renewal-agent":"renewal-assess-risk","expansion-agent":"expansion-identify-opportunity","relationship-agent":"relationship-review","forecast-agent":"forecast-review","executive-agent":"executive-recommend-action","meeting-preparation-agent":"meeting-prepare"}[agentType];return{promptId,name:`${responsibleAgentNames[agentType]} ${task}`,description:`Controlled prompt for ${agentType} ${task}.`,agentType,supportedTaskTypes:[task as AgentTaskType],version:"1.0.0",status:"active",systemInstructionTemplate:system,taskInstructionTemplate:`Objective: {{taskObjective}}\nTask guidance: ${taskDetails[agentType]}\nDecision types in scope: ${allowedDecisionTypes[agentType].join(", ")}\nTime horizon: {{timeHorizon}}\nConstraints: {{taskConstraints}}\nCurrent time: {{currentTime}}\nAccount: {{accountName}}\nSupplied AgentContextPackage:\n{{contextPackage}}`,outputInstructionTemplate:output,evidenceInstructionTemplate:evidence,uncertaintyInstructionTemplate:uncertainty,prohibitedBehaviorTemplate:prohibited,contextSectionPolicy:contextSectionPolicies[agentType],citationPolicy:defaultCitationPolicy,uncertaintyPolicy:defaultUncertaintyPolicy,prohibitedBehaviors,outputSchemaVersion:reasoningVersions.decisionCandidateSchemaVersion,evaluationPolicyVersion:reasoningVersions.evaluationPolicyVersion,minimumContextVersion:contextVersions.contextVersion,tags:[agentType,task,"synthetic","provider-neutral"],createdAt,updatedAt:createdAt,changelog:[{version:"1.0.0",date:createdAt,author:"CogniVit AROS",summary:"Initial controlled prompt.",changeType:"major",expectedBehaviorImpact:"Establishes grounded schema-constrained behavior.",relatedEvaluationScenarioIds:[]}],metadata:{author:"CogniVit AROS",owner:"Revenue AI Governance",intendedUse:`Synthetic ${agentType} evaluation and future provider-neutral reasoning.`,knownLimitations:["No production provider is connected.","Token counts are estimates."],testCoverage:[`${agentType} prompt fixture`],releaseNotes:"Initial registry release.",synthetic:true,traceabilityRequired:true}};}
export const initialPromptDefinitions:PromptDefinition[]=(Object.keys(taskDetails) as AgentType[]).map(definition);
