import type {AgentType} from "@/domain/agents/types";import type {DecisionType} from "@/domain/decisions/types";import type {FactType} from "@/domain/facts/types";import type {ContextBudgetPolicy,ContextSection,RedactionPolicy} from "@/domain/llm-context/types";
export const contextVersions={contextVersion:"agent-context-v1",builderVersion:"context-builder-v1",schemaVersion:"agent-context-schema-v1",selectionPolicyVersion:"context-selection-v1",compressionPolicyVersion:"context-compression-v1",redactionPolicyVersion:"context-redaction-v1"} as const;
export interface AgentSelectionPolicy{sectionPriorities:Partial<Record<ContextSection,number>>;factTypes:FactType[];decisionTypes:DecisionType[];timelineCategories:string[];primaryStakeholderRoles:string[];lookbackDays:number;}
const common={"account-summary":1,commercial:.75,stakeholders:.65,relationships:.65,"recent-changes":.8,decisions:.8,evidence:.75,caveats:1,"data-confidence":.8,provenance:.8} satisfies Partial<Record<ContextSection,number>>;
export const agentSelectionPolicies:Record<AgentType,AgentSelectionPolicy>={
 "renewal-agent":{sectionPriorities:{...common,renewal:1,"product-usage":.75,qualification:.8,timeline:.8,risks:1},factTypes:["annual-contract-value","renewal-date","contract-end-date","security-review-status","legal-review-status","procurement-status","product-usage-trend","support-severity","champion","executive-sponsor","meddpicc-field"],decisionTypes:["renewal-risk","relationship-risk","executive-action"],timelineCategories:["commercial","support","engagement","decisions"],primaryStakeholderRoles:["champion","executive-sponsor","economic-buyer","security","legal","procurement"],lookbackDays:120},
 "expansion-agent":{sectionPriorities:{...common,opportunities:1,"product-usage":1,qualification:.8,"expansion-signals":1,timeline:.65},factTypes:["product-adoption","product-usage-trend","opportunity-value","opportunity-stage","close-date","strategic-initiative","meddpicc-field"],decisionTypes:["expansion-opportunity","forecast-risk"],timelineCategories:["product","commercial","engagement","decisions"],primaryStakeholderRoles:["champion","economic-buyer","business-buyer","technical-buyer"],lookbackDays:120},
 "relationship-agent":{sectionPriorities:{...common,stakeholders:1,relationships:1,timeline:1,risks:.8},factTypes:["champion","executive-sponsor","stakeholder-title","stakeholder-engagement","stakeholder-sentiment","relationship-strength","meeting-occurrence","meeting-outcome"],decisionTypes:["relationship-risk","meeting-preparation","executive-action"],timelineCategories:["engagement","decisions"],primaryStakeholderRoles:["champion","economic-buyer","executive-sponsor","blocker"],lookbackDays:90},
 "forecast-agent":{sectionPriorities:{...common,opportunities:1,qualification:1,timeline:.75,risks:.85},factTypes:["opportunity-stage","opportunity-value","close-date","forecast-category","meddpicc-field","stakeholder-engagement"],decisionTypes:["forecast-risk","expansion-opportunity"],timelineCategories:["commercial","engagement","decisions"],primaryStakeholderRoles:["champion","economic-buyer","business-buyer"],lookbackDays:120},
 "executive-agent":{sectionPriorities:{...common,commercial:1,renewal:.85,opportunities:.9,stakeholders:.8,risks:1,"expansion-signals":.9,"recent-changes":1,decisions:1},factTypes:["annual-contract-value","renewal-date","opportunity-value","executive-sponsor","relationship-strength","account-health-driver","strategic-initiative"],decisionTypes:["renewal-risk","expansion-opportunity","forecast-risk","executive-action","relationship-risk"],timelineCategories:["commercial","engagement","decisions","support"],primaryStakeholderRoles:["executive-sponsor","economic-buyer","champion","blocker"],lookbackDays:180},
 "meeting-preparation-agent":{sectionPriorities:{...common,commercial:.8,stakeholders:1,relationships:.9,timeline:1,decisions:.9,"unresolved-questions":1},factTypes:["meeting-occurrence","meeting-outcome","stakeholder-title","stakeholder-sentiment","relationship-strength","opportunity-value","renewal-date"],decisionTypes:["meeting-preparation","relationship-risk","executive-action","renewal-risk","expansion-opportunity"],timelineCategories:["engagement","commercial","decisions"],primaryStakeholderRoles:["executive-sponsor","economic-buyer","champion","technical-buyer","business-buyer"],lookbackDays:60}
};
export const defaultContextBudgetPolicy:ContextBudgetPolicy={targetTokenBudget:4000,hardTokenLimit:8000,reservedPromptTokens:600,reservedOutputTokens:1200,sectionBudgets:{timeline:700,evidence:650,stakeholders:550,decisions:650,qualification:450,"product-usage":400,opportunities:500,caveats:450,provenance:500},minimumRequiredSections:["account-summary","commercial","caveats","data-confidence","provenance"],maximumItemsPerSection:{timeline:8,evidence:10,stakeholders:8,decisions:6,qualification:8,"product-usage":4,opportunities:5,"recent-changes":6,"unresolved-questions":8},compressionThresholds:{summaryCharacters:650,itemCharacters:360}};
export const defaultRedactionPolicy:RedactionPolicy={excludedFieldPaths:["stakeholders.notes","sourceRecords","payload","metadata.raw"],allowedSensitiveCategories:[],maskEmailAddresses:true,maskPhoneNumbers:true,removeFreeformNotes:true,includeParticipantNames:true,includeSourceRecordIds:true,policyVersion:contextVersions.redactionPolicyVersion};
export const relevanceWeights={agentRelevance:.25,taskRelevance:.18,businessImpact:.16,urgency:.12,recency:.1,confidence:.08,authority:.06,timeSensitivity:.05};
export const contextPolicy={minimumConfidence:.4,lowConfidenceThreshold:.6,timelineLimit:8,evidenceLimit:10,stakeholderLimit:8,decisionLimit:6,unsupportedThreshold:.4,staleRelevantAllowed:true};
