import {NextResponse} from "next/server";import {getAuthenticatedIdentity,getRawSessionUser} from "@/auth/session.server";import {identityRepository} from "@/auth/repository.server";import {assignRevenueTeam,createOrganizationRole,createOrganizationalUnit,createRelationship} from "@/auth/tenant-model";import {recordAudit} from "@/auth/audit.server";import type {OrganizationalUnitType,RelationshipType,ParticipationType,RoleCategory} from "@/auth/types";
export async function POST(request:Request){
 const identity=await getAuthenticatedIdentity(),actor=await getRawSessionUser();if(!identity||!actor||!["ORG_OWNER","ORG_ADMIN"].includes(identity.membership.adminRole))return NextResponse.json({error:"Organization administrator access is required."},{status:403});
 let body:Record<string,unknown>;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid request."},{status:400})}
 let result;let event="";
 if(body.action==="role"){result=createOrganizationRole(identityRepository,identity.membership,{name:String(body.name??"").trim(),code:String(body.code??"").trim().toUpperCase(),category:"CUSTOM" as RoleCategory,description:null,systemTemplateId:body.systemTemplateId?String(body.systemTemplateId):null,defaultExperienceKey:null,permissions:[]});event="CUSTOM_ROLE_CREATED"}
 else if(body.action==="unit"){result=createOrganizationalUnit(identityRepository,identity.membership,{name:String(body.name??"").trim(),type:String(body.type) as OrganizationalUnitType,parentUnitId:body.parentUnitId?String(body.parentUnitId):null,leaderMembershipId:null});event="ORG_UNIT_CREATED"}
 else if(body.action==="relationship"){result=createRelationship(identityRepository,identity.membership,{sourceMembershipId:String(body.sourceMembershipId),targetMembershipId:String(body.targetMembershipId),relationshipType:String(body.relationshipType) as RelationshipType,isPrimary:body.relationshipType==="REPORTS_TO",metadata:null});event=body.relationshipType==="DOTTED_LINE_TO"?"DOTTED_LINE_CREATED":"REPORTING_RELATIONSHIP_CREATED"}
 else if(body.action==="revenue-team"){result=assignRevenueTeam(identityRepository,identity.membership,{accountId:body.accountId?String(body.accountId):null,opportunityId:body.opportunityId?String(body.opportunityId):null,membershipId:String(body.membershipId),organizationRoleDefinitionId:null,participationType:String(body.participationType) as ParticipationType,isPrimaryOwner:body.participationType==="OWNER"});event="REVENUE_TEAM_ASSIGNMENT_CREATED"}
 else return NextResponse.json({error:"Unsupported action."},{status:400});
 if(!result.ok)return NextResponse.json({error:result.error},{status:400});recordAudit(actor,{event,resourceType:String(body.action),resourceId:result.value.id,after:{...result.value}});return NextResponse.json(result.value,{status:201})
}
