import {mkdir,readFile,readdir,rename,writeFile} from "node:fs/promises";import path from "node:path";import type {SimulationScenario,SimulationSession} from "@/domain/simulation/types";import {revenueSimulatorConfig} from "./config";
export interface SimulationRepository{saveSession(session:SimulationSession):Promise<void>;loadSession(id:string):Promise<SimulationSession|undefined>;listSessions():Promise<SimulationSession[]>;saveScenario(scenario:SimulationScenario):Promise<void>;loadScenario(id:string):Promise<SimulationScenario|undefined>;}
const safe=(id:string)=>{if(!/^[a-zA-Z0-9._:-]+$/.test(id))throw new Error("invalid-simulation-id");return id;},sensitive=(value:unknown):boolean=>{if(!value||typeof value!=="object")return typeof value==="string"&&/(bearer\s|authorization:|api[_-]?key|client_secret)/i.test(value);return Object.entries(value as Record<string,unknown>).some(([key,item])=>["authorization","apikey","api_key","password","secret","credentials","headers"].includes(key.toLowerCase())||sensitive(item));};
export function exportScenario(scenario:SimulationScenario):string{const value=JSON.stringify(scenario,null,2);if(value.length>revenueSimulatorConfig.storage.maximumImportBytes)throw new Error("scenario-export-too-large");if(sensitive(scenario))throw new Error("simulation-sensitive-material-detected");return value;}
export function importScenario(value:string):SimulationScenario{if(value.length>revenueSimulatorConfig.storage.maximumImportBytes)throw new Error("scenario-import-too-large");const parsed=JSON.parse(value) as SimulationScenario;if(!parsed.scenarioId||!parsed.metadata?.synthetic||parsed.accountId!=="acct-coinbase")throw new Error("invalid-simulation-scenario");if(sensitive(parsed))throw new Error("simulation-sensitive-material-detected");return parsed;}
export function createInMemorySimulationRepository():SimulationRepository{const sessions=new Map<string,SimulationSession>(),scenarios=new Map<string,SimulationScenario>();return{async saveSession(session){if(sensitive(session))throw new Error("simulation-sensitive-material-detected");sessions.set(session.sessionId,structuredClone(session));},async loadSession(id){const value=sessions.get(id);return value&&structuredClone(value);},async listSessions(){return[...sessions.values()].map(value=>structuredClone(value));},async saveScenario(scenario){scenarios.set(scenario.scenarioId,structuredClone(scenario));},async loadScenario(id){const value=scenarios.get(id);return value&&structuredClone(value);}};}
export function createFilesystemSimulationRepository({rootDirectory=path.join(process.cwd(),".aros","revenue-simulator")}:{rootDirectory?:string}={}):SimulationRepository{const sessions=path.join(rootDirectory,"sessions"),scenarios=path.join(rootDirectory,"scenarios"),ensure=()=>Promise.all([mkdir(sessions,{recursive:true}),mkdir(scenarios,{recursive:true})]),atomic=async(file:string,value:unknown)=>{if(sensitive(value))throw new Error("simulation-sensitive-material-detected");const temporary=`${file}.${Date.now()}.tmp`;await writeFile(temporary,JSON.stringify(value,null,2),"utf8");await rename(temporary,file);};return{async saveSession(session){await ensure();await atomic(path.join(sessions,`${safe(session.sessionId)}.json`),session);},async loadSession(id){await ensure();try{return JSON.parse(await readFile(path.join(sessions,`${safe(id)}.json`),"utf8")) as SimulationSession;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;}},async listSessions(){await ensure();return Promise.all((await readdir(sessions)).filter(file=>file.endsWith(".json")).sort().map(async file=>JSON.parse(await readFile(path.join(sessions,file),"utf8")) as SimulationSession));},async saveScenario(scenario){await ensure();await atomic(path.join(scenarios,`${safe(scenario.scenarioId)}.json`),scenario);},async loadScenario(id){await ensure();try{return JSON.parse(await readFile(path.join(scenarios,`${safe(id)}.json`),"utf8")) as SimulationScenario;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;}}};}
export async function saveScenario(repository:SimulationRepository,scenario:SimulationScenario){await repository.saveScenario(scenario);return scenario;}
export const loadScenario=(repository:SimulationRepository,id:string)=>repository.loadScenario(id);
export async function replayScenario(session:SimulationSession,runner:(session:SimulationSession)=>Promise<SimulationSession>){let replay:SimulationSession={...structuredClone(session),executionMode:"replay",currentState:structuredClone(session.baselineState),queuedEvents:[...session.appliedEvents],appliedEvents:[],simulationSteps:[],status:"ready"};while(replay.queuedEvents.length)replay=await runner(replay);return replay;}
