import {describe,expect,it} from "vitest";import {defaultEvaluationPolicy} from "@/agent-evaluation";import {getEvaluationContext} from "@/data/evaluation-fixtures/context-fixtures";import {promptFixtures,promptFixtureRegistry} from "@/data/prompt-fixtures/prompt-fixtures";import {reasonerFixtures} from "@/data/evaluation-fixtures/reasoner-fixtures";import {agentTaskNow} from "@/data/synthetic/agent-tasks";import {runPromptFixture} from "@/prompt-regression";import type {AgentType} from "@/domain/agents/types";
const run=(id:string)=>{const fixture=promptFixtures.find(item=>item.fixtureId===id)!,context=getEvaluationContext(fixture.accountId,fixture.agentType as AgentType);return runPromptFixture({fixture,registry:promptFixtureRegistry,context,reasoner:reasonerFixtures[fixture.reasonerFixtureId],evaluatorPolicy:defaultEvaluationPolicy,now:agentTaskNow});};
describe("Prompt fixtures and regression",()=>{
 it("defines the required twenty fixtures",()=>expect(promptFixtures).toHaveLength(20));
 it("matches every non-regression fixture expectation",()=>{for(const fixture of promptFixtures.filter(item=>item.fixtureId!=="prompt-version-regression")){const result=run(fixture.fixtureId);expect(result.regression.expectedOutcomeMatched,`${fixture.fixtureId}: ${result.regression.findings.join(", ")}`).toBe(true)}});
 it("detects a prompt version regression",()=>{const result=run("prompt-version-regression");expect(result.regression.regressed).toBe(true);expect(result.auditEvents.at(-1)?.eventType).toBe("prompt-regression-detected")});
 it.each(["coinbase-renewal-prompt","paypal-expansion-prompt","nvidia-meeting-preparation-prompt","franklin-relationship-prompt","executive-action-prompt"])("runs %s through reasoner and evaluator",id=>{const result=run(id);expect(result.selection.errors,JSON.stringify(result.selection.errors)).toEqual([]);expect(result.build.errors,JSON.stringify(result.build.errors)).toEqual([]);expect(result.build.package).toBeDefined();expect(result.reasoning?.candidate).toBeDefined();expect(result.evaluation).toBeDefined()});
 it("blocks unsupported agents",()=>expect(run("unsupported-agent-prompt").selection.errors[0].code).toBe("unsupported-agent"));
 it("blocks over-budget prompts",()=>expect(run("over-token-limit-prompt").build.errors[0].code).toBe("prompt-over-budget"));
 it("detects hallucinating candidates",()=>{const result=run("hallucinating-through-evaluator");expect(result.evaluation?.verdict).toBe("fail");expect(result.evaluation?.hallucinationFindings.length).toBeGreaterThan(0)});
 it("emits prompt audit events",()=>expect(run("coinbase-renewal-prompt").auditEvents.map(item=>item.eventType)).toEqual(expect.arrayContaining(["prompt-fixture-started","prompt-selected","prompt-build-completed","prompt-fixture-completed"])));
});
