import type {AgentTaskType,AgentType} from "@/domain/agents/types";
import type {ContextCandidateItemType,ContextMandatoryStatus} from "@/domain/llm-context/explainability-types";
import type {ContextSection} from "@/domain/llm-context/types";
import {agentSelectionPolicies,defaultContextBudgetPolicy} from "../config";

export type ContextPolicyEffect="require"|"conditionally-require"|"prefer"|"boost"|"penalize"|"prohibit"|"force-caveat"|"require-compression"|"change-section"|"cap-items";
export interface ContextPolicyRule{ruleId:string;name:string;description:string;agentTypes:AgentType[];taskTypes:AgentTaskType[];itemTypes:ContextCandidateItemType[];sections:ContextSection[];conditions:{textIncludes?:string[];freshness?:string[];minimumConfidence?:number;maximumAgeDays?:number;minimumBusinessImpact?:number};effect:ContextPolicyEffect;scoreAdjustment:number;mandatoryStatus:ContextMandatoryStatus;precedence:number;enabled:boolean;version:string;rationale:string;}
export interface AgentContextSelectionPolicy{policyId:string;version:string;agentType:AgentType;requiredSections:ContextSection[];preferredItemTypes:ContextCandidateItemType[];prohibitedItemTypes:ContextCandidateItemType[];sectionPriorities:Partial<Record<ContextSection,number>>;sectionTokenBudgets:Partial<Record<ContextSection,number>>;minimumConfidence:number;maximumItems:Partial<Record<ContextSection,number>>;rules:ContextPolicyRule[];deduplicationStrategy:"highest-score-then-id";compressionStrategy:"mandatory-preserving";fallbackBehavior:"fail-closed";}
const version="context-selection-explainability-v1";
const commonRules:ContextPolicyRule[]=[{ruleId:"prohibit-unsupported",name:"Prohibit unsupported content",description:"Unsupported claims cannot enter model context.",agentTypes:["renewal-agent","expansion-agent","relationship-agent","forecast-agent","executive-agent","meeting-preparation-agent"],taskTypes:["assess-risk","identify-opportunity","prepare-meeting","review-relationship","review-forecast","recommend-executive-action"],itemTypes:["resolved-fact"],sections:["commercial","renewal","relationships","opportunities","qualification"],conditions:{},effect:"prohibit",scoreAdjustment:-1,mandatoryStatus:"prohibited",precedence:100,enabled:true,version,rationale:"Unsupported content would create hallucination risk."},{ruleId:"require-human-verified",name:"Require human verified facts",description:"Human-verified facts are mandatory when in agent scope.",agentTypes:["renewal-agent","expansion-agent","relationship-agent","forecast-agent","executive-agent","meeting-preparation-agent"],taskTypes:["assess-risk","identify-opportunity","prepare-meeting","review-relationship","review-forecast","recommend-executive-action"],itemTypes:["resolved-fact"],sections:["commercial","renewal","relationships","opportunities","qualification"],conditions:{},effect:"require",scoreAdjustment:.2,mandatoryStatus:"required",precedence:90,enabled:true,version,rationale:"Verified facts have explicit human authority."}];
const rulesByAgent:Record<AgentType,ContextPolicyRule[]>={
 "renewal-agent":[{ruleId:"renewal-core-facts",name:"Renewal core facts",description:"Renewal date, contract value and contract status are required when present.",agentTypes:["renewal-agent"],taskTypes:["assess-risk"],itemTypes:["resolved-fact","renewal-milestone"],sections:["commercial","renewal"],conditions:{textIncludes:["renewal date","annual contract value","contract status","contract end date"]},effect:"require",scoreAdjustment:.28,mandatoryStatus:"required",precedence:95,enabled:true,version,rationale:"Renewal timing and value define exposure."},{ruleId:"renewal-relationship-loss",name:"Active champion or sponsor loss",description:"Champion or executive sponsor loss is required.",agentTypes:["renewal-agent"],taskTypes:["assess-risk"],itemTypes:["stakeholder","resolved-fact","recent-change"],sections:["stakeholders","relationships","recent-changes"],conditions:{textIncludes:["champion left","champion loss","executive sponsor loss","departed"]},effect:"require",scoreAdjustment:.3,mandatoryStatus:"required",precedence:96,enabled:true,version,rationale:"Relationship loss is a leading renewal risk."},{ruleId:"renewal-process-conditional",name:"Active renewal process",description:"Security, legal and procurement status are conditional requirements.",agentTypes:["renewal-agent"],taskTypes:["assess-risk"],itemTypes:["resolved-fact","renewal-milestone","active-risk"],sections:["renewal","risks","commercial"],conditions:{textIncludes:["security","legal","procurement","support escalation"]},effect:"conditionally-require",scoreAdjustment:.2,mandatoryStatus:"conditionally-required",precedence:85,enabled:true,version,rationale:"Active process blockers can prevent renewal."},{ruleId:"renewal-methodology",name:"Renewal methodology relevance",description:"Usage decline and missing economic buyer receive high renewal relevance.",agentTypes:["renewal-agent"],taskTypes:["assess-risk"],itemTypes:["product-usage","meddpicc-field"],sections:["product-usage","qualification"],conditions:{textIncludes:["declin","economic buyer","champion","paper process"]},effect:"boost",scoreAdjustment:.18,mandatoryStatus:"preferred",precedence:70,enabled:true,version,rationale:"These are validated leading indicators."}],
 "expansion-agent":[{ruleId:"expansion-demand",name:"Observed expansion demand",description:"Fresh usage and opportunity evidence is preferred.",agentTypes:["expansion-agent"],taskTypes:["identify-opportunity"],itemTypes:["product-usage","opportunity","meddpicc-field"],sections:["product-usage","opportunities","qualification"],conditions:{},effect:"prefer",scoreAdjustment:.15,mandatoryStatus:"preferred",precedence:60,enabled:true,version,rationale:"Expansion needs demonstrated demand and qualification."}],
 "relationship-agent":[{ruleId:"relationship-primary-roles",name:"Primary relationship roles",description:"Champion, economic buyer and sponsor information is required when present.",agentTypes:["relationship-agent"],taskTypes:["review-relationship"],itemTypes:["stakeholder","meddpicc-field"],sections:["stakeholders","relationships","qualification"],conditions:{textIncludes:["champion","economic buyer","executive sponsor"]},effect:"require",scoreAdjustment:.2,mandatoryStatus:"required",precedence:80,enabled:true,version,rationale:"Relationship coverage depends on primary buying roles."}],
 "forecast-agent":[{ruleId:"forecast-core",name:"Forecast core",description:"Stage, close date and forecast category are required.",agentTypes:["forecast-agent"],taskTypes:["review-forecast"],itemTypes:["opportunity","resolved-fact"],sections:["opportunities","commercial"],conditions:{textIncludes:["stage","close date","forecast category"]},effect:"require",scoreAdjustment:.2,mandatoryStatus:"required",precedence:80,enabled:true,version,rationale:"Forecast assessment requires timing and stage."}],
 "executive-agent":[{ruleId:"executive-impact",name:"Executive impact",description:"High impact decisions and critical blockers are required.",agentTypes:["executive-agent"],taskTypes:["recommend-executive-action"],itemTypes:["governed-decision","active-risk","conflict"],sections:["decisions","risks","caveats"],conditions:{minimumBusinessImpact:500000},effect:"require",scoreAdjustment:.2,mandatoryStatus:"required",precedence:80,enabled:true,version,rationale:"Executive attention should focus on verified material impact."}],
 "meeting-preparation-agent":[{ruleId:"meeting-participants",name:"Meeting participants and open decisions",description:"Participants and relevant open decisions are required.",agentTypes:["meeting-preparation-agent"],taskTypes:["prepare-meeting"],itemTypes:["stakeholder","timeline-event","governed-decision"],sections:["stakeholders","timeline","decisions"],conditions:{},effect:"conditionally-require",scoreAdjustment:.18,mandatoryStatus:"conditionally-required",precedence:80,enabled:true,version,rationale:"Meeting preparation must reflect attendees and open decisions."}]
};
export const contextPolicyRegistryVersion="context-policy-registry-v2";
export const contextSelectionPolicies=Object.fromEntries((Object.keys(agentSelectionPolicies) as AgentType[]).map(agentType=>[agentType,{policyId:`${agentType}-context-policy`,version,agentType,requiredSections:["account-summary","commercial","caveats","data-confidence","provenance"],preferredItemTypes:agentType==="renewal-agent"?["renewal-milestone","stakeholder","product-usage","meddpicc-field","active-risk"]:["resolved-fact","stakeholder","governed-decision"],prohibitedItemTypes:[],sectionPriorities:agentSelectionPolicies[agentType].sectionPriorities,sectionTokenBudgets:defaultContextBudgetPolicy.sectionBudgets,minimumConfidence:.4,maximumItems:defaultContextBudgetPolicy.maximumItemsPerSection,rules:[...commonRules,...rulesByAgent[agentType]],deduplicationStrategy:"highest-score-then-id",compressionStrategy:"mandatory-preserving",fallbackBehavior:"fail-closed"} satisfies AgentContextSelectionPolicy])) as unknown as Record<AgentType,AgentContextSelectionPolicy>;
export function getContextSelectionPolicy(agentType:AgentType){return contextSelectionPolicies[agentType];}
