import type {AgentContextPackage,ContextSection} from "@/domain/llm-context/types";
import type {PromptContextReference,PromptContextSectionPolicy} from "@/domain/prompts/types";
import {stableSerialize} from "../diagnostics/stable-serialization";

const sectionValue=(context:AgentContextPackage,section:ContextSection):unknown=>({"account-summary":context.accountSummary,commercial:context.commercialContext,renewal:context.renewalContext,opportunities:context.opportunityContext,stakeholders:context.stakeholderContext,relationships:context.relationshipContext,"product-usage":context.productUsageContext,qualification:context.qualificationContext,"recent-changes":context.recentChanges,timeline:context.relevantTimeline,risks:context.activeRisks,"expansion-signals":context.expansionSignals,"unresolved-questions":context.unresolvedQuestions,decisions:context.governedDecisions,evidence:context.supportingEvidence,caveats:context.conflictsAndCaveats,"data-confidence":context.dataConfidence,"source-coverage":context.sourceCoverage,provenance:context.provenanceIndex}[section]);
const limit=(value:unknown,maximum?:number):unknown=>Array.isArray(value)&&maximum!==undefined?value.slice(0,maximum):value;
const empty=(value:unknown)=>value===undefined||value===null||value===""||(Array.isArray(value)&&value.length===0)||(typeof value==="object"&&!Array.isArray(value)&&Object.keys(value as object).length===0);
const strings=(value:unknown,key:string):string[]=>{const found:string[]=[];const visit=(item:unknown):void=>{if(Array.isArray(item))item.forEach(visit);else if(item&&typeof item==="object")for(const[field,nested]of Object.entries(item)){if(field===key&&typeof nested==="string")found.push(nested);else visit(nested);}};visit(value);return[...new Set(found)].sort();};
export function renderAgentContext(context:AgentContextPackage,policy:PromptContextSectionPolicy):{content:string;included:ContextSection[];excluded:ContextSection[];references:PromptContextReference[];omissions:string[]}{const included:ContextSection[]=[],excluded:ContextSection[]=[],references:PromptContextReference[]=[],parts:string[]=[];for(const section of policy.sectionOrder){if(policy.prohibitedSections.includes(section)){excluded.push(section);continue;}if(section==="source-coverage"&&!policy.includeSourceCoverage||section==="provenance"&&!policy.includeProvenanceIndex||section==="caveats"&&!policy.includeConflictDetails||section==="decisions"&&!policy.includeHistoricalDecisions){excluded.push(section);continue;}const value=limit(sectionValue(context,section),policy.maximumItemsPerSection[section]);if(empty(value)&&!policy.includeEmptySections){if(policy.requiredSections.includes(section))parts.push(`## ${section}\n[required section has no supplied data]`);else excluded.push(section);continue;}included.push(section);parts.push(`## ${section}\n${stableSerialize(value)}`);references.push({section,itemIds:[...new Set([...strings(value,"id"),...strings(value,"claimId")])].sort(),factIds:strings(value,"factId").concat(strings(value,"factIds")).flatMap(item=>item.includes(",")?item.split(","):item).sort(),evidenceIds:strings(value,"evidenceId").concat(strings(value,"evidenceIds")).flatMap(item=>item.includes(",")?item.split(","):item).sort(),conflictIds:strings(value,"conflictId").concat(strings(value,"conflictIds")).flatMap(item=>item.includes(",")?item.split(","):item).sort(),lineageIds:strings(value,"lineageId").concat(strings(value,"lineageIds")).flatMap(item=>item.includes(",")?item.split(","):item).sort()});}const omissions=policy.includeOmissions?context.omissions.map(item=>`${item.section}:${item.itemId}:${item.reason}`):[];if(policy.includeOmissions)parts.push(`## context-limitations\n${stableSerialize({omissions,contextLimits:context.contextLimits})}`);return{content:parts.join("\n\n"),included,excluded:[...new Set([...excluded,...policy.prohibitedSections])],references,omissions};}
