import type { AccountDigitalTwin, DataQualityAssessment, SourceCoverage } from "@/domain/accounts/account-digital-twin";
import type { AccountFact, FactType, FactValue } from "@/domain/facts/types";
import type { EvidenceSource } from "@/domain/evidence/types";
import type { SourceRecord } from "@/domain/sources/types";
export type FreshnessStatus="fresh"|"aging"|"stale"|"expired"|"unknown";
export interface SourceValidationIssue{code:string;field:string;message:string;severity:"warning"|"error"|"fatal";recoverable:boolean;}
export interface SourceValidationResult{valid:boolean;errors:SourceValidationIssue[];warnings:SourceValidationIssue[];validatedAt:string;source:EvidenceSource;sourceRecordId:string;disposition:"accepted"|"accepted-with-warnings"|"quarantined"|"rejected";}
export interface SourceValidationBatchResult{acceptedRecords:SourceRecord[];quarantinedRecords:SourceRecord[];rejectedRecords:SourceRecord[];results:SourceValidationResult[];duplicateRecordIds:string[];}
export type ConflictSeverity="low"|"medium"|"high"|"critical";
export type ConflictType="value-mismatch"|"date-mismatch"|"status-mismatch"|"identity-mismatch"|"stale-versus-fresh"|"authoritative-versus-nonauthoritative"|"human-override-conflict"|"semantic-conflict";
export interface FactResolution{conflictId:string;selectedFactId:string;selectedValue:FactValue;method:"source-authority"|"freshness"|"reliability"|"corroboration"|"direct-observation"|"human-override"|"calculated-consensus"|"unresolved";confidence:number;reason:string;rejectedFactIds:string[];resolvedAt:string;resolvedBy:string;policyVersion:string;requiresSourceCorrection:boolean;correctionTarget?:string;}
export interface EvidenceConflict{id:string;accountId:string;factType:FactType;fieldPath:string;competingFactIds:string[];competingValues:FactValue[];detectedAt:string;severity:ConflictSeverity;conflictType:ConflictType;status:"unresolved"|"auto-resolved"|"human-review-required"|"human-resolved"|"ignored";recommendedResolution:string;resolvedFactId?:string;resolution?:FactResolution;requiresHumanReview:boolean;auditTrail:string[];}
export interface HumanFactOverride{id:string;accountId:string;factType:FactType;fieldPath:string;value:FactValue;createdBy:string;createdAt:string;reason:string;evidenceIds:string[];expiresAt?:string;status:"active"|"expired"|"revoked"|"superseded";supersedesFactIds:string[];auditTrail:string[];}
export interface ResolvedFactConfidence{sourceAuthority:number;sourceReliability:number;freshness:number;directness:number;corroboration:number;consistency:number;verification:number;total:number;explanation:string;}
export interface LineageStep{stepType:string;inputIds:string[];outputId:string;ruleId:string;ruleVersion:string;timestamp:string;details:string;}
export interface EvidenceLineage{lineageId:string;accountId:string;outputFactId:string;sourceRecordIds:string[];sourceFactIds:string[];transformationSteps:LineageStep[];ruleVersions:string[];generatedAt:string;explanation:string;}
export interface ResolvedAccountFact{id:string;accountId:string;factType:FactType;fieldPath:string;value:FactValue;selectedFactId:string;supportingFactIds:string[];rejectedFactIds:string[];confidence:ResolvedFactConfidence;freshnessStatus:FreshnessStatus;authoritySource:EvidenceSource;resolutionMethod:FactResolution["method"];conflictIds:string[];lineage:EvidenceLineage;humanVerified:boolean;effectiveAt:string;resolvedAt:string;expiresAt?:string;explanation:string;}
export interface ReconciliationSummary{sourceRecordCount:number;acceptedRecordCount:number;quarantinedRecordCount:number;rejectedRecordCount:number;extractedFactCount:number;resolvedFactCount:number;conflictCount:number;autoResolvedConflictCount:number;humanReviewConflictCount:number;staleFactCount:number;humanVerifiedFactCount:number;overallConfidence:number;completedAt:string;}
export interface ResolvedAccountContext{accountId:string;asOf:string;facts:ResolvedAccountFact[];factsByType:Partial<Record<FactType,ResolvedAccountFact[]>>;conflicts:EvidenceConflict[];unresolvedConflicts:EvidenceConflict[];humanOverrides:HumanFactOverride[];sourceCoverage:SourceCoverage[];dataQuality:DataQualityAssessment;lineageIndex:Record<string,EvidenceLineage>;staleFactCount:number;unsupportedFactCount:number;criticalConflictCount:number;reconciliationSummary:ReconciliationSummary;validationResults:SourceValidationResult[];sourceRecords:SourceRecord[];}
export interface AccountReconciliationResult{context:ResolvedAccountContext;facts:AccountFact[];conflicts:EvidenceConflict[];diagnostics:Record<string,number>;}
export interface IncrementalTwinUpdateResult{accountId:string;changedFactIds:string[];addedFactIds:string[];supersededFactIds:string[];newConflictIds:string[];resolvedConflictIds:string[];affectedTwinSections:string[];previousTwin:AccountDigitalTwin;updatedTwin:AccountDigitalTwin;reconciliationState:ResolvedAccountContext;decisionsRequiringReevaluation:string[];auditEvents:string[];diagnostics:Record<string,number>;}

