import type { AIExecutionStage, AIExecutionStageKey, AIExecutionTrace, ArtifactStageSnapshot, ContextStageSnapshot, DigitalTwinStageSnapshot, EconomicsStageSnapshot, EligibilityStageSnapshot, EvaluationStageSnapshot, GovernanceStageSnapshot, ParsingStageSnapshot, PromptStageSnapshot, ProviderStageSnapshot, ReconciliationStageSnapshot, SourceStageSnapshot, WorkspaceStageSnapshot } from "@/domain/ai-developer-console/types";
import type { EvaluationArtifact } from "@/domain/evaluation-artifacts/types";
import type { LLMRequest, LLMResponse } from "@/domain/llm-provider/types";
import type { PromptDefinition, PromptPackage } from "@/domain/prompts/types";
import type { AgentContextBuildResult, AgentContextPackage } from "@/domain/llm-context/types";
import type { SimulationSession, SimulationStep } from "@/domain/simulation/types";
import type { DecisionControlResult } from "@/decision-control";
import { contentHash, stableSerialize } from "@/prompt-builder";
import { aiDeveloperConsoleConfig, screenRedactionPolicy } from "../config";
import { redactAIConsoleValue } from "../redaction/redact";

const labels: Record<AIExecutionStageKey,string>={source:"Evidence",reconciliation:"Reconciliation","digital-twin":"Digital Twin",context:"Context",prompt:"Prompt",provider:"Provider",parsing:"Parser",evaluation:"Evaluation",eligibility:"Eligibility",governance:"Decision Control",economics:"Economics",artifact:"Artifact",workspace:"Workspace"};
function stage<T>(key:AIExecutionStageKey,status:AIExecutionStage<T>["status"],output?:T,options:Partial<AIExecutionStage<T>>={}):AIExecutionStage<T>{return{stageId:`stage-${key}`,stageName:labels[key],status,inputReferences:[],output,warnings:[],errors:[],auditEventIds:[],versionMetadata:{},diagnostics:{},...options};}
const unavailable=<T>(key:AIExecutionStageKey,reason:string)=>stage<T>(key,"unavailable",undefined,{diagnostics:{unavailableReason:reason}});

export interface BuildTraceInput { simulationSession?: SimulationSession; simulationStep?: SimulationStep; evaluationArtifact?: EvaluationArtifact; agentContext?: AgentContextPackage; contextBuildResult?: AgentContextBuildResult; promptDefinition?: PromptDefinition; promptPackage?: PromptPackage; providerRequest?: LLMRequest; providerResponse?: LLMResponse; decisionControlResult?: DecisionControlResult; executionMode?: AIExecutionTrace["executionMode"]; now: string; }

export function buildAIExecutionTrace(input:BuildTraceInput):AIExecutionTrace {
  const {simulationSession:session,simulationStep:step,evaluationArtifact:artifact,promptDefinition,promptPackage,providerRequest,providerResponse,now}=input;
  const contextBuild=input.contextBuildResult??step?.contextBuildResult;
  const context=input.agentContext??contextBuild?.context??undefined;
  const candidate=step?.reasoningResult?.candidate??artifact?.decisionCandidate;
  const evaluation=step?.evaluationResult??artifact?.evaluationResult;
  const eligibility=step?.eligibilityResult;
  const governance=input.decisionControlResult??step?.governedDecisionResult;
  const traceId=providerRequest?.traceId??promptPackage?.traceId??step?.reasoningResult?.metadata.traceId??artifact?.evaluationResult.metadata.reasoning.traceId??`trace-${artifact?.artifactId??step?.stepId??now}`;
  const requestId=providerRequest?.requestId??promptPackage?.requestId??step?.reasoningResult?.metadata.requestId??artifact?.evaluationResult.metadata.reasoning.requestId??`request-${traceId}`;
  const state=step?.state??session?.currentState;
  const mode=input.executionMode??session?.executionMode??(artifact?.metadata.source==="artifact-replay"?"replay":"deterministic");
  const source=state?stage("source","completed",{sourceRecordIds:state.sourceRecords.map(item=>item.sourceRecordId),addedSourceRecordIds:step?.addedSourceRecordIds??[],synthetic:true,rawPayloadsIncluded:false as const},{completedAt:step?.completedAt??now,inputReferences:[state.accountDigitalTwin.accountId],diagnostics:{recordCount:state.sourceRecords.length}}):unavailable<SourceStageSnapshot>("source","No simulation source snapshot is associated with this trace.");
  const sourceRecordIds=state?.sourceRecords.map(item=>item.sourceRecordId)??[];
  const reconciliation=state?stage("reconciliation","completed",{contextId:`resolved-${state.resolvedAccountContext.accountId}-${state.resolvedAccountContext.asOf}`,factIds:state.resolvedAccountContext.facts.map(item=>item.id),conflictIds:state.resolvedAccountContext.conflicts.map(item=>item.id),sourceRecordCount:state.resolvedAccountContext.sourceRecords.length},{completedAt:step?.completedAt??now,inputReferences:sourceRecordIds,versionMetadata:{asOf:state.resolvedAccountContext.asOf},diagnostics:{changedFactCount:step?.changedFactIds.length??0}}):unavailable<ReconciliationStageSnapshot>("reconciliation","Reconciliation snapshot was not persisted by the source artifact.");
  const twin=state?.accountDigitalTwin;
  const digitalTwin=twin?stage("digital-twin","completed",{accountId:twin.accountId,accountName:twin.identity.name,generatedAt:twin.generatedAt,healthScore:twin.health.overallScore,renewalLikelihood:twin.renewalProfile?.renewalLikelihood??0,evidenceIds:twin.evidence.map(item=>item.id),activeDecisionIds:twin.activeDecisions.map(item=>item.id)},{completedAt:step?.completedAt??now,inputReferences:[`resolved-${state!.resolvedAccountContext.accountId}-${state!.resolvedAccountContext.asOf}`],versionMetadata:{generatedAt:twin.generatedAt},diagnostics:{evidenceCount:twin.evidence.length}}):unavailable<DigitalTwinStageSnapshot>("digital-twin","Digital Twin snapshot is unavailable.");
  const contextStage=context&&contextBuild?stage("context",contextBuild.warnings.length?"completed-with-warnings":"completed",{build:contextBuild,context},{completedAt:step?.completedAt??now,inputReferences:[twin?.accountId??context.accountId],warnings:contextBuild.warnings.map(item=>item.message),errors:contextBuild.errors.map(item=>item.message),contentHash:contentHash(stableSerialize(context)),versionMetadata:{contextVersion:context.contextVersion,builderVersion:context.metadata.builderVersion},diagnostics:{selectedItems:contextBuild.diagnostics.selectedItemCount,excludedItems:contextBuild.diagnostics.excludedItemCount,tokens:contextBuild.tokenEstimate.totalEstimatedTokens}}):context?stage("context","completed",{build:{context,diagnostics:{candidateItemCount:0,selectedItemCount:context.claims.length,excludedItemCount:context.omissions.length,estimatedTokensBeforeCompression:0,estimatedTokensAfterCompression:0,sectionsCompressed:[],staleItemsIncluded:context.dataConfidence.staleFactCount,conflictsIncluded:context.conflictsAndCaveats.length,unsupportedItemsExcluded:context.dataConfidence.unsupportedFactCount,evidenceReferencesIncluded:context.supportingEvidence.length,buildDurationMs:0,warnings:[]},warnings:[],errors:[],excludedItems:context.omissions,tokenEstimate:{estimatedInputTokens:0,reservedPromptTokens:0,reservedOutputTokens:0,totalEstimatedTokens:0,withinBudget:true,estimationMethod:"artifact-snapshot",margin:0},buildMetadata:context.metadata},context},{completedAt:now,inputReferences:[context.accountId],contentHash:contentHash(stableSerialize(context)),versionMetadata:{contextVersion:context.contextVersion,builderVersion:context.metadata.builderVersion},diagnostics:{selectedItems:context.claims.length,excludedItems:context.omissions.length}}):unavailable<ContextStageSnapshot>("context","AgentContextBuildResult is unavailable; artifact retains only its context reference.");
  const promptStage=promptPackage?stage("prompt","completed",{definition:promptDefinition,promptPackage,selectionReason:promptDefinition?"explicit-version":"retained-package"},{completedAt:promptPackage.buildMetadata.builtAt,inputReferences:[promptPackage.contextId],contentHash:promptPackage.buildMetadata.contentHash,versionMetadata:{promptVersion:promptPackage.promptVersion,builderVersion:promptPackage.buildMetadata.builderVersion,schemaVersion:promptPackage.outputSchemaVersion},diagnostics:{messageCount:promptPackage.messages.length,estimatedTokens:promptPackage.estimatedTokens.totalEstimatedTokens}}):unavailable<PromptStageSnapshot>("prompt","This historical run did not retain its PromptPackage; no prompt was reconstructed.");
  const safeRequest=providerRequest?redactAIConsoleValue(providerRequest,screenRedactionPolicy) as LLMRequest:undefined;
  const safeResponse=providerResponse?redactAIConsoleValue(providerResponse,screenRedactionPolicy) as LLMResponse:undefined;
  const providerStage=providerRequest||providerResponse?stage("provider",providerResponse?"completed":"failed",{request:safeRequest,response:safeResponse,translatedRequestRedacted:true,rawOutputAvailable:Boolean(providerResponse&&screenRedactionPolicy.includeRawProviderOutput)},{startedAt:step?.startedAt??now,completedAt:providerResponse?.createdAt,inputReferences:[promptPackage?.promptPackageId??requestId],warnings:providerResponse?.diagnostics.normalizationWarnings??[],versionMetadata:{provider:providerResponse?.provider??String(providerRequest?.metadata.provider??"provider-neutral"),model:providerResponse?.model??providerRequest?.model??"unknown"},diagnostics:{latencyMs:providerResponse?.latencyMs??0,retries:providerResponse?.diagnostics.retries??0,redacted:true}}):unavailable<ProviderStageSnapshot>("provider",mode==="deterministic"?"Deterministic reasoning made no provider call.":"Provider request or response was not retained by policy.");
  const parse=step?.reasoningResult?.parseResult;
  const parsingStage=parse?stage("parsing",parse.success?"completed":"failed",{parseResult:parse,rawOutput:step?.reasoningResult?.response?.rawOutput,candidate:parse.candidate},{completedAt:step?.reasoningResult?.metadata.completedAt,inputReferences:[requestId],warnings:parse.warnings.map(item=>item.message),errors:parse.errors.map(item=>item.message),versionMetadata:{schemaVersion:parse.schemaVersion},diagnostics:{unknownFieldCount:parse.rawOutputMetadata.unknownFields.length}}):candidate?unavailable<ParsingStageSnapshot>("parsing","Artifact stores the parsed candidate but not the original parse result."):unavailable<ParsingStageSnapshot>("parsing","No response was available to parse.");
  const evaluationStage=evaluation?stage("evaluation",evaluation.verdict==="fail"?"failed":evaluation.findings.length?"completed-with-warnings":"completed",{evaluation},{completedAt:evaluation.evaluatedAt,inputReferences:[evaluation.candidateId,evaluation.contextId],warnings:evaluation.findings.filter(item=>!item.blocking).map(item=>item.message),errors:evaluation.findings.filter(item=>item.blocking).map(item=>item.message),auditEventIds:evaluation.auditEvents.map(item=>item.id),versionMetadata:{policyVersion:evaluation.policyVersion,schemaVersion:evaluation.metadata.evaluationSchemaVersion},diagnostics:{score:evaluation.overallScore,verdict:evaluation.verdict,grounding:evaluation.groundingSummary.coverageScore}}):unavailable<EvaluationStageSnapshot>("evaluation","Evaluation result is unavailable.");
  const eligibilityStage=eligibility?stage("eligibility",eligibility.eligible?"completed":eligibility.requiredReview?"completed-with-warnings":"failed",{eligibility},{inputReferences:[evaluation?.evaluationId??"evaluation-unavailable"],errors:eligibility.blockingFindings.map(item=>item.message),diagnostics:{eligible:eligibility.eligible,nextStep:eligibility.allowedNextStep}}):unavailable<EligibilityStageSnapshot>("eligibility",artifact?"Artifact does not persist the standalone eligibility result.":"Eligibility was not evaluated.");
  const governanceStage=governance?stage("governance",governance.rejectedCandidates.length&&!governance.acceptedDecisions.length?"failed":governance.warnings.length?"completed-with-warnings":"completed",{result:governance,candidate,governedDecisions:governance.acceptedDecisions},{completedAt:step?.completedAt??now,inputReferences:candidate?[candidate.candidateId]:[],warnings:governance.warnings.flatMap(item=>item.messages),errors:governance.rejectedCandidates.flatMap(item=>item.issues.map(issue=>issue.message)),auditEventIds:governance.auditEvents.map(item=>item.id),diagnostics:{accepted:governance.acceptedDecisions.length,rejected:governance.rejectedCandidates.length}}):unavailable<GovernanceStageSnapshot>("governance","Decision Control did not run or its result was not retained.");
  const economicsStage=step?.analytics?stage("economics","completed",{analytics:step.analytics},{completedAt:step.analytics.calculatedAt,inputReferences:[requestId],versionMetadata:{analyticsVersion:step.analytics.analyticsVersion,pricingVersion:step.analytics.cost.pricingVersion??"unavailable"},diagnostics:{incrementalCostUsd:step.analytics.cost.incrementalCostUsd,totalLatencyMs:step.analytics.latency.totalMs,qualityScore:step.analytics.quality.overallScore}}):unavailable<EconomicsStageSnapshot>("economics","No step economics were attached to this run.");
  const artifactStage=artifact?stage("artifact","completed",{artifact},{completedAt:artifact.createdAt,inputReferences:[artifact.runId],contentHash:artifact.artifactHash,versionMetadata:{artifactVersion:artifact.artifactVersion},diagnostics:{immutable:artifact.metadata.immutableSnapshot}}):unavailable<ArtifactStageSnapshot>("artifact","No evaluation artifact is associated with this trace.");
  const governed=governance?.acceptedDecisions??[];
  const workspaceStage=governed.length?stage("workspace","completed",{destination:"renewal-workspace" as const,decisionIds:governed.map(item=>item.id)},{inputReferences:governed.map(item=>item.id),diagnostics:{decisionCount:governed.length}}):unavailable<WorkspaceStageSnapshot>("workspace","No governed decision was available for a product workspace.");
  const stages=[source,reconciliation,digitalTwin,contextStage,promptStage,providerStage,parsingStage,evaluationStage,eligibilityStage,governanceStage,economicsStage,artifactStage,workspaceStage];
  const errors=stages.flatMap(item=>item.errors),warnings=stages.flatMap(item=>item.warnings);
  return {traceId,requestId,runId:artifact?.runId??session?.sessionId??traceId,sessionId:session?.sessionId,stepId:step?.stepId,scenarioId:artifact?.scenarioId??session?.scenarioId,accountId:artifact?.accountId??session?.accountId??context?.accountId??"unknown",accountName:session?.accountName??context?.accountName??"Unknown account",agentType:artifact?.agentType??session?.agentType??context?.agentType??"renewal-agent",taskType:session?.taskType??context?.task.taskType??"assess-risk",executionMode:mode,status:errors.length?"completed-with-warnings":mode==="replay"?"replayed":"completed",createdAt:step?.startedAt??artifact?.createdAt??now,completedAt:step?.completedAt??artifact?.createdAt??now,sourceStage:source,reconciliationStage:reconciliation,digitalTwinStage:digitalTwin,contextStage,promptStage,providerStage,parsingStage,evaluationStage,eligibilityStage,governanceStage,economicsStage,artifactStage,workspaceStage,warnings,errors,metadata:{consoleVersion:aiDeveloperConsoleConfig.consoleVersion,traceSchemaVersion:aiDeveloperConsoleConfig.traceSchemaVersion,redactionPolicyVersion:screenRedactionPolicy.policyVersion,developmentOnly:true,replay:mode==="replay",provider:providerResponse?.provider??evaluation?.metadata.reasoning.provider,model:providerResponse?.model??evaluation?.metadata.reasoning.model,promptVersion:promptPackage?.promptVersion??artifact?.promptVersion,evaluationVerdict:evaluation?.verdict,eligible:eligibility?.eligible}};
}

export function getTraceStages(trace:AIExecutionTrace):Array<[AIExecutionStageKey,AIExecutionStage<unknown>]> { const stages:Record<AIExecutionStageKey,AIExecutionStage<unknown>>={source:trace.sourceStage,reconciliation:trace.reconciliationStage,"digital-twin":trace.digitalTwinStage,context:trace.contextStage,prompt:trace.promptStage,provider:trace.providerStage,parsing:trace.parsingStage,evaluation:trace.evaluationStage,eligibility:trace.eligibilityStage,governance:trace.governanceStage,economics:trace.economicsStage,artifact:trace.artifactStage,workspace:trace.workspaceStage};return aiDeveloperConsoleConfig.stageOrder.map(key=>[key,stages[key]]); }
