import {render,screen} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {describe,expect,it} from "vitest";import {accountDigitalTwins} from "@/data/synthetic/final-account-digital-twins";import {resolvedAccountContexts} from "@/data/synthetic/resolved-account-contexts";import {ContextInspector} from "./context-inspector";
const contexts=Object.fromEntries(Object.entries(resolvedAccountContexts).map(([id,context])=>[id,{...context,sourceRecords:[]}])) ,decisions=accountDigitalTwins.flatMap(twin=>twin.activeDecisions);
describe("ContextInspector",()=>{
 it("renders context diagnostics",()=>{render(<ContextInspector twins={accountDigitalTwins} contexts={contexts} decisions={decisions}/>);expect(screen.getByRole("heading",{name:"LLM Context Inspector"})).toBeVisible();expect(screen.getByRole("region",{name:"Context diagnostics"})).toBeVisible();expect(screen.getByText("Account summary")).toBeVisible()});
 it("switches agent types",async()=>{render(<ContextInspector twins={accountDigitalTwins} contexts={contexts} decisions={decisions}/>);await userEvent.selectOptions(screen.getByLabelText("Agent type"),"expansion-agent");expect(screen.getByLabelText("Task type")).toHaveValue("identify opportunity");expect(screen.getByText(/provider-neutral context selection/i)).toBeVisible()});
 it("switches accounts",async()=>{render(<ContextInspector twins={accountDigitalTwins} contexts={contexts} decisions={decisions}/>);await userEvent.selectOptions(screen.getByLabelText("Account"),"acct-paypal");expect(screen.getByText(/PayPal is/i)).toBeVisible()});
 it("displays omissions",()=>{render(<ContextInspector twins={accountDigitalTwins} contexts={contexts} decisions={decisions}/>);expect(screen.getByRole("heading",{name:/Omissions ·/i})).toBeVisible();expect(screen.getAllByText(/out-of-scope|section-limit|token-budget/i).length).toBeGreaterThan(0)});
 it("supports token-budget changes",async()=>{render(<ContextInspector twins={accountDigitalTwins} contexts={contexts} decisions={decisions}/>);const input=screen.getByLabelText("Token budget");await userEvent.clear(input);await userEvent.type(input,"2200");expect(input).toHaveValue(2200)});
});
