import {describe,expect,it} from "vitest";
import type {AgentType} from "@/domain/agents/types";
import {accountDigitalTwins} from "@/data/synthetic/final-account-digital-twins";
import {resolvedAccountContexts} from "@/data/synthetic/resolved-account-contexts";
import {agentTaskNow,createSyntheticAgentTask} from "@/data/synthetic/agent-tasks";
import {buildAgentContext,compareContextSelections,getContextSelectionPolicy,simulateContextPolicy} from "@/llm-context";
const twin=accountDigitalTwins.find(item=>item.accountId==="acct-coinbase")!,resolved=resolvedAccountContexts["acct-coinbase"]!;
function build(agentType:AgentType="renewal-agent",policy?:Parameters<typeof buildAgentContext>[0]["policy"]){return buildAgentContext({agentType,task:createSyntheticAgentTask(twin.accountId,agentType),accountTwin:twin,resolvedContext:resolved,governedDecisions:twin.activeDecisions,policy,now:agentTaskNow});}
describe("context selection explainability",()=>{
 it("creates a complete deterministic candidate decision ledger",()=>{const first=build(),second=build();expect(first.context).toBeTruthy();expect(first.candidates?.length).toBe(first.selectionDecisions?.length);expect(first.selectionDecisions).toEqual(second.selectionDecisions);expect(first.selectionDecisions?.every(item=>item.decisionStages[0]?.stage==="candidate-generated")).toBe(true);expect(first.selectionDecisions?.every(item=>item.humanReadableExplanation.length>20)).toBe(true);});
 it("preserves fact, evidence, conflict, lineage, and source references",()=>{const result=build(),fact=result.candidates?.find(item=>item.factIds.length&&item.lineageIds.length);expect(fact?.sourceRecordIds.length).toBeGreaterThan(0);expect(fact?.fullValueReference).toContain(":");});
 it.each(["renewal-agent","expansion-agent","relationship-agent","forecast-agent","executive-agent","meeting-preparation-agent"] as AgentType[])("exposes a versioned explicit %s policy",agent=>{const policy=getContextSelectionPolicy(agent);expect(policy.version).toMatch(/^context-selection/);expect(policy.rules.length).toBeGreaterThan(1);expect(policy.fallbackBehavior).toBe("fail-closed");});
 it("classifies renewal core facts and process blockers explicitly",()=>{const result=build(),renewal=result.selectionDecisions?.filter(item=>result.candidates?.find(value=>value.candidateId===item.candidateId)?.itemType==="renewal-milestone")??[];expect(renewal.some(item=>["required","conditionally-required"].includes(item.mandatoryStatus))).toBe(true);expect(renewal.flatMap(item=>item.matchedRules)).toContain("renewal-core-facts");});
 it("attributes methodology and named policy adjustments",()=>{const result=build(),adjusted=result.selectionDecisions?.find(item=>item.scoreBreakdown.policyAdjustments.length);expect(adjusted?.scoreBreakdown.explanation).toContain("named policy adjustment");expect(adjusted?.scoreBreakdown.policyAdjustments[0]?.ruleId).toBeTruthy();});
 it("distinguishes section, scope, trust and budget exclusions",()=>{const result=build("renewal-agent",{targetTokenBudget:1200,hardTokenLimit:8000,maximumItemsPerSection:{timeline:2,evidence:3,stakeholders:3}}),dispositions=new Set(result.selectionDecisions?.filter(item=>!item.selected).map(item=>item.finalDisposition));expect(dispositions.has("excluded-section-limit")||dispositions.has("excluded-token-budget")||dispositions.has("excluded-agent-scope")).toBe(true);expect(result.selectionDecisions?.filter(item=>!item.selected).every(item=>item.exclusionReason)).toBe(true);});
 it("allocates mandatory before preferred and optional and records compression",()=>{const result=build("renewal-agent",{targetTokenBudget:1200,hardTokenLimit:8000});expect(result.tokenBudgetLedger?.mandatoryTokensAllocated).toBeGreaterThan(0);expect(result.tokenBudgetLedger?.explanation).toContain("mandatory items were allocated before preferred and optional");expect(result.compressionDecisions?.every(item=>item.preservedFields.includes("fact IDs"))).toBe(true);});
 it("calculates multidimensional context quality",()=>{const quality=build().contextQuality;expect(quality?.mandatoryCoverage).toBeGreaterThanOrEqual(0);expect(quality?.taskCriticalCoverage).toBeGreaterThanOrEqual(0);expect(quality?.explanation).toContain("mandatory coverage");});
 it.each(["champion","renewal date","security review","economic buyer","product usage"])("traces %s availability across stages",concept=>{const trace=build().availabilityIndex?.find(item=>item.requestedConcept===concept);expect(trace).toBeTruthy();expect(trace?.explanation.length).toBeGreaterThan(20);expect(trace?.status).toMatch(/available|blocked|unavailable|gap/);});
 it("simulates and compares a policy without mutating baseline context",()=>{const task=createSyntheticAgentTask(twin.accountId,"renewal-agent"),input={agentType:"renewal-agent" as const,task,accountTwin:twin,resolvedContext:resolved,governedDecisions:twin.activeDecisions,now:agentTaskNow},simulation=simulateContextPolicy({builderInput:input,candidatePolicy:{targetTokenBudget:1800,maximumItemsPerSection:{timeline:2,evidence:4}},now:agentTaskNow}),comparison=compareContextSelections(simulation.baselineBuild,simulation.candidateBuild);expect(simulation.baselineBuild.context?.contextId).toBe(simulation.candidateBuild.context?.contextId);expect(simulation.candidatePolicy.policyId).toContain("experiment");expect(comparison.tokenChange).toBe(simulation.tokenChange);expect(simulation.recommendation).toMatch(/promotion|removed context/);});
 it("keeps AgentContextPackage and Prompt Builder inputs backward compatible",()=>{const result=build();expect(result.context?.contextVersion).toBe("agent-context-v1");expect("selectionDecisions" in result.context!).toBe(false);expect(result.context?.metadata.selectionPolicyVersion).toBe("context-selection-v1");});
});
