import type {AgentType,AgentTaskType} from "@/domain/agents/types";
import type {SimulationExecutionMode,SimulationScenario,SimulationSession} from "@/domain/simulation/types";
import type {EvaluationArtifact} from "@/domain/evaluation-artifacts/types";

export type CoverageStatus="not-tested"|"partially-tested"|"tested"|"passed"|"failed"|"stale"|"blocked"|"not-applicable";
export type ScenarioReadinessStatus="untested"|"insufficient-coverage"|"needs-improvement"|"internally-ready"|"design-partner-ready"|"blocked";
export type ScenarioCategory="healthy-baseline"|"single-risk"|"combined-risk"|"recovery"|"contradiction"|"stale-data"|"missing-data"|"malformed-data"|"context-budget"|"provider-failure"|"governance"|"end-to-end-demo";
export type BlockerCategory="missing-coverage"|"failed-assertion"|"grounding"|"hallucination"|"eligibility"|"human-review"|"resilience"|"demo-reliability"|"stale-artifact"|"incompatible-version"|"missing-baseline"|"environment"|"unknown";
export interface ReadinessBlocker{blockerId:string;scenarioId:string;category:BlockerCategory;severity:"warning"|"critical";code:string;message:string;requiredAction:string;sourceReferences:string[];blocking:boolean;detectedAt:string;}
export interface ScenarioReadinessPolicy{requiredExecutionModes:SimulationExecutionMode[];minimumAssertionPassRate:number;minimumGroundingScore:number;minimumEligibilityRate:number;maximumBlockingHallucinations:number;minimumRecommendationCorrectness:number;minimumActionability:number;minimumEvidenceSufficiency:number;minimumPriorityAppropriateness:number;minimumHumanApprovalRate:number;minimumRecoveryAccuracy:number;maximumArtifactAgeDays:number;requireHumanReview:boolean;requireReplayCoverage:boolean;requireFaultCoverage:boolean;requireDemoCoverage:boolean;policyVersion:string;}
export interface ScenarioCoverageRecord{scenarioId:string;scenarioName:string;scenarioVersion:string;accountId:string;agentType:AgentType;taskType:AgentTaskType;category:ScenarioCategory;eventTypes:string[];riskTypes:string[];recoveryIncluded:boolean;contradictionIncluded:boolean;deterministicCoverage:CoverageStatus;replayCoverage:CoverageStatus;liveProviderCoverage:CoverageStatus;humanReviewCoverage:CoverageStatus;evaluationCoverage:CoverageStatus;governanceCoverage:CoverageStatus;contextPolicyCoverage:CoverageStatus;promptVersionCoverage:CoverageStatus;resilienceCoverage:CoverageStatus;demoCoverage:CoverageStatus;latestRunAt?:string;latestSuccessfulRunAt?:string;assertionPassRate:number;groundingScore:number;eligibilityRate:number;blockingHallucinationCount:number;humanApprovalRate:number;recommendationCorrectness:number;actionability:number;evidenceSufficiency:number;priorityAppropriateness:number;recoveryAccuracy:number;readinessStatus:ScenarioReadinessStatus;readinessBlockers:ReadinessBlocker[];warnings:string[];metadata:Record<string,string|number|boolean>;}
export interface ScenarioCoverageSummary{total:number;ready:number;internal:number;untested:number;failed:number;blocked:number;criticalBlockers:number;coveragePercent:number;}
export interface ScenarioCoverageMatrix{generatedAt:string;policyVersion:string;records:ScenarioCoverageRecord[];summary:ScenarioCoverageSummary;coverageGaps:string[];recommendedNextTests:string[];}
export interface ScenarioCoverageSnapshot{snapshotId:string;createdAt:string;policyVersion:string;scenarioRecords:ScenarioCoverageRecord[];summary:ScenarioCoverageSummary;contentHash:string;previousSnapshotHash?:string;}
export interface CoverageSnapshotComparison{baselineSnapshotId:string;candidateSnapshotId:string;newlyReady:string[];regressed:string[];resolvedBlockers:number;newBlockers:number;coverageDelta:number;}

export type FaultCategory="missing-data"|"stale-data"|"conflicting-data"|"malformed-data"|"duplicate-data"|"out-of-order-data"|"context-overflow"|"prompt-build"|"provider-timeout"|"provider-rate-limit"|"provider-unavailable"|"authentication"|"cancellation"|"malformed-response"|"parser-failure"|"evaluation-failure"|"eligibility-failure"|"governance-rejection"|"artifact-corruption"|"persistence-failure"|"replay-mismatch"|"configuration-failure";
export type FaultTargetStage="source-validation"|"evidence-reconciliation"|"digital-twin"|"context-builder"|"prompt-builder"|"provider-readiness"|"provider"|"parser"|"evaluation"|"eligibility"|"decision-control"|"artifact-store"|"replay"|"workspace-rendering";
export interface FaultDefinition{faultId:string;name:string;description:string;category:FaultCategory;targetStage:FaultTargetStage;injectionPoint:string;severity:"low"|"medium"|"high"|"critical";expectedBehavior:string;recoveryPolicy:string;enabled:boolean;version:string;metadata:Record<string,string|number|boolean>;}
export interface FaultInjectionPlan{planId:string;name:string;description:string;scenarioId:string;faultIds:string[];executionMode:SimulationExecutionMode;sequence:"ordered"|"isolated";stopOnBlockingFailure:boolean;recoverySteps:string[];expectedAssertions:ResilienceAssertionCategory[];version:string;tags:string[];}
export type ResilienceAssertionCategory="fail-closed"|"no-hallucination"|"trusted-state-preserved"|"human-state-preserved"|"no-governance-bypass"|"bounded-retry"|"cancellation-respected"|"uncertainty-visible"|"audit-preserved"|"recovery"|"UI-graceful-degradation";
export interface ResilienceAssertion{assertionId:string;category:ResilienceAssertionCategory;expected:string;actual:string;passed:boolean;severity:"warning"|"critical";blocking:boolean;explanation:string;evidenceReferences:string[];}
export interface FaultStepResult{fault:FaultDefinition;status:"passed"|"failed"|"warning";affectedStage:FaultTargetStage;assertions:ResilienceAssertion[];errorCode?:string;recovered:boolean;durationMs:number;}
export interface ResilienceAssessment{failClosedScore:number;trustedStatePreservation:number;humanStatePreservation:number;uncertaintyCommunication:number;retrySafety:number;cancellationSafety:number;governanceIntegrity:number;traceIntegrity:number;recoveryScore:number;gracefulDegradationScore:number;blockingFailures:string[];overallStatus:"resilient"|"resilient-with-warnings"|"needs-improvement"|"unsafe"|"unable-to-assess";explanation:string;}
export interface FaultInjectionRunResult{runId:string;planId:string;scenarioId:string;startedAt:string;completedAt:string;injectedFaults:string[];stepResults:FaultStepResult[];assertions:ResilienceAssertion[];resilienceAssessment:ResilienceAssessment;trustedStatePreserved:boolean;humanWorkflowStatePreserved:boolean;unsafeRecommendationCreated:boolean;governanceBypassed:boolean;retriesExhaustedSafely:boolean;recoverySucceeded:boolean;warnings:string[];errors:string[];diagnostics:Record<string,string|number|boolean>;}

export interface DemoStep{stepId:string;sequence:number;name:string;description:string;action:string;expectedResult:string;timeoutMs:number;required:boolean;retryPolicy:{maximumAttempts:number};evidenceCapture:string[];tags:string[];}
export interface DesignPartnerDemoFlow{flowId:string;name:string;description:string;version:string;scenarioId:string;requiredEnvironment:"development"|"test";steps:DemoStep[];assertions:string[];fixtureRequirements:string[];approvedArtifactIds:string[];maximumDurationMs:number;policyVersion:string;status:"draft"|"active"|"deprecated"|"archived";}
export interface DemoStepResult{stepId:string;status:"passed"|"failed"|"skipped"|"blocked"|"timed-out"|"warning";startedAt:string;completedAt:string;durationMs:number;attempts:number;assertionResults:{name:string;passed:boolean;explanation:string}[];screenshotsOrArtifacts?:string[];traceIds:string[];warnings:string[];errors:string[];}
export interface DesignPartnerDemoPolicy{minimumConsecutiveSuccessfulRuns:number;minimumRequiredStepPassRate:number;maximumCriticalFailures:number;maximumFlakyStepRate:number;maximumTotalDurationMs:number;maximumConsoleErrors:number;requireApprovedReplayArtifact:boolean;requireArtifactIntegrity:boolean;requireSecretScan:boolean;requireMorningBriefing:boolean;requireRenewalWorkspace:boolean;requireSimulator:boolean;requireEvidenceExplorer:boolean;requireHumanApproval:boolean;requireTraceInspection:boolean;policyVersion:string;}
export interface DemoReliabilityReport{runId:string;flowId:string;flowVersion:string;environment:string;startedAt:string;completedAt:string;totalDurationMs:number;requiredStepCount:number;passedRequiredSteps:number;failedRequiredSteps:number;warningCount:number;passRate:number;criticalFailures:string[];flakySteps:string[];traceIds:string[];artifactIds:string[];readinessStatus:"ready"|"ready-with-warnings"|"not-ready"|"blocked";blockers:string[];recommendations:string[];metadata:Record<string,string|number|boolean>;stepResults:DemoStepResult[];}
export interface DemoReliabilityHistory{runCount:number;consecutiveSuccessfulRuns:number;stepStatistics:{stepId:string;passRate:number;averageDurationMs:number;p95DurationMs:number;intermittentFailureRate:number;retryFrequency:number;timeoutFrequency:number;mostCommonFailure?:string;}[];flakyStepRate:number;}
export interface DemoEnvironmentValidation{valid:boolean;errors:string[];warnings:string[];fixtureIds:string[];artifactIds:string[];secretScanPassed:boolean;replayOnly:boolean;}
export type TestReadinessCIOutcome="PASS"|"FAIL"|"MANUAL REVIEW REQUIRED";
export interface PlatformTestReadinessSummary{generatedAt:string;scenarioCoverage:ScenarioCoverageSummary;resilienceStatus:ResilienceAssessment["overallStatus"];demoReliabilityStatus:DemoReliabilityReport["readinessStatus"];criticalScenarioCount:number;readyScenarioCount:number;untestedScenarioCount:number;failedScenarioCount:number;blockingHallucinationCount:number;criticalResilienceFailures:number;demoPassRate:number;consecutiveSuccessfulDemoRuns:number;designPartnerReady:boolean;blockers:string[];recommendedNextTests:string[];policyVersions:Record<string,string>;ciOutcome:TestReadinessCIOutcome;}
export interface TestReadinessInput{scenarios:SimulationScenario[];simulationRuns:SimulationSession[];evaluationArtifacts:EvaluationArtifact[];faultRuns:FaultInjectionRunResult[];demoRuns:DemoReliabilityReport[];}
