import { createHash } from "node:crypto";
import { Pool, type PoolClient } from "pg";
import { createDemoIdentityStore } from "../src/auth/seed";
import { syntheticAccounts } from "../src/data/synthetic/accounts";
import { accountDigitalTwins } from "../src/data/synthetic/final-account-digital-twins";
import { governedDecisions } from "../src/features/morning-briefing/data";
import {createCoinbaseRenewalWorkspaceFixture} from "../src/data/renewal-intelligence-fixtures/coinbase";

async function main(){if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");
const pool = new Pool({connectionString:process.env.DATABASE_URL});
const store=createDemoIdentityStore(),now="2026-08-12T16:00:00.000Z";
const json=(value:unknown)=>JSON.stringify(value??null);

async function seedIdentity(client:PoolClient){
 for(const organization of store.organizations)await client.query(`INSERT INTO organizations(id,name,slug,status,primary_domain,environment,timezone,fiscal_year_start_month,default_methodology,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET name=excluded.name,updated_at=excluded.updated_at`,[organization.id,organization.name,organization.slug,organization.status,organization.primaryDomain,organization.environment,organization.timezone,organization.fiscalYearStartMonth,organization.defaultMethodology,organization.createdAt,organization.updatedAt]);
 for(const region of store.regions)await client.query(`INSERT INTO regions(id,organization_id,name,parent_region_id) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET name=excluded.name`,[region.id,region.organizationId,region.name,region.parentRegionId]);
 for(const user of store.users)await client.query(`INSERT INTO users(id,organization_id,email,first_name,last_name,display_name,role,status,timezone,avatar_url,is_demo_user,is_admin,password_hash,platform_role,created_at,updated_at,last_login_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT(id) DO UPDATE SET email=excluded.email,password_hash=excluded.password_hash,updated_at=excluded.updated_at`,[user.id,user.organizationId,user.email,user.firstName,user.lastName,user.displayName,user.role,user.status,user.timezone,user.avatarUrl,user.isDemoUser,user.isAdmin,user.passwordHash,user.platformRole,user.createdAt,user.updatedAt,user.lastLoginAt]);
 for(const team of store.teams)await client.query(`INSERT INTO teams(id,organization_id,name,manager_user_id,parent_team_id,type,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET name=excluded.name,manager_user_id=excluded.manager_user_id`,[team.id,team.organizationId,team.name,team.managerUserId,team.parentTeamId,team.type,team.createdAt,team.updatedAt]);
 for(const user of store.users)await client.query(`UPDATE users SET manager_user_id=$2,team_id=$3,region_id=$4 WHERE id=$1`,[user.id,user.managerUserId,user.teamId,user.regionId]);
 for(const membership of store.memberships)await client.query(`INSERT INTO organization_memberships(id,organization_id,user_id,admin_role,status,joined_at,permission_overrides,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET admin_role=excluded.admin_role,status=excluded.status,updated_at=excluded.updated_at`,[membership.id,membership.organizationId,membership.userId,membership.adminRole,membership.status,membership.joinedAt,json(membership.permissionOverrides??{}),membership.createdAt,membership.updatedAt]);
 for(const template of store.systemRoleTemplates)await client.query(`INSERT INTO system_role_templates(id,code,name,category,description,default_experience_key,default_permissions,capabilities,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET name=excluded.name,is_active=excluded.is_active`,[template.id,template.code,template.name,template.category,template.description,template.defaultExperienceKey,json(template.defaultPermissions),json(template.capabilities),template.isActive]);
 for(const role of store.organizationRoles)await client.query(`INSERT INTO organization_role_definitions(id,organization_id,name,code,system_template_id,category,description,default_experience_key,permissions,is_system_seeded,is_active,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(id) DO UPDATE SET name=excluded.name,system_template_id=excluded.system_template_id,is_active=excluded.is_active,updated_at=excluded.updated_at`,[role.id,role.organizationId,role.name,role.code,role.systemTemplateId,role.category,role.description,role.defaultExperienceKey,json(role.permissions),role.isSystemSeeded,role.isActive,role.createdAt,role.updatedAt]);
 for(const assignment of store.roleAssignments)await client.query(`INSERT INTO membership_role_assignments(id,organization_id,membership_id,organization_role_definition_id,is_primary,effective_from,effective_to,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET is_primary=excluded.is_primary,effective_to=excluded.effective_to,updated_at=excluded.updated_at`,[assignment.id,assignment.organizationId,assignment.membershipId,assignment.organizationRoleDefinitionId,assignment.isPrimary,assignment.effectiveFrom,assignment.effectiveTo,assignment.createdAt,assignment.updatedAt]);
 for(const unit of store.organizationalUnits)await client.query(`INSERT INTO organizational_units(id,organization_id,name,type,parent_unit_id,leader_membership_id,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET name=excluded.name,parent_unit_id=excluded.parent_unit_id,leader_membership_id=excluded.leader_membership_id,status=excluded.status`,[unit.id,unit.organizationId,unit.name,unit.type,unit.parentUnitId,unit.leaderMembershipId,unit.status,unit.createdAt,unit.updatedAt]);
 for(const item of store.unitMemberships)await client.query(`INSERT INTO membership_organizational_units(id,organization_id,membership_id,organizational_unit_id,membership_type,is_primary,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO NOTHING`,[item.id,item.organizationId,item.membershipId,item.organizationalUnitId,item.membershipType,item.isPrimary,item.createdAt]);
 for(const item of store.relationships)await client.query(`INSERT INTO organization_relationships(id,organization_id,source_membership_id,target_membership_id,relationship_type,is_primary,effective_from,effective_to,metadata,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO NOTHING`,[item.id,item.organizationId,item.sourceMembershipId,item.targetMembershipId,item.relationshipType,item.isPrimary,item.effectiveFrom,item.effectiveTo,json(item.metadata),item.createdAt,item.updatedAt]);
}

async function ensureTenant(client:PoolClient,id:string,name:string,slug:string){
 await client.query(`INSERT INTO organizations(id,name,slug,status,environment,timezone,created_at,updated_at) VALUES($1,$2,$3,'ACTIVE','SANDBOX','America/Los_Angeles',$4,$4) ON CONFLICT(id) DO NOTHING`,[id,name,slug,now]);
 const uid=`user-${slug}`,mid=`membership-${slug}`;
 await client.query(`INSERT INTO users(id,organization_id,email,first_name,last_name,display_name,role,status,is_demo_user,is_admin,password_hash,created_at,updated_at) VALUES($1,$2,$3,'Design','Partner',$4,'AE','ACTIVE',false,true,$5,$6,$6) ON CONFLICT(id) DO NOTHING`,[uid,id,`owner@${slug}.example`,`${name} Owner`,createHash("sha256").update("ArosDemo!2026").digest("hex"),now]);
 await client.query(`INSERT INTO organization_memberships(id,organization_id,user_id,admin_role,status,joined_at,created_at,updated_at) VALUES($1,$2,$3,'ORG_OWNER','ACTIVE',$4,$4,$4) ON CONFLICT(id) DO NOTHING`,[mid,id,uid,now]);
 return mid;
}

async function seedRevenue(client:PoolClient){
 for(const account of syntheticAccounts)await client.query(`INSERT INTO accounts(id,organization_id,external_id,name,segment,status,created_at,updated_at) VALUES($1,'org-cognivit-demo',$1,$2,$3,$4,$5,$5) ON CONFLICT(id) DO UPDATE SET name=excluded.name,updated_at=excluded.updated_at`,[account.id,account.name,account.segment,account.accountStatus.toUpperCase(),now]);
 for(const twin of accountDigitalTwins){const summary=twin as typeof twin&{healthScore?:number;riskLevel?:string},renewalWorkspace=twin.accountId==="acct-coinbase"?createCoinbaseRenewalWorkspaceFixture():undefined;await client.query(`INSERT INTO revenue_digital_twins(id,organization_id,account_id,health_state,risk_state,lifecycle_state,state,created_at,updated_at) VALUES($1,'org-cognivit-demo',$2,$3,$4,'ACTIVE',$5,$6,$6) ON CONFLICT(organization_id,account_id) DO UPDATE SET state=excluded.state,health_state=excluded.health_state,risk_state=excluded.risk_state,updated_at=excluded.updated_at`,[`twin-${twin.accountId}`,twin.accountId,String(summary.healthScore??"UNKNOWN"),String(summary.riskLevel??"UNKNOWN"),json({...twin,renewalWorkspace}),now]);for(const stakeholder of twin.stakeholders)await client.query(`INSERT INTO revenue_stakeholders(id,organization_id,account_id,name,title,department,seniority,buying_role,influence_level,support_level,relationship_strength,engagement_trend,sentiment,last_interaction_at,attributes,updated_at) VALUES($1,'org-cognivit-demo',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET name=excluded.name,attributes=excluded.attributes,updated_at=excluded.updated_at`,[stakeholder.id,twin.accountId,stakeholder.name,stakeholder.title,stakeholder.department,stakeholder.seniority,stakeholder.roleInBuyingProcess,stakeholder.influenceLevel,stakeholder.supportLevel,stakeholder.relationshipStrength,stakeholder.engagementTrend,stakeholder.sentiment,stakeholder.lastInteractionAt,json({isChampion:stakeholder.isChampion,isEconomicBuyer:stakeholder.isEconomicBuyer,isExecutiveSponsor:stakeholder.isExecutiveSponsor,isBlocker:stakeholder.isBlocker,sourceIds:stakeholder.sourceIds,notes:stakeholder.notes}),now]);await client.query(`INSERT INTO methodology_states(id,organization_id,account_id,methodology,completeness_score,state,updated_at) VALUES($1,'org-cognivit-demo',$2,'MEDDPICC',$3,$4,$5) ON CONFLICT(organization_id,account_id,methodology) DO UPDATE SET completeness_score=excluded.completeness_score,state=excluded.state,updated_at=excluded.updated_at`,[`methodology-${twin.accountId}`,twin.accountId,twin.meddpicc.completenessScore,json(twin.meddpicc),now]);for(const event of twin.fullTimeline)await client.query(`INSERT INTO revenue_digital_twin_events(id,organization_id,revenue_digital_twin_id,event_type,payload,occurred_at,created_at) VALUES($1,'org-cognivit-demo',$2,$3,$4,$5,$6) ON CONFLICT(id) DO NOTHING`,[event.id,`twin-${twin.accountId}`,event.type,json(event),event.occurredAt,now])}
 for(const twin of accountDigitalTwins){for(const opportunity of twin.opportunities)await client.query(`INSERT INTO opportunities(id,organization_id,account_id,external_id,name,stage,amount,currency,close_date,status,created_at,updated_at) VALUES($1,'org-cognivit-demo',$2,$1,$3,$4,$5,$6,$7,'OPEN',$8,$8) ON CONFLICT(id) DO UPDATE SET stage=excluded.stage,amount=excluded.amount,close_date=excluded.close_date,updated_at=excluded.updated_at`,[opportunity.id,twin.accountId,opportunity.name,opportunity.stage,opportunity.amount,opportunity.currency,opportunity.closeDate,now]);for(const [index,risk] of twin.knownRisks.entries())await client.query(`INSERT INTO revenue_signals(id,organization_id,account_id,type,source,severity,confidence,payload,observed_at,created_at) VALUES($1,'org-cognivit-demo',$2,'ACCOUNT_RISK','deterministic-seed','HIGH',0.9,$3,$4,$4) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,observed_at=excluded.observed_at`,[`signal-${twin.accountId}-risk-${index}`,twin.accountId,json({risk}),now])}
 for(const decision of governedDecisions)await client.query(`INSERT INTO action_decisions(id,organization_id,account_id,type,recommendation,status,evidence,metadata,idempotency_key,created_at,updated_at) VALUES($1,'org-cognivit-demo',$2,$3,$4,'PENDING',$5,$6,$1,$7,$7) ON CONFLICT(id) DO UPDATE SET recommendation=excluded.recommendation,metadata=excluded.metadata`,[decision.id,decision.accountId,decision.type,decision.recommendedAction,json(decision.evidence),json(decision),now]);
 const acmeMember=await ensureTenant(client,"org-acme","Acme Software","acme-software"),globexMember=await ensureTenant(client,"org-globex","Globex Technologies","globex-technologies");
 for(const [org,id,name,member] of [["org-acme","acct-acme","Acme Design Account",acmeMember],["org-globex","acct-globex","Globex Design Account",globexMember]] as const){await client.query(`INSERT INTO accounts(id,organization_id,external_id,name,status,created_at,updated_at) VALUES($1,$2,$1,$3,'ACTIVE',$4,$4) ON CONFLICT(id) DO NOTHING`,[id,org,name,now]);await client.query(`INSERT INTO opportunities(id,organization_id,account_id,name,status,owner_membership_id,created_at,updated_at) VALUES($1,$2,$3,$4,'OPEN',$5,$6,$6) ON CONFLICT(id) DO NOTHING`,[`opp-${id}`,org,id,`${name} Opportunity`,member,now]);await client.query(`INSERT INTO revenue_digital_twins(id,organization_id,account_id,lifecycle_state,state,created_at,updated_at) VALUES($1,$2,$3,'ACTIVE',$4,$5,$5) ON CONFLICT(id) DO NOTHING`,[`twin-${id}`,org,id,json({accountId:id,accountName:name}),now]);await client.query(`INSERT INTO revenue_signals(id,organization_id,account_id,type,source,severity,confidence,payload,observed_at,created_at) VALUES($1,$2,$3,'ACCOUNT_HEALTH','deterministic-seed','MEDIUM',0.8,'{}',$4,$4) ON CONFLICT(id) DO NOTHING`,[`signal-${id}`,org,id,now]);await client.query(`INSERT INTO action_decisions(id,organization_id,account_id,type,recommendation,status,idempotency_key,created_at,updated_at) VALUES($1,$2,$3,'FOLLOW_UP','Review account context','PENDING',$1,$4,$4) ON CONFLICT(id) DO NOTHING`,[`action-${id}`,org,id,now]);}
 await client.query(`INSERT INTO accounts(id,organization_id,external_id,name,status,created_at,updated_at) VALUES('acct-other-tenant','org-isolation-test','acct-other-tenant','Isolation Account','ACTIVE',$1,$1) ON CONFLICT(id) DO NOTHING`,[now]);
 for(const assignment of store.revenueTeamAssignments)await client.query(`INSERT INTO revenue_team_assignments(id,organization_id,account_id,opportunity_id,membership_id,organization_role_definition_id,participation_type,is_primary_owner,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) ON CONFLICT(id) DO UPDATE SET participation_type=excluded.participation_type,is_primary_owner=excluded.is_primary_owner,updated_at=excluded.updated_at`,[assignment.id,assignment.organizationId,assignment.accountId,assignment.opportunityId,assignment.membershipId,assignment.organizationRoleDefinitionId,assignment.participationType,assignment.isPrimaryOwner,assignment.createdAt]);
}

const client=await pool.connect();try{await client.query("BEGIN");await seedIdentity(client);await seedRevenue(client);await client.query("COMMIT");console.log("Seeded relational identity and deterministic revenue tenants.");}catch(error){await client.query("ROLLBACK");throw error}finally{client.release();await pool.end()}
}main().catch(error=>{console.error(error);process.exitCode=1});
