import type { GovernedDecision } from "@/domain/decisions/types";
import type { EvidenceItem, EvidenceSource } from "@/domain/evidence/types";
import type { StrategicTier } from "./types";
import type { ResolvedAccountContext } from "@/domain/reconciliation/types";

export type Trend = "improving"|"stable"|"declining"|"unknown";
export type HealthStatus = "healthy"|"watch"|"at-risk"|"critical"|"unknown";
export type RelationshipState = "strong"|"healthy"|"weakening"|"at-risk"|"inactive"|"unknown";
export type StakeholderRole = "champion"|"economic-buyer"|"executive-sponsor"|"technical-buyer"|"business-buyer"|"procurement"|"legal"|"security"|"influencer"|"user"|"blocker"|"unknown";
export interface AccountIdentity { id:string;name:string;legalName:string;industry:string;segment:string;region:string;headquarters:string;website:string;employeeCount:number;annualRevenue?:number;strategicTier:StrategicTier;accountStatus:"active"|"inactive";ownerId:string;ownerName:string;teamMemberIds:string[];createdAt:string;updatedAt:string; }
export interface CommercialProfile { annualContractValue:number;totalContractValue:number;currency:"USD";contractStartDate:string;contractEndDate:string;renewalDate:string;renewalTerm:number;productsPurchased:string[];currentSpendByProduct:Record<string,number>;openPipelineValue:number;expansionPotential:number;paymentStatus:"current"|"late"|"unknown";contractStatus:"active"|"expiring"|"inactive"; }
export interface Stakeholder { id:string;accountId:string;name:string;title:string;department:string;seniority:string;roleInBuyingProcess:StakeholderRole;influenceLevel:"high"|"medium"|"low";supportLevel:"advocate"|"supportive"|"neutral"|"skeptical"|"opposed";relationshipStrength:RelationshipState;engagementTrend:Trend;sentiment:"positive"|"neutral"|"negative"|"unknown";isChampion:boolean;isEconomicBuyer:boolean;isExecutiveSponsor:boolean;isBlocker:boolean;lastInteractionAt:string;interactionCount30Days:number;interactionCount90Days:number;sourceIds:string[];notes:string[]; }
export interface StakeholderMap { economicBuyer?:Stakeholder;champion?:Stakeholder;executiveSponsor?:Stakeholder;blockers:Stakeholder[];technicalEvaluators:Stakeholder[];procurement:Stakeholder[];legal:Stakeholder[];security:Stakeholder[];endUsers:Stakeholder[];missingRoles:StakeholderRole[]; }
export interface Opportunity { id:string;accountId:string;name:string;type:"new-business"|"expansion"|"cross-sell"|"upsell"|"renewal"|"services";stage:string;amount:number;currency:"USD";probability:number;closeDate:string;ownerId:string;useCases:string[];products:string[];nextStep:string;nextStepDueAt:string;daysInStage:number;lastActivityAt:string;forecastCategory:string;qualificationCompleteness:number;risks:string[];sourceRecordId:string; }
export interface RenewalProfile { renewalDate:string;daysUntilRenewal:number;annualContractValue:number;renewalLikelihood:number;renewalStage:string;usageHealth:HealthStatus;relationshipHealth:HealthStatus;supportHealth:HealthStatus;commercialHealth:HealthStatus;securityReviewStatus:string;legalReviewStatus:string;procurementStatus:string;executiveAlignmentStatus:string;renewalRisks:string[];renewalPlan:string[];nextMilestone:string;milestoneDueAt:string; }
export interface ProductUsageSummary { productId:string;productName:string;activeUsers:number;licensedUsers:number;adoptionRate:number;usageTrend:Trend;usageChange30Days:number;usageChange90Days:number;featureAdoption:Record<string,number>;keyUseCases:string[];unusedCapabilities:string[];lastUpdatedAt:string;sourceRecordIds:string[]; }
export type ActivityType = "meeting"|"call"|"email"|"crm-update"|"support-event"|"usage-event"|"contract-event"|"stakeholder-change"|"external-news"|"decision"|"human-action";
export interface AccountActivity { id:string;accountId:string;type:ActivityType;source:EvidenceSource;title:string;summary:string;occurredAt:string;participants:string[];stakeholderIds:string[];opportunityId?:string;sentiment?:"positive"|"neutral"|"negative";outcome?:string;nextSteps:string[];sourceRecordId:string;evidenceIds:string[]; }
export interface StrategicInitiative { id:string;accountId:string;name:string;description:string;executiveOwner:string;businessPriority:"high"|"medium"|"low";status:string;expectedTimeline:string;relatedUseCases:string[];relatedProducts:string[];relatedOpportunityIds:string[];evidenceIds:string[]; }
export type MEDDPICCKey = "metrics"|"economic-buyer"|"decision-criteria"|"decision-process"|"paper-process"|"identify-pain"|"champion"|"competition";
export type QualificationStatus = "confirmed"|"partial"|"assumed"|"missing"|"stale"|"not-applicable";
export interface MEDDPICCField { key:MEDDPICCKey;status:QualificationStatus;value:string;confidence:number;evidenceIds:string[];lastUpdatedAt:string;owner:string;gaps:string[];recommendedNextStep:string; }
export interface MEDDPICCProfile { fields:MEDDPICCField[];completenessScore:number;confirmedCount:number;missingCount:number;staleCount:number;criticalGaps:string[];recommendedActions:string[]; }
export interface AccountHealth { overallScore:number;overallStatus:HealthStatus;commercialScore:number;relationshipScore:number;productUsageScore:number;supportScore:number;renewalScore:number;opportunityScore:number;qualificationScore:number;dataQualityScore:number;trend:Trend;drivers:string[];risks:string[];opportunities:string[];calculatedAt:string; }
export interface DataQualityAssessment { completenessScore:number;freshnessScore:number;consistencyScore:number;sourceCoverageScore:number;overallScore:number;missingFields:string[];staleFields:string[];conflictingFields:string[];unsupportedClaims:string[];lastEvaluatedAt:string; }
export interface SourceCoverage { source:EvidenceSource;connected:boolean;recordCount:number;latestRecordAt:string|null;freshnessStatus:"fresh"|"stale"|"missing";reliability:number;limitations:string[]; }
export interface ProvenanceRecord { fieldPath:string;derivationType:"normalized"|"calculated"|"aggregated"|"inferred";sourceIds:string[];evidenceIds:string[];calculatedAt:string;ruleVersion:string;explanation:string; }
export interface AccountSnapshot { id:string;accountId:string;capturedAt:string;healthScore:number;relationshipScore:number;usageScore:number;renewalLikelihood:number;openPipelineValue:number;meddpiccCompleteness:number;activeRiskCount:number;activeDecisionCount:number;stakeholderEngagementSummary:RelationshipState; }
export interface SnapshotChange { field:string;previous:string|number;current:string|number;delta?:number;summary:string;severity:"positive"|"negative"|"neutral"; }
export interface SnapshotSummary { previous?:AccountSnapshot;current:AccountSnapshot;changes:SnapshotChange[]; }
export interface TimelineEvent { id:string;accountId:string;category:"engagement"|"commercial"|"product"|"support"|"decisions";type:ActivityType;title:string;summary:string;occurredAt:string;source:string;sourceId:string; }
export interface OpenAction { id:string;title:string;owner:string;dueAt:string;status:"open"|"complete";sourceId:string; }
export interface AccountDigitalTwin { accountId:string;generatedAt:string;asOf:string;identity:AccountIdentity;commercialProfile:CommercialProfile;stakeholders:Stakeholder[];stakeholderMap:StakeholderMap;opportunities:Opportunity[];renewalProfile:RenewalProfile|null;productUsage:ProductUsageSummary[];recentActivities:AccountActivity[];fullTimeline:TimelineEvent[];strategicInitiatives:StrategicInitiative[];meddpicc:MEDDPICCProfile;health:AccountHealth;evidence:EvidenceItem[];activeDecisions:GovernedDecision[];historicalDecisions:GovernedDecision[];openActions:OpenAction[];knownRisks:string[];expansionSignals:string[];unresolvedQuestions:string[];dataQuality:DataQualityAssessment;snapshotSummary:SnapshotSummary;sourceCoverage:SourceCoverage[];provenance:ProvenanceRecord[];reconciliation?:ResolvedAccountContext; }
