import type {DecisionClaimCertainty,DecisionClaimType,DecisionType} from "@/domain/decisions/types";

export const decisionTypes:DecisionType[]=["renewal-risk","expansion-opportunity","meeting-preparation","relationship-risk","forecast-risk","executive-action"];
export const decisionClaimTypes:DecisionClaimType[]=["account-identity","financial-impact","date","stakeholder","relationship","product-usage","renewal","opportunity","forecast","meeting","recommendation-rationale","risk","qualification","summary"];
export const decisionClaimCertainties:DecisionClaimCertainty[]=["observed","resolved","corroborated","inferred","disputed","uncertain"];
export const decisionCandidateRequiredFields=["candidateId","accountId","proposedType","proposedCategory","proposedTitle","proposedSummary","whatHappened","whyItMatters","evidenceIds","proposedBusinessImpact","proposedBusinessImpactValue","proposedConfidence","recommendedAction","alternativeActions","responsibleAgent","requiredHumanDecision","generatedAt","reasoningSummary","claimReferences","modelMetadata","contextMetadata"] as const;
export const decisionCandidateOptionalFields=["factIds","dueAt","meetingTime"] as const;
export const decisionCandidateKnownFields=[...decisionCandidateRequiredFields,...decisionCandidateOptionalFields] as const;
export const decisionCandidateSchemaDescriptor={version:"decision-candidate-v2",strictUnknownFields:false,requiredFields:decisionCandidateRequiredFields,optionalFields:decisionCandidateOptionalFields,enums:{proposedType:decisionTypes,"claimReferences.claimType":decisionClaimTypes,"claimReferences.certainty":decisionClaimCertainties},ranges:{proposedConfidence:{minimum:0,maximum:1},proposedBusinessImpactValue:{minimum:0}},rules:["evidenceIds must contain at least one supplied evidence ID","claimReferences must link material claims to supplied fact and evidence IDs","critical claims include lineage IDs when available","dates use valid ISO-8601 timestamps","financial values must be nonnegative and supported by authoritative supplied facts","modelMetadata.synthetic must be true","contextMetadata must match the request and context"]} as const;

const strings={type:"array",items:{type:"string"}} as const;
export const decisionCandidateJsonSchema={type:"object",additionalProperties:false,required:["candidateId","accountId","proposedType","proposedCategory","proposedTitle","proposedSummary","whatHappened","whyItMatters","evidenceIds","factIds","proposedBusinessImpact","proposedBusinessImpactValue","proposedConfidence","recommendedAction","alternativeActions","responsibleAgent","requiredHumanDecision","generatedAt","modelMetadata","reasoningSummary","claimReferences","contextMetadata"],properties:{candidateId:{type:"string"},accountId:{type:"string"},proposedType:{type:"string",enum:decisionTypes},proposedCategory:{type:"string"},proposedTitle:{type:"string"},proposedSummary:{type:"string"},whatHappened:{type:"string"},whyItMatters:{type:"string"},evidenceIds:strings,factIds:strings,proposedBusinessImpact:{type:"string"},proposedBusinessImpactValue:{type:"number",minimum:0},proposedConfidence:{type:"number",minimum:0,maximum:1},recommendedAction:{type:"string"},alternativeActions:strings,responsibleAgent:{type:"string"},requiredHumanDecision:{type:"boolean"},generatedAt:{type:"string"},modelMetadata:{type:"object",additionalProperties:false,required:["provider","model","promptVersion","responseVersion","generatedAt","traceId","synthetic"],properties:{provider:{type:"string"},model:{type:"string"},promptVersion:{type:"string"},responseVersion:{type:"string"},generatedAt:{type:"string"},traceId:{type:"string"},synthetic:{type:"boolean",const:true}}},reasoningSummary:{type:"string"},claimReferences:{type:"array",items:{type:"object",additionalProperties:false,required:["claimId","claimType","text","importance","factIds","evidenceIds","conflictIds","lineageIds","certainty","sourceContextSection"],properties:{claimId:{type:"string"},claimType:{type:"string",enum:decisionClaimTypes},text:{type:"string"},importance:{type:"string",enum:["critical","high","medium","low"]},factIds:strings,evidenceIds:strings,conflictIds:strings,lineageIds:strings,certainty:{type:"string",enum:decisionClaimCertainties},sourceContextSection:{type:"string"}}}},contextMetadata:{type:"object",additionalProperties:false,required:["contextId","contextVersion","taskId","requestId","traceId","outputSchemaVersion"],properties:{contextId:{type:"string"},contextVersion:{type:"string"},taskId:{type:"string"},requestId:{type:"string"},traceId:{type:"string"},outputSchemaVersion:{type:"string"}}}}} as const;

export function renderDecisionCandidateSchema():string{return JSON.stringify(decisionCandidateSchemaDescriptor,null,2);}
