import type {AgentOutputParseResult,AgentReasoner,AgentReasoningError,AgentReasoningMetadata,AgentReasoningRequest,AgentReasoningResult} from "@/domain/agent-reasoning/types";import type {AgentTask} from "@/domain/agents/types";import type {AgentContextPackage} from "@/domain/llm-context/types";import {createReasoningAuditEvent} from "./audit/create-reasoning-audit-event";import {reasoningVersions} from "./config";import {createAgentReasoningRequest} from "./contracts/create-request";import {parseAgentOutput} from "./parsing/parse-agent-output";
const emptyParse=(now:string,version:string):AgentOutputParseResult=>({success:false,errors:[],warnings:[],rawOutputMetadata:{format:"structured-object",size:0,unknownFields:[]},schemaVersion:version,parsedAt:now});
export function runAgentReasoning({context,task,reasoner,outputSchemaVersion=reasoningVersions.decisionCandidateSchemaVersion,now}:{context?:AgentContextPackage;task?:AgentTask;reasoner:AgentReasoner;outputSchemaVersion?:string;now:string}):AgentReasoningResult{
 const fallbackRequest:AgentReasoningRequest={requestId:"invalid-request",traceId:"invalid-trace",contextId:context?.contextId??"missing-context",contextVersion:context?.contextVersion??"missing",accountId:context?.accountId??"missing",agentType:context?.agentType??"renewal-agent",task:task??context?.task??({} as AgentTask),outputSchemaVersion,requestedAt:now,constraints:[],metadata:{simulated:true}};
 let request=fallbackRequest;const startedAt=now,fail=(error:AgentReasoningError):AgentReasoningResult=>({request,parseResult:emptyParse(now,outputSchemaVersion),metadata:{reasonerId:reasoner.id,reasonerVersion:reasoner.version,simulated:true,contextVersion:request.contextVersion,outputSchemaVersion,requestId:request.requestId,traceId:request.traceId,startedAt,completedAt:now,latencyMs:0,retryCount:0,rawOutputFormat:"structured-object",parseStatus:"failed"},auditEvents:[createReasoningAuditEvent({traceId:request.traceId,requestId:request.requestId,contextId:request.contextId,actorType:"agent-reasoner",eventType:"reasoner-failed",timestamp:now,details:{code:error.code}})],errors:[error]});
 if(!context)return fail({code:"missing-context",message:"AgentContextPackage is required.",recoverable:true});
 try{request=createAgentReasoningRequest({context,task,outputSchemaVersion,now});}catch(error){const code=error instanceof Error&&error.message==="unsupported-agent"?"unsupported-agent":"invalid-task";return fail({code,message:error instanceof Error?error.message:"Invalid request.",recoverable:true});}
 if(!reasoner.supportedAgentTypes.includes(request.agentType))return fail({code:"unsupported-agent",message:"Reasoner does not support the requested agent.",recoverable:true});
 if(!reasoner.supportedOutputSchemaVersions.includes(outputSchemaVersion))return fail({code:"unsupported-schema",message:"Reasoner does not support the requested output schema.",recoverable:true});
 const audit=[createReasoningAuditEvent({traceId:request.traceId,requestId:request.requestId,contextId:request.contextId,actorType:"system",eventType:"reasoning-request-created",timestamp:now}),createReasoningAuditEvent({traceId:request.traceId,requestId:request.requestId,contextId:request.contextId,actorType:"agent-reasoner",eventType:"reasoner-started",timestamp:now})];
 try{const response=reasoner.reason(request,context);if(response.rawOutput===""||response.rawOutput===null||response.rawOutput===undefined)return fail({code:"empty-output",message:"Reasoner returned no output.",recoverable:true});const parseResult=parseAgentOutput({response,outputSchemaVersion,now}),metadata:AgentReasoningMetadata={reasonerId:reasoner.id,reasonerVersion:reasoner.version,simulated:true,provider:typeof response.metadata.provider==="string"?response.metadata.provider:undefined,model:typeof response.metadata.model==="string"?response.metadata.model:undefined,contextVersion:context.contextVersion,outputSchemaVersion,requestId:request.requestId,traceId:request.traceId,startedAt,completedAt:now,latencyMs:0,retryCount:0,rawOutputFormat:response.format,parseStatus:parseResult.success?"passed":"failed"};audit.push(createReasoningAuditEvent({traceId:request.traceId,requestId:request.requestId,contextId:request.contextId,candidateId:parseResult.candidate?.candidateId,actorType:"agent-reasoner",eventType:"reasoner-completed",timestamp:now}),createReasoningAuditEvent({traceId:request.traceId,requestId:request.requestId,contextId:request.contextId,candidateId:parseResult.candidate?.candidateId,actorType:"system",eventType:parseResult.success?"output-parsed":"output-parse-failed",timestamp:now,details:{errorCount:parseResult.errors.length}}));return{request,response,parseResult,candidate:parseResult.candidate,metadata,auditEvents:audit,errors:[]};}catch(error){const timeout=error instanceof Error&&error.message.includes("timeout");return fail({code:timeout?"reasoner-timeout":"reasoner-failure",message:error instanceof Error?error.message:"Reasoner failed safely.",recoverable:true});}
}
