import type {AgentEvaluationResult,CandidateEligibilityResult} from "@/domain/agent-evaluation/types";import type {DecisionCandidate,GovernedDecision} from "@/domain/decisions/types";import type {LLMRecording,LLMReplayFixture,LLMResponse} from "@/domain/llm-provider/types";
export type QualityMetricId="grounding"|"hallucination"|"recommendation-specificity"|"recommendation-actionability"|"business-value"|"eligibility"|"traceability"|"conflict-awareness"|"freshness-awareness"|"schema-compliance"|"latency"|"token-usage"|"response-variance"|"human-approval";
export type PromotionOutcome="Approved"|"Conditionally Approved"|"Needs Improvement"|"Rejected"|"Blocked";export type HumanReviewOutcome="Approve"|"Reject"|"Needs Improvement";export type HumanReviewFlag="hallucination"|"weak-recommendation"|"unsupported-claim"|"missing-evidence";
export interface AIQualityScenario{id:string;name:string;description:string;accountId:string;agentType:"renewal-agent";taskType:"assess-risk";contextFixtureId:string;promptId:string;promptVersion:string;providerId:string;modelId:string;outputSchemaVersion:string;evaluationPolicyVersion:string;version:string;tags:string[];}
export interface QualityVersionSet{promptVersion:string;modelVersion:string;providerVersion:string;evaluationVersion:string;contextVersion:string;schemaVersion:string;}
export interface AIQualityRunSample{sampleId:string;runId:string;scenarioId:string;candidate?:DecisionCandidate;evaluation?:AgentEvaluationResult;eligibility?:CandidateEligibilityResult;response?:LLMResponse;parseSuccess:boolean;evaluationSuccess:boolean;recordingId?:string;versions:QualityVersionSet;completedAt:string;}
export interface ApprovedQualityBaseline{baselineId:string;scenarioId:string;candidate:DecisionCandidate;evaluation:AgentEvaluationResult;eligibility:CandidateEligibilityResult;versions:QualityVersionSet;approvedAt:string;approvedBy:string;preferred:boolean;recordingId?:string;}
export interface BaselineClaimComparison{identicalClaims:string[];improvedClaims:string[];unsupportedClaims:string[];missingClaims:string[];}
export interface BaselineComparison{scenarioId:string;baselineId:string;sampleId:string;claims:BaselineClaimComparison;recommendationChanged:boolean;recommendationExplanation:string;businessImpactDelta:number;confidenceDelta:number;decisionTypeConsistent:boolean;eligibilityConsistent:boolean;scoreDelta:number;explanation:string;}
export interface StabilityStatistics{sampleCount:number;mean:number;variance:number;minimum:number;maximum:number;standardDeviation:number;eligibilityConsistency:number;parseConsistency:number;evaluationConsistency:number;promotionConsistency:number;}
export interface QualityMetricDefinition{id:QualityMetricId;definition:string;weight:number;threshold:number;higherIsBetter:boolean;required:boolean;}
export interface QualityMetricResult{id:QualityMetricId;definition:string;score:number;weight:number;threshold:number;passed:boolean;trend:"improved"|"stable"|"regressed"|"unavailable";evidence:string[];explanation:string;}
export interface HumanQualityReview{reviewId:string;runId:string;scenarioId:string;sampleId?:string;recordingId?:string;reviewerId:string;outcome:HumanReviewOutcome;flags:HumanReviewFlag[];notes:string;reviewedAt:string;version:string;}
export interface ApprovedDevelopmentRecording{approvalId:string;recordingId:string;scenarioId:string;recording:LLMRecording;replayFixture:LLMReplayFixture;reviewId:string;approvedBy:string;approvedAt:string;developmentOnly:true;redacted:true;version:string;}
export interface PromotionPolicy{version:string;metricDefinitions:Record<QualityMetricId,QualityMetricDefinition>;minimumOverallScore:number;conditionalOverallScore:number;minimumSamples:number;maximumHallucinationRate:number;humanApprovalRequired:boolean;blockingReviewFlags:HumanReviewFlag[];regressionTolerance:number;requireApprovedRecording:boolean;}
export interface PromotionGateDecision{decisionId:string;runId:string;scenarioId:string;outcome:PromotionOutcome;overallScore:number;passedMetrics:QualityMetricId[];failedMetrics:QualityMetricId[];blockingReasons:string[];conditions:string[];preferredBaselineEligible:boolean;policyVersion:string;decidedAt:string;explanation:string;}
export interface QualityRegression{regressionId:string;dimension:string;baselineValue:string|number;currentValue:string|number;severity:"warning"|"blocking";explanation:string;}
export interface AIQualityEvaluationRunReport{runId:string;scenario:AIQualityScenario;startedAt:string;completedAt:string;overallScore:number;metrics:QualityMetricResult[];promotionDecision:PromotionGateDecision;baselineComparisons:BaselineComparison[];stability:StabilityStatistics;regressions:QualityRegression[];approvedRecordings:ApprovedDevelopmentRecording[];humanReviews:HumanQualityReview[];samples:AIQualityRunSample[];summary:string;metadata:{policyVersion:string;scenarioVersion:string;baselineId:string;versions:QualityVersionSet;};}
export interface ReplayQualityResult{parseSuccess:boolean;evaluationSuccess:boolean;candidate?:DecisionCandidate;evaluation?:AgentEvaluationResult;eligibility?:CandidateEligibilityResult;governedDecisions:GovernedDecision[];errors:string[];}
