import type { AccountFact, FactType, FactValue, FactValueType } from "@/domain/facts/types";
import type { SourceRecord, SalesforceAccountPayload } from "@/domain/sources/types";
import { authorityPolicy, reconciliationPolicy } from "../config";
interface Spec { type:FactType; path:string; value:FactValue; valueType:FactValueType; currency?:string; derivation?:AccountFact["derivationType"] }
const clean=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-");
function specs(record:SourceRecord):Spec[]{const p=record.payload;switch(record.sourceRecordType){
case"salesforce-account":{const a=p as SalesforceAccountPayload;return[{type:"account-name",path:"identity.name",value:a.name,valueType:"string"},{type:"owner",path:"identity.ownerName",value:a.ownerName,valueType:"string"},{type:"annual-contract-value",path:"commercialProfile.annualContractValue",value:a.annualContractValue,valueType:"money",currency:a.currency},{type:"renewal-date",path:"commercialProfile.renewalDate",value:a.renewalDate,valueType:"date"}];}
case"salesforce-opportunity":return"opportunityId" in p?[{type:"opportunity-stage",path:`opportunities.${p.opportunityId}.stage`,value:p.stage,valueType:"status"},{type:"opportunity-value",path:`opportunities.${p.opportunityId}.amount`,value:p.amount,valueType:"money",currency:p.currency},{type:"close-date",path:`opportunities.${p.opportunityId}.closeDate`,value:p.closeDate,valueType:"date"},{type:"forecast-category",path:`opportunities.${p.opportunityId}.forecastCategory`,value:p.forecastCategory,valueType:"enum"}]:[];
case"salesforce-contact":return"contactId" in p?[{type:"stakeholder-title",path:`stakeholders.${p.contactId}.title`,value:p.title,valueType:"string"}]:[];
case"gong-call":return"durationMinutes" in p?[{type:"meeting-occurrence",path:`activities.${record.sourceRecordId}.occurredAt`,value:p.occurredAt,valueType:"date"},...(p.sentiment?[{type:"stakeholder-sentiment" as const,path:`activities.${record.sourceRecordId}.sentiment`,value:p.sentiment,valueType:"enum" as const,derivation:"inferred" as const}]:[]),...(p.outcome?[{type:"meeting-outcome" as const,path:`activities.${record.sourceRecordId}.outcome`,value:p.outcome,valueType:"string" as const}]:[])]:[];
case"email-interaction":return"subject" in p?[...(p.stakeholderTitle&&p.stakeholderId?[{type:"stakeholder-title" as const,path:`stakeholders.${p.stakeholderId}.title`,value:p.stakeholderTitle,valueType:"string" as const}]:[]),...(p.sentiment?[{type:"stakeholder-sentiment" as const,path:`stakeholders.${p.stakeholderId??"unknown"}.sentiment`,value:p.sentiment,valueType:"enum" as const,derivation:"inferred" as const}]:[])]:[];
case"calendar-meeting":return"status" in p?[{type:"meeting-occurrence",path:`activities.${record.sourceRecordId}.occurredAt`,value:p.occurredAt,valueType:"date"}]:[];
case"product-usage":return"productId" in p?[{type:"product-adoption",path:`productUsage.${p.productId}.adoptionRate`,value:p.adoptionRate,valueType:"percentage"},{type:"product-usage-trend",path:`productUsage.${p.productId}.usageTrend`,value:p.usageTrend,valueType:"enum"}]:[];
case"support-event":return"severity" in p?[{type:"support-severity",path:`support.${record.sourceRecordId}.severity`,value:p.severity,valueType:"enum"}]:[];
case"contract":return"totalContractValue" in p?[{type:"annual-contract-value",path:"commercialProfile.annualContractValue",value:p.annualContractValue,valueType:"money",currency:p.currency},{type:"total-contract-value",path:"commercialProfile.totalContractValue",value:p.totalContractValue,valueType:"money",currency:p.currency},{type:"contract-start-date",path:"commercialProfile.contractStartDate",value:p.startDate,valueType:"date"},{type:"contract-end-date",path:"commercialProfile.contractEndDate",value:p.endDate,valueType:"date"},{type:"renewal-date",path:"commercialProfile.renewalDate",value:p.renewalDate,valueType:"date"}]:[];
case"external-news":return"claim" in p?[{type:"strategic-initiative",path:`strategicInitiatives.${clean(p.headline)}`,value:p.claim,valueType:"string",derivation:"inferred"}]:[];
case"manual-verification":return"factType" in p?[{type:p.factType as FactType,path:p.fieldPath,value:p.value,valueType:typeof p.value==="number"?"number":typeof p.value==="boolean"?"boolean":Array.isArray(p.value)?"collection":"string",derivation:"human-override"}]:[];default:return[];}}
export function extractAccountFacts({acceptedRecords,now}:{acceptedRecords:readonly SourceRecord[];policies?:unknown;now:string}){const facts=acceptedRecords.flatMap(record=>specs(record).map((s,index)=>{const policy=authorityPolicy(s.type),rank=policy.preferredSources.indexOf(record.source),fallback=policy.fallbackSources.indexOf(record.source),authorityScore=rank>=0?Math.max(.7,1-rank*.1):fallback>=0?Math.max(.45,.65-fallback*.08):.3;return{id:`fact-${record.sourceRecordId}-${s.type}-${index}`,accountId:record.accountId,factType:s.type,fieldPath:s.path,value:s.value,valueType:s.valueType,currency:s.currency,effectiveAt:record.effectiveAt,observedAt:record.observedAt,ingestedAt:record.ingestedAt,source:record.source,sourceRecordId:record.sourceRecordId,sourceRecordType:record.sourceRecordType,reliability:record.reliability,authorityScore,confidence:Number((authorityScore*.55+record.reliability*.45).toFixed(4)),verificationStatus:s.derivation==="human-override"?"human-verified":"observed",derivationType:s.derivation??"normalized",lineage:[record.id],metadata:{ruleVersion:reconciliationPolicy.ruleVersion,extractedAt:now}} satisfies AccountFact;}));return{facts,recordCount:acceptedRecords.length,extractedFactCount:facts.length};}
