"use client";
import {useState} from "react";
import type {AgentContextPackage} from "@/domain/llm-context/types";
import type {PromptFixture,PromptFixtureRunResult} from "@/domain/prompts/types";
import {defaultEvaluationPolicy} from "@/agent-evaluation";
import {reasonerFixtures,reasoningFixtureIds} from "@/data/evaluation-fixtures/reasoner-fixtures";
import {promptFixtureRegistry} from "@/data/prompt-fixtures/prompt-fixtures";
import {agentTaskNow} from "@/data/synthetic/agent-tasks";
import {comparePromptVersions,validatePromptDefinition} from "@/prompt-registry";
import {runPromptFixture} from "@/prompt-regression";
const pretty=(value:string)=>value.replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase()),key=(accountId:string,agentType:string)=>`${accountId}|${agentType}`;
export function PromptLab({contexts,fixtures}:{contexts:Record<string,AgentContextPackage>;fixtures:PromptFixture[]}){
 "use no memo";
 const[fixtureId,setFixtureId]=useState(fixtures[0]?.fixtureId??"");
 const[reasonerId,setReasonerId]=useState(fixtures[0]?.reasonerFixtureId??"valid");
 const[tokenLimit,setTokenLimit]=useState(20000);
 const[runAll,setRunAll]=useState<PromptFixtureRunResult[]|null>(null);
 const fixture=fixtures.find(item=>item.fixtureId===fixtureId)??fixtures[0];
 const context=fixture?contexts[key(fixture.accountId,fixture.agentType)]:undefined;
 const definition=promptFixtureRegistry.definitions.find(item=>item.promptId===fixture?.promptId&&item.version===fixture.promptVersion);
 const controlledFixture=fixture?{...fixture,reasonerFixtureId:reasonerId,buildPolicy:{...fixture.buildPolicy,maximumPromptTokens:tokenLimit}}:undefined;
 const result=controlledFixture?runPromptFixture({fixture:controlledFixture,registry:promptFixtureRegistry,context,reasoner:reasonerFixtures[reasonerId],evaluatorPolicy:defaultEvaluationPolicy,now:agentTaskNow}):undefined;
 const validation=definition?validatePromptDefinition({definition,registry:promptFixtureRegistry,now:agentTaskNow}):undefined;
 const versions=definition?promptFixtureRegistry.definitions.filter(item=>item.promptId===definition.promptId):[];
 const baseline=versions.find(item=>item.status==="active")??versions[0];
 const diff=definition&&baseline?comparePromptVersions({baseline,candidate:definition}):undefined;
 const selectFixture=(id:string)=>{const next=fixtures.find(item=>item.fixtureId===id);setFixtureId(id);if(next)setReasonerId(next.reasonerFixtureId)};
 const runEveryFixture=()=>setRunAll(fixtures.map(item=>runPromptFixture({fixture:{...item,buildPolicy:{...item.buildPolicy,maximumPromptTokens:item.buildPolicy?.maximumPromptTokens??20000}},registry:promptFixtureRegistry,context:contexts[key(item.accountId,item.agentType)],reasoner:reasonerFixtures[item.reasonerFixtureId],evaluatorPolicy:defaultEvaluationPolicy,now:agentTaskNow})));
 if(!fixture)return <section className="twin-card inspector-error" role="alert"><h1>Prompt Lab unavailable</h1></section>;
 return <article className="context-inspector prompt-lab"><header className="accounts-header"><div><span className="eyebrow">DEVELOPMENT TOOL · CONTROLLED PROMPTS · SIMULATED REASONERS</span><h1>Prompt Lab</h1><p>Inspect prompt selection, deterministic construction, schema grounding, and regression outcomes.</p></div><div className="prompt-actions"><button className="secondary-button" type="button">Validate prompt</button><button className="secondary-button" type="button">Compare versions</button><button className="primary-button" type="button" onClick={runEveryFixture}>Run all prompt fixtures</button></div></header>
  <section className="twin-card inspector-controls prompt-controls" aria-label="Prompt controls"><label>Prompt fixture<select aria-label="Prompt fixture" value={fixtureId} onChange={event=>selectFixture(event.target.value)}>{fixtures.map(item=><option key={item.fixtureId} value={item.fixtureId}>{pretty(item.name)}</option>)}</select></label><label>Account<input aria-label="Account" readOnly value={context?.accountName??fixture.accountId}/></label><label>Agent type<input aria-label="Agent type" readOnly value={pretty(fixture.agentType)}/></label><label>Task type<input aria-label="Task type" readOnly value={pretty(fixture.taskType)}/></label><label>Prompt ID<input aria-label="Prompt ID" readOnly value={fixture.promptId}/></label><label>Prompt version<select aria-label="Prompt version" value={fixture.promptVersion} onChange={event=>{const next=fixtures.find(item=>item.promptId===fixture.promptId&&item.promptVersion===event.target.value);if(next)selectFixture(next.fixtureId)}}>{versions.map(item=><option key={item.version} value={item.version}>{item.version} · {item.status}</option>)}</select></label><label>Context fixture<input aria-label="Context fixture" readOnly value={fixture.contextFixtureId}/></label><label>Reasoner fixture<select aria-label="Reasoner fixture" value={reasonerId} onChange={event=>setReasonerId(event.target.value)}>{reasoningFixtureIds.map(id=><option key={id} value={id}>{pretty(id)}</option>)}</select></label><label>Evaluation policy<input aria-label="Evaluation policy" readOnly value={defaultEvaluationPolicy.version}/></label><label>Token limit<input aria-label="Token limit" type="number" min="100" max="30000" step="500" value={tokenLimit} onChange={event=>setTokenLimit(Number(event.target.value))}/></label></section>
  <section className="reconciliation-metrics inspector-metrics" aria-label="Prompt diagnostics"><span><strong>{result?.build.tokenEstimate.totalEstimatedTokens??0}</strong> estimated tokens</span><span><strong>{result?.build.package?.buildMetadata.contentHash??"not-built"}</strong> content hash</span><span><strong>{validation?.valid?"Valid":"Invalid"}</strong> definition</span><span><strong>{result?.build.package?"Passed":"Failed"}</strong> build</span><span><strong>{result?.evaluation?.verdict??"not-run"}</strong> evaluation</span><span><strong>{result?.regression.expectedOutcomeMatched?"Matched":"Mismatch"}</strong> regression</span></section>
  <div className="inspector-grid">
   <section className="twin-card"><h2>Selected PromptDefinition</h2><pre>{JSON.stringify(definition??result?.selection.errors,null,2)}</pre></section><section className="twin-card"><h2>Metadata and changelog</h2><pre>{JSON.stringify({metadata:definition?.metadata,changelog:definition?.changelog},null,2)}</pre></section><section className="twin-card"><h2>Context section policy</h2><pre>{JSON.stringify(definition?.contextSectionPolicy,null,2)}</pre></section><section className="twin-card"><h2>Validation</h2><pre>{JSON.stringify(validation,null,2)}</pre></section>
   <section className="twin-card twin-wide"><h2>Prompt messages</h2>{result?.build.package?.messages.map(message=><details open key={message.role}><summary>{pretty(message.role)} message</summary><pre>{message.content}</pre></details>)??<pre>{JSON.stringify(result?.build.errors,null,2)}</pre>}</section>
   <section className="twin-card"><h2>Output schema instructions</h2><pre>{result?.build.package?.schemaContract??"Not built"}</pre></section><section className="twin-card"><h2>Citation instructions</h2><pre>{JSON.stringify(result?.build.package?.citationPolicy??definition?.citationPolicy,null,2)}</pre></section><section className="twin-card"><h2>Uncertainty instructions</h2><pre>{JSON.stringify(result?.build.package?.uncertaintyPolicy??definition?.uncertaintyPolicy,null,2)}</pre></section><section className="twin-card"><h2>Prohibited behaviors</h2><pre>{JSON.stringify(result?.build.package?.prohibitedBehaviors??definition?.prohibitedBehaviors,null,2)}</pre></section>
   <section className="twin-card"><h2>Token estimate and build findings</h2><pre>{JSON.stringify({estimate:result?.build.tokenEstimate,warnings:result?.build.warnings,errors:result?.build.errors},null,2)}</pre></section><section className="twin-card"><h2>Prompt version diff</h2><pre>{JSON.stringify(diff,null,2)}</pre></section><section className="twin-card"><h2>Simulated reasoner output</h2><pre>{JSON.stringify(result?.reasoning?.response?.rawOutput??result?.reasoning?.errors??"Not run",null,2)}</pre></section><section className="twin-card"><h2>Parsed DecisionCandidate</h2><pre>{JSON.stringify(result?.reasoning?.candidate??result?.reasoning?.parseResult.errors??"Not parsed",null,2)}</pre></section><section className="twin-card"><h2>Evaluation result</h2><pre>{JSON.stringify(result?.evaluation??"Not evaluated",null,2)}</pre></section><section className="twin-card"><h2>Regression outcome</h2><pre>{JSON.stringify(result?.regression,null,2)}</pre></section>
  </div>{runAll&&<section className="twin-card twin-wide reasoning-report" aria-live="polite"><h2>All prompt fixtures</h2><p>{runAll.length} fixtures · {runAll.filter(item=>item.regression.expectedOutcomeMatched).length} matched · {runAll.filter(item=>item.regression.regressed).length} regressions</p></section>}
 </article>;
}
