import type {AccountDigitalTwin} from "@/domain/accounts/account-digital-twin";import type {ContextCaveat,ContextClaim,ContextDecision,RecentChange} from "@/domain/llm-context/types";
const linked=(text:string,claim?:ContextClaim)=>claim?`${text} [${claim.id}]`:text;
export function buildDeterministicAccountSummary({twin,claims,changes,decisions,caveats,compact=false}:{twin:AccountDigitalTwin;claims:ContextClaim[];changes:RecentChange[];decisions:ContextDecision[];caveats:ContextCaveat[];compact?:boolean}){const risk=twin.knownRisks[0]??"No validated material risk",opportunity=twin.expansionSignals[0]??"No validated expansion signal",decision=decisions[0],change=changes[0],uncertainty=caveats[0]?.description??twin.unresolvedQuestions[0]??"No material uncertainty is currently identified",healthClaim=claims.find(claim=>claim.text.includes("account health")),renewalClaim=claims.find(claim=>claim.text.startsWith("renewal date"));if(compact)return `${twin.identity.name}: ${twin.health.overallStatus} (${twin.health.overallScore}/100). Risk: ${risk} Opportunity: ${opportunity} Decision: ${decision?.recommendedAction??"none"} Uncertainty: ${uncertainty}`;return `${linked(`${twin.identity.name} is ${twin.health.overallStatus} at ${twin.health.overallScore}/100 with a ${twin.health.trend} trend`,healthClaim)}. Most important recent change: ${change?.description??"No material snapshot change"}. Top risk: ${risk}. Top opportunity: ${opportunity}. Most important open decision: ${decision?`${decision.summary}; ${decision.recommendedAction}`:"No active governed decision"}. Key uncertainty: ${uncertainty}${renewalClaim?` [${renewalClaim.id}]`:""}.`;}

export function compressAccountSummary(summary:string){
 const sentences=summary.match(/[^.]+\.(?:\s|$)/g)?.map(sentence=>sentence.trim())??[summary];
 const prefixes=["Top risk:","Top opportunity:","Most important open decision:","Key uncertainty:"];
 return [sentences[0],...prefixes.map(prefix=>sentences.find(sentence=>sentence.includes(prefix)))].filter((value):value is string=>Boolean(value)).join(" ");
}
