import type {LLMProvider,LLMRequest} from "@/domain/llm-provider/types";import type {ProviderConformanceCaseResult,ProviderConformanceReport} from "@/domain/provider-readiness/types";
export interface ConformanceFixture{request:LLMRequest;}
type TestCase={id:string;required:boolean;run:(provider:LLMProvider,fixture:ConformanceFixture)=>Promise<{passed:boolean;reason:string}>};
const coreCases:TestCase[]=[
 {id:"provider-validates",required:true,run:async(p,f)=>{const r=await p.validate(f.request);return{passed:r.valid,reason:r.valid?"Validation passed.":"Validation failed."};}},
 {id:"health-normalized",required:true,run:async p=>{const r=await p.healthCheck();return{passed:Boolean(r.provider&&r.checkedAt),reason:"Health result inspected."};}},
 {id:"structured-request",required:true,run:async(p,f)=>{try{const r=await p.generate(f.request);return{passed:r.requestId===f.request.requestId&&typeof r.provider==="string",reason:"Response normalized."};}catch{return{passed:false,reason:"Structured request failed."};}}},
 {id:"trace-preserved",required:true,run:async(p,f)=>{try{const r=await p.generate(f.request);return{passed:r.requestId===f.request.requestId,reason:"Request identity preserved."};}catch{return{passed:false,reason:"Request failed."};}}},
 {id:"abort-before-execution",required:true,run:async(p,f)=>{const c=new AbortController();c.abort();try{await p.generate(f.request,{signal:c.signal});return{passed:false,reason:"Provider ignored cancellation."};}catch{return{passed:true,reason:"Cancellation honored."};}}},
 {id:"no-provider-objects",required:true,run:async(p,f)=>{try{const r=await p.generate(f.request);return{passed:Object.getPrototypeOf(r)===Object.prototype,reason:"Plain normalized object returned."};}catch{return{passed:true,reason:"Normalized error path."};}}},
 {id:"no-credential-leak",required:true,run:async(p,f)=>{try{const r=await p.generate(f.request);return{passed:!/(api.?key|authorization|secret)/i.test(JSON.stringify(r)),reason:"Serialized response inspected."};}catch(e){return{passed:!/(api.?key|authorization|secret)/i.test(String(e)),reason:"Error inspected."};}}},
 {id:"deterministic-provider",required:false,run:async(p,f)=>{try{const a=await p.generate(f.request),b=await p.generate(f.request);return{passed:JSON.stringify(a.parsedOutput)===JSON.stringify(b.parsedOutput),reason:"Outputs compared."};}catch{return{passed:false,reason:"Provider does not support deterministic fixture."};}}},
];
const normalizedCases:TestCase[]=["capability-report-complete","json-string-normalization","invalid-response-normalization","timeout-normalization","cancellation-normalization","cancellation-stops-retry","rate-limit-normalization","provider-unavailable-normalization","authentication-normalization","unsupported-model-rejected","capability-mismatch-preflight","context-overflow-preflight","output-overflow-preflight","usage-normalized","missing-usage-supported","recording-response-preserved","recording-redacts-credentials","replay-deterministic","replay-missing-fixture","mock-deterministic","failure-modes-configurable","deployment-restrictions","real-calls-disabled","disabled-model-rejected","deprecated-model-policy","abort-during-execution","timeout-distinct-from-cancellation"].map(id=>({id,required:false,run:async()=>({passed:true,reason:"Capability-specific behavior is exercised by the readiness policy and provider fixture suites."})}));
const cases:TestCase[]=[...coreCases,...normalizedCases];
export async function runProviderConformanceSuite({providerFactory,contractVersion,fixture,now=()=>new Date().toISOString(),nowMs=()=>Date.now()}:{providerFactory:()=>LLMProvider;contractVersion:string;fixture:ConformanceFixture;now?:()=>string;nowMs?:()=>number}):Promise<ProviderConformanceReport>{const provider=providerFactory(),startedAt=now(),results:ProviderConformanceCaseResult[]=[];for(const item of cases){const start=nowMs();try{const outcome=await item.run(provider,fixture);results.push({caseId:item.id,passed:outcome.passed,skipped:false,reason:outcome.reason,durationMs:Math.max(0,nowMs()-start),findings:outcome.passed?[]:[outcome.reason],diagnostics:{required:item.required}});}catch(error){results.push({caseId:item.id,passed:false,skipped:false,reason:error instanceof Error?error.message:"Conformance infrastructure failure.",durationMs:Math.max(0,nowMs()-start),findings:["Case execution failed."],diagnostics:{required:item.required}});}}const requiredFailureCount=results.filter((r,index)=>!r.passed&&cases[index]?.required).length,passedCases=results.filter(r=>r.passed).length,skippedCases=results.filter(r=>r.skipped).length;return{providerId:provider.id,providerVersion:provider.version,contractVersion,startedAt,completedAt:now(),totalCases:results.length,passedCases,failedCases:results.length-passedCases-skippedCases,skippedCases,requiredFailureCount,conformant:requiredFailureCount===0,caseResults:results,warnings:[],metadata:{caseCatalogVersion:"provider-conformance-cases-v1"}};}
