import type {CredentialResolutionResult,CredentialResolver,CredentialResolverRegistry,DeploymentEnvironment,ProviderCredentialReference,ResolvedProviderCredential} from "@/domain/provider-readiness/types";import {providerError} from "./errors";
const vault=new WeakMap<ResolvedProviderCredential,string>();
function opaque(reference:ProviderCredentialReference,value:string):ResolvedProviderCredential{const credential:ResolvedProviderCredential={providerId:reference.providerId,credentialType:reference.credentialType,source:reference.source,resolved:true,metadata:{referenceId:reference.referenceId},toJSON(){return{providerId:this.providerId,credentialType:this.credentialType,source:this.source,resolved:this.resolved,metadata:this.metadata};}};vault.set(credential,value);return credential;}
export function accessResolvedSecret(credential:ResolvedProviderCredential,consumer:(value:string)=>void):void{const secret=vault.get(credential);if(!secret)throw new Error("Credential secret is unavailable.");consumer(secret);}
const result=(credential:ResolvedProviderCredential|undefined,errors:ReturnType<typeof providerError>[],now:()=>string):CredentialResolutionResult=>({credential,errors,warnings:[],resolvedAt:now()});
export function createEnvironmentCredentialResolver(values:Readonly<Record<string,string|undefined>>,now=()=>new Date().toISOString()):CredentialResolver{return{source:"environment",async resolve(reference,environment){if(environment!=="development"&&environment!=="test")return result(undefined,[providerError("environment-credential-blocked","configuration","Environment credentials are limited to development and test.",now)],now);const value=values[reference.locator];return value?result(opaque(reference,value),[],now):result(undefined,[providerError("credential-missing","authentication","Required environment credential is missing.",now)],now);}};}
export function createDevelopmentCredentialResolver(values:Readonly<Record<string,string|undefined>>,now=()=>new Date().toISOString()):CredentialResolver{return{source:"development-secret",async resolve(reference,environment){if(environment==="production")return result(undefined,[providerError("development-credential-blocked","configuration","Development credentials are disabled in production.",now)],now);const value=values[reference.locator];return value?result(opaque(reference,value),[],now):result(undefined,[providerError("credential-missing","authentication","Development credential fixture is missing.",now)],now);}};}
export function createUnsupportedCredentialResolver(source:"secret-manager"|"workload-identity",now=()=>new Date().toISOString()):CredentialResolver{return{source,async resolve(){return result(undefined,[providerError(`${source}-unsupported`,"configuration",`${source} resolution is not implemented.`,now)],now);}};}
export function createMissingCredentialResolver(now=()=>new Date().toISOString()):CredentialResolver{return{source:"none",async resolve(){return result(undefined,[providerError("credential-missing","authentication","Credential could not be resolved.",now)],now);}};}
export function createCredentialResolverRegistry(resolvers:CredentialResolver[]):CredentialResolverRegistry{return{resolvers:new Map(resolvers.map(item=>[item.source,item]))};}
export async function resolveProviderCredential({reference,environment,resolverRegistry}:{reference:ProviderCredentialReference;environment:DeploymentEnvironment;resolverRegistry:CredentialResolverRegistry}):Promise<CredentialResolutionResult>{const resolver=resolverRegistry.resolvers.get(reference.source);return resolver?resolver.resolve(reference,environment):{errors:[providerError("resolver-missing","configuration",`No resolver registered for ${reference.source}.`)],warnings:[],resolvedAt:new Date().toISOString()};}
