import type {Permission} from "./permissions";
import {permissions,rolePermissions} from "./permissions";
import type {IdentityRepository} from "./repository";
import type {OrganizationMembership,ResourceType,User} from "./types";
import {getUserScope} from "./hierarchy";
import {activeRoleAssignments,getMembership} from "./tenant-model";

const platformPermissions=new Set<Permission>([permissions.platformOrganizationCreate,permissions.platformOrganizationRead,permissions.platformOrganizationManage,permissions.platformOrganizationSuspend]);
const adminPermissions=new Set<Permission>([permissions.organizationSettingsRead,permissions.organizationSettingsUpdate,permissions.userInvite,permissions.userRead,permissions.userUpdate,permissions.userDeactivate,permissions.roleRead,permissions.roleCreate,permissions.roleUpdate,permissions.roleAssign,permissions.orgUnitRead,permissions.orgUnitCreate,permissions.orgUnitUpdate,permissions.relationshipRead,permissions.relationshipCreate,permissions.relationshipUpdate,permissions.integrationConfigure,permissions.methodologyConfigure,permissions.governanceConfigure,permissions.auditRead]);
export function resolvePermissions(repository:IdentityRepository,user:User,membership?:OrganizationMembership){const result=new Set<Permission>();if(user.platformRole==="SUPER_ADMIN")for(const item of platformPermissions)result.add(item);if(!membership||membership.status!=="ACTIVE")return result;if(membership.adminRole==="ORG_OWNER"||membership.adminRole==="ORG_ADMIN")for(const item of adminPermissions)result.add(item);const store=repository.read();for(const assignment of activeRoleAssignments(repository,membership.id)){const definition=store.organizationRoles.find(item=>item.id===assignment.organizationRoleDefinitionId);if(!definition?.isActive)continue;const template=definition.systemTemplateId?store.systemRoleTemplates.find(item=>item.id===definition.systemTemplateId):undefined;for(const permission of [...(template?.defaultPermissions??[]),...definition.permissions])result.add(permission as Permission)}for(const[permission,allowed]of Object.entries(membership.permissionOverrides??{}))if(allowed)result.add(permission as Permission);else result.delete(permission as Permission);return result}
export function canViewAs(user:User):boolean;
export function canViewAs(repository:IdentityRepository,user:User,organizationId?:string):boolean;
export function canViewAs(first:IdentityRepository|User,second?:User,organizationId?:string){if(!second){const user=first as User;return user.status==="ACTIVE"&&(user.isDemoUser||user.isAdmin)}const repository=first as IdentityRepository,membership=getMembership(repository,second.id,organizationId??second.organizationId);return second.status==="ACTIVE"&&Boolean(second.isDemoUser&&(membership?.adminRole==="ORG_OWNER"||membership?.adminRole==="ORG_ADMIN"))}
export function authorizePermission(user:User,permission:Permission,repository?:IdentityRepository,organizationId=user.organizationId){if(!repository)return user.status==="ACTIVE"&&rolePermissions[user.role].has(permission);const membership=getMembership(repository,user.id,organizationId);return user.status==="ACTIVE"&&resolvePermissions(repository,user,membership).has(permission)}
export function isResourceInScope(repository:IdentityRepository,user:User,resourceType:ResourceType,resourceId:string,resourceOrganizationId:string){const membership=getMembership(repository,user.id,resourceOrganizationId);if(user.status!=="ACTIVE"||!membership||membership.status!=="ACTIVE")return false;if(resourceType==="organization")return resourceId===membership.organizationId;const scope=getUserScope(repository,user.id,resourceOrganizationId);if(!scope||scope.organizationId!==resourceOrganizationId)return false;if(resourceType==="account")return scope.accountIds.includes(resourceId);if(resourceType==="opportunity")return scope.opportunityIds.includes(resourceId);if(resourceType==="seller")return scope.userIds.includes(resourceId);return repository.read().revenueTeamAssignments.some(item=>item.organizationId===resourceOrganizationId&&item.membershipId===membership.id&&(item.accountId===resourceId||item.opportunityId===resourceId))}
export function authorizeResource(repository:IdentityRepository,user:User,permission:Permission,resourceType:ResourceType,resourceId:string,resourceOrganizationId:string){return authorizePermission(user,permission,repository,resourceOrganizationId)&&isResourceInScope(repository,user,resourceType,resourceId,resourceOrganizationId)}
