import type {IdentityRepository} from "./repository";
import type {OrganizationMembership,PublicUser} from "./types";
import {toPublicUser} from "./types";
import {getMembership,primaryRoleContext} from "./tenant-model";

const current=(from:string|null,to:string|null)=>(!from||Date.parse(from)<=Date.now())&&(!to||Date.parse(to)>Date.now());
function context(repository:IdentityRepository,userId:string){const store=repository.read(),user=store.users.find(item=>item.id===userId),membership=user?store.memberships.find(item=>item.userId===userId&&item.organizationId===user.organizationId&&item.status==="ACTIVE"):undefined;return user&&membership?{store,user,membership}:null}
function usersForMemberships(store:ReturnType<IdentityRepository["read"]>,memberships:OrganizationMembership[]){const ids=new Set(memberships.map(item=>item.userId));return store.users.filter(item=>ids.has(item.id)&&item.status==="ACTIVE").map(toPublicUser)}
export function getDirectReports(repository:IdentityRepository,userId:string):PublicUser[]{const ctx=context(repository,userId);if(!ctx)return[];const ids=new Set(ctx.store.relationships.filter(item=>item.organizationId===ctx.membership.organizationId&&item.relationshipType==="REPORTS_TO"&&item.targetMembershipId===ctx.membership.id&&current(item.effectiveFrom,item.effectiveTo)).map(item=>item.sourceMembershipId));return usersForMemberships(ctx.store,ctx.store.memberships.filter(item=>ids.has(item.id)))}
export function getAllDescendants(repository:IdentityRepository,userId:string):PublicUser[]{const ctx=context(repository,userId);if(!ctx)return[];const edges=ctx.store.relationships.filter(item=>item.organizationId===ctx.membership.organizationId&&item.relationshipType==="REPORTS_TO"&&current(item.effectiveFrom,item.effectiveTo)),children=new Map<string,string[]>();for(const edge of edges)children.set(edge.targetMembershipId,[...(children.get(edge.targetMembershipId)??[]),edge.sourceMembershipId]);const found:string[]=[],queue=[...(children.get(ctx.membership.id)??[])],seen=new Set([ctx.membership.id]);while(queue.length){const id=queue.shift()!;if(seen.has(id))continue;seen.add(id);found.push(id);queue.push(...(children.get(id)??[]))}return usersForMemberships(ctx.store,ctx.store.memberships.filter(item=>found.includes(item.id)))}
export function getManagerChain(repository:IdentityRepository,userId:string):PublicUser[]{const ctx=context(repository,userId);if(!ctx)return[];const edges=ctx.store.relationships.filter(item=>item.organizationId===ctx.membership.organizationId&&item.relationshipType==="REPORTS_TO"&&item.isPrimary&&current(item.effectiveFrom,item.effectiveTo)),manager=new Map(edges.map(item=>[item.sourceMembershipId,item.targetMembershipId])),ids:string[]=[],seen=new Set<string>();let cursor=manager.get(ctx.membership.id);while(cursor&&!seen.has(cursor)){seen.add(cursor);ids.push(cursor);cursor=manager.get(cursor)}const memberships=new Map(ctx.store.memberships.map(item=>[item.id,item])),users=new Map(ctx.store.users.map(item=>[item.id,item]));return ids.map(id=>users.get(memberships.get(id)?.userId??"")).filter(Boolean).map(item=>toPublicUser(item!))}
export function getDottedLineRelationships(repository:IdentityRepository,userId:string){const ctx=context(repository,userId);if(!ctx)return[];return ctx.store.relationships.filter(item=>item.organizationId===ctx.membership.organizationId&&item.sourceMembershipId===ctx.membership.id&&item.relationshipType==="DOTTED_LINE_TO"&&current(item.effectiveFrom,item.effectiveTo))}
export function getOrganizationalUnitsLedByUser(repository:IdentityRepository,userId:string){const ctx=context(repository,userId);return ctx?ctx.store.organizationalUnits.filter(item=>item.organizationId===ctx.membership.organizationId&&item.leaderMembershipId===ctx.membership.id):[]}
function collaborations(repository:IdentityRepository,userId:string){const ctx=context(repository,userId);return ctx?ctx.store.revenueTeamAssignments.filter(item=>item.organizationId===ctx.membership.organizationId&&item.membershipId===ctx.membership.id):[]}
export function getAccountsAssignedToUser(repository:IdentityRepository,userId:string){return [...new Set(collaborations(repository,userId).map(item=>item.accountId).filter(Boolean) as string[])]}
export function getOpportunitiesSupportedByUser(repository:IdentityRepository,userId:string){return [...new Set(collaborations(repository,userId).map(item=>item.opportunityId).filter(Boolean) as string[])]}
export function getRevenueTeamMembers(repository:IdentityRepository,organizationId:string,input:{accountId?:string;opportunityId?:string}){const store=repository.read(),assignments=store.revenueTeamAssignments.filter(item=>item.organizationId===organizationId&&(input.accountId?item.accountId===input.accountId:item.opportunityId===input.opportunityId)),memberships=new Map(store.memberships.filter(item=>item.organizationId===organizationId).map(item=>[item.id,item]));return assignments.map(assignment=>({assignment,membership:memberships.get(assignment.membershipId),user:store.users.find(item=>item.id===memberships.get(assignment.membershipId)?.userId)}))}
export function getOpportunitiesAssignedToDirectReports(repository:IdentityRepository,userId:string){return [...new Set(getDirectReports(repository,userId).flatMap(user=>getOpportunitiesSupportedByUser(repository,user.id)))]}
export function getSESupportedOpportunitiesForManager(repository:IdentityRepository,userId:string){return [...new Set(getAllDescendants(repository,userId).filter(user=>primaryRoleContext(repository,getMembership(repository,user.id,user.organizationId)!.id).template?.code==="SALES_ENGINEER").flatMap(user=>getOpportunitiesSupportedByUser(repository,user.id)))]}
export function getPartnerSupportedOpportunities(repository:IdentityRepository,userId:string){return collaborations(repository,userId).filter(item=>item.participationType==="PARTNER").map(item=>item.opportunityId).filter(Boolean) as string[]}
export function getUserScope(repository:IdentityRepository,userId:string){const ctx=context(repository,userId);if(!ctx)return null;const role=primaryRoleContext(repository,ctx.membership.id).template?.code,descendants=getAllDescendants(repository,userId),managed=role==="RSM"||role==="VP_SALES"||role==="CRO"?descendants:role==="SALES_ENGINEER_MANAGER"?descendants.filter(user=>primaryRoleContext(repository,getMembership(repository,user.id,user.organizationId)!.id).template?.code==="SALES_ENGINEER"):[],visible=[ctx.user,...managed],membershipIds=new Set(visible.map(user=>getMembership(repository,user.id,ctx.membership.organizationId)?.id).filter(Boolean)),assignments=ctx.store.revenueTeamAssignments.filter(item=>item.organizationId===ctx.membership.organizationId&&membershipIds.has(item.membershipId));return{organizationId:ctx.membership.organizationId,userIds:[...new Set(visible.map(item=>item.id))],accountIds:[...new Set(assignments.map(item=>item.accountId).filter(Boolean) as string[])],opportunityIds:[...new Set(assignments.map(item=>item.opportunityId).filter(Boolean) as string[])],teamIds:[...new Set(ctx.store.unitMemberships.filter(item=>membershipIds.has(item.membershipId)).map(item=>item.organizationalUnitId))]}}
